package com.hospital.ontology.lis;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;
import java.util.*;

@Component
public class AutoimmuneSerologySopCatalog {

    @Data
    @AllArgsConstructor
    public static class LabHandlingSop {
        private String sopCode;
        private String assayTitle;
        private String preAnalyticalStabilityProtocol;
        private String validatedAnalyzerPlatform;
        private String criticalActionGuideline;
    }

    private final Map<String, LabHandlingSop> sops = new LinkedHashMap<>();

    public AutoimmuneSerologySopCatalog() {
        initializeSops();
    }

    private void initializeSops() {
        sops.put("SOP-LIS-AUTO-001", new LabHandlingSop("SOP-LIS-AUTO-001", "AutoimmuneSerologySop Analytical Protocol #1", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-002", new LabHandlingSop("SOP-LIS-AUTO-002", "AutoimmuneSerologySop Analytical Protocol #2", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-003", new LabHandlingSop("SOP-LIS-AUTO-003", "AutoimmuneSerologySop Analytical Protocol #3", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-004", new LabHandlingSop("SOP-LIS-AUTO-004", "AutoimmuneSerologySop Analytical Protocol #4", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-005", new LabHandlingSop("SOP-LIS-AUTO-005", "AutoimmuneSerologySop Analytical Protocol #5", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-006", new LabHandlingSop("SOP-LIS-AUTO-006", "AutoimmuneSerologySop Analytical Protocol #6", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-007", new LabHandlingSop("SOP-LIS-AUTO-007", "AutoimmuneSerologySop Analytical Protocol #7", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-008", new LabHandlingSop("SOP-LIS-AUTO-008", "AutoimmuneSerologySop Analytical Protocol #8", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-009", new LabHandlingSop("SOP-LIS-AUTO-009", "AutoimmuneSerologySop Analytical Protocol #9", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-010", new LabHandlingSop("SOP-LIS-AUTO-010", "AutoimmuneSerologySop Analytical Protocol #10", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-011", new LabHandlingSop("SOP-LIS-AUTO-011", "AutoimmuneSerologySop Analytical Protocol #11", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-012", new LabHandlingSop("SOP-LIS-AUTO-012", "AutoimmuneSerologySop Analytical Protocol #12", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-013", new LabHandlingSop("SOP-LIS-AUTO-013", "AutoimmuneSerologySop Analytical Protocol #13", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-014", new LabHandlingSop("SOP-LIS-AUTO-014", "AutoimmuneSerologySop Analytical Protocol #14", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-015", new LabHandlingSop("SOP-LIS-AUTO-015", "AutoimmuneSerologySop Analytical Protocol #15", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-016", new LabHandlingSop("SOP-LIS-AUTO-016", "AutoimmuneSerologySop Analytical Protocol #16", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-017", new LabHandlingSop("SOP-LIS-AUTO-017", "AutoimmuneSerologySop Analytical Protocol #17", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-018", new LabHandlingSop("SOP-LIS-AUTO-018", "AutoimmuneSerologySop Analytical Protocol #18", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-019", new LabHandlingSop("SOP-LIS-AUTO-019", "AutoimmuneSerologySop Analytical Protocol #19", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-020", new LabHandlingSop("SOP-LIS-AUTO-020", "AutoimmuneSerologySop Analytical Protocol #20", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-021", new LabHandlingSop("SOP-LIS-AUTO-021", "AutoimmuneSerologySop Analytical Protocol #21", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-022", new LabHandlingSop("SOP-LIS-AUTO-022", "AutoimmuneSerologySop Analytical Protocol #22", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-023", new LabHandlingSop("SOP-LIS-AUTO-023", "AutoimmuneSerologySop Analytical Protocol #23", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-024", new LabHandlingSop("SOP-LIS-AUTO-024", "AutoimmuneSerologySop Analytical Protocol #24", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-025", new LabHandlingSop("SOP-LIS-AUTO-025", "AutoimmuneSerologySop Analytical Protocol #25", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-026", new LabHandlingSop("SOP-LIS-AUTO-026", "AutoimmuneSerologySop Analytical Protocol #26", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-027", new LabHandlingSop("SOP-LIS-AUTO-027", "AutoimmuneSerologySop Analytical Protocol #27", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-028", new LabHandlingSop("SOP-LIS-AUTO-028", "AutoimmuneSerologySop Analytical Protocol #28", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-029", new LabHandlingSop("SOP-LIS-AUTO-029", "AutoimmuneSerologySop Analytical Protocol #29", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-030", new LabHandlingSop("SOP-LIS-AUTO-030", "AutoimmuneSerologySop Analytical Protocol #30", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-031", new LabHandlingSop("SOP-LIS-AUTO-031", "AutoimmuneSerologySop Analytical Protocol #31", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-032", new LabHandlingSop("SOP-LIS-AUTO-032", "AutoimmuneSerologySop Analytical Protocol #32", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-033", new LabHandlingSop("SOP-LIS-AUTO-033", "AutoimmuneSerologySop Analytical Protocol #33", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-034", new LabHandlingSop("SOP-LIS-AUTO-034", "AutoimmuneSerologySop Analytical Protocol #34", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-035", new LabHandlingSop("SOP-LIS-AUTO-035", "AutoimmuneSerologySop Analytical Protocol #35", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-036", new LabHandlingSop("SOP-LIS-AUTO-036", "AutoimmuneSerologySop Analytical Protocol #36", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-037", new LabHandlingSop("SOP-LIS-AUTO-037", "AutoimmuneSerologySop Analytical Protocol #37", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-038", new LabHandlingSop("SOP-LIS-AUTO-038", "AutoimmuneSerologySop Analytical Protocol #38", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-039", new LabHandlingSop("SOP-LIS-AUTO-039", "AutoimmuneSerologySop Analytical Protocol #39", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-040", new LabHandlingSop("SOP-LIS-AUTO-040", "AutoimmuneSerologySop Analytical Protocol #40", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-041", new LabHandlingSop("SOP-LIS-AUTO-041", "AutoimmuneSerologySop Analytical Protocol #41", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-042", new LabHandlingSop("SOP-LIS-AUTO-042", "AutoimmuneSerologySop Analytical Protocol #42", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-043", new LabHandlingSop("SOP-LIS-AUTO-043", "AutoimmuneSerologySop Analytical Protocol #43", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-044", new LabHandlingSop("SOP-LIS-AUTO-044", "AutoimmuneSerologySop Analytical Protocol #44", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-045", new LabHandlingSop("SOP-LIS-AUTO-045", "AutoimmuneSerologySop Analytical Protocol #45", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-046", new LabHandlingSop("SOP-LIS-AUTO-046", "AutoimmuneSerologySop Analytical Protocol #46", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-047", new LabHandlingSop("SOP-LIS-AUTO-047", "AutoimmuneSerologySop Analytical Protocol #47", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-048", new LabHandlingSop("SOP-LIS-AUTO-048", "AutoimmuneSerologySop Analytical Protocol #48", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-049", new LabHandlingSop("SOP-LIS-AUTO-049", "AutoimmuneSerologySop Analytical Protocol #49", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-050", new LabHandlingSop("SOP-LIS-AUTO-050", "AutoimmuneSerologySop Analytical Protocol #50", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-051", new LabHandlingSop("SOP-LIS-AUTO-051", "AutoimmuneSerologySop Analytical Protocol #51", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-052", new LabHandlingSop("SOP-LIS-AUTO-052", "AutoimmuneSerologySop Analytical Protocol #52", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-053", new LabHandlingSop("SOP-LIS-AUTO-053", "AutoimmuneSerologySop Analytical Protocol #53", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-054", new LabHandlingSop("SOP-LIS-AUTO-054", "AutoimmuneSerologySop Analytical Protocol #54", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-055", new LabHandlingSop("SOP-LIS-AUTO-055", "AutoimmuneSerologySop Analytical Protocol #55", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-056", new LabHandlingSop("SOP-LIS-AUTO-056", "AutoimmuneSerologySop Analytical Protocol #56", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-057", new LabHandlingSop("SOP-LIS-AUTO-057", "AutoimmuneSerologySop Analytical Protocol #57", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-058", new LabHandlingSop("SOP-LIS-AUTO-058", "AutoimmuneSerologySop Analytical Protocol #58", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-059", new LabHandlingSop("SOP-LIS-AUTO-059", "AutoimmuneSerologySop Analytical Protocol #59", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-060", new LabHandlingSop("SOP-LIS-AUTO-060", "AutoimmuneSerologySop Analytical Protocol #60", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-061", new LabHandlingSop("SOP-LIS-AUTO-061", "AutoimmuneSerologySop Analytical Protocol #61", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-062", new LabHandlingSop("SOP-LIS-AUTO-062", "AutoimmuneSerologySop Analytical Protocol #62", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-063", new LabHandlingSop("SOP-LIS-AUTO-063", "AutoimmuneSerologySop Analytical Protocol #63", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-064", new LabHandlingSop("SOP-LIS-AUTO-064", "AutoimmuneSerologySop Analytical Protocol #64", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-065", new LabHandlingSop("SOP-LIS-AUTO-065", "AutoimmuneSerologySop Analytical Protocol #65", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-066", new LabHandlingSop("SOP-LIS-AUTO-066", "AutoimmuneSerologySop Analytical Protocol #66", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-067", new LabHandlingSop("SOP-LIS-AUTO-067", "AutoimmuneSerologySop Analytical Protocol #67", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-068", new LabHandlingSop("SOP-LIS-AUTO-068", "AutoimmuneSerologySop Analytical Protocol #68", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-069", new LabHandlingSop("SOP-LIS-AUTO-069", "AutoimmuneSerologySop Analytical Protocol #69", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-070", new LabHandlingSop("SOP-LIS-AUTO-070", "AutoimmuneSerologySop Analytical Protocol #70", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-071", new LabHandlingSop("SOP-LIS-AUTO-071", "AutoimmuneSerologySop Analytical Protocol #71", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-072", new LabHandlingSop("SOP-LIS-AUTO-072", "AutoimmuneSerologySop Analytical Protocol #72", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-073", new LabHandlingSop("SOP-LIS-AUTO-073", "AutoimmuneSerologySop Analytical Protocol #73", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-074", new LabHandlingSop("SOP-LIS-AUTO-074", "AutoimmuneSerologySop Analytical Protocol #74", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-075", new LabHandlingSop("SOP-LIS-AUTO-075", "AutoimmuneSerologySop Analytical Protocol #75", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-076", new LabHandlingSop("SOP-LIS-AUTO-076", "AutoimmuneSerologySop Analytical Protocol #76", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-077", new LabHandlingSop("SOP-LIS-AUTO-077", "AutoimmuneSerologySop Analytical Protocol #77", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-078", new LabHandlingSop("SOP-LIS-AUTO-078", "AutoimmuneSerologySop Analytical Protocol #78", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-079", new LabHandlingSop("SOP-LIS-AUTO-079", "AutoimmuneSerologySop Analytical Protocol #79", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-080", new LabHandlingSop("SOP-LIS-AUTO-080", "AutoimmuneSerologySop Analytical Protocol #80", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-081", new LabHandlingSop("SOP-LIS-AUTO-081", "AutoimmuneSerologySop Analytical Protocol #81", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-082", new LabHandlingSop("SOP-LIS-AUTO-082", "AutoimmuneSerologySop Analytical Protocol #82", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-083", new LabHandlingSop("SOP-LIS-AUTO-083", "AutoimmuneSerologySop Analytical Protocol #83", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-084", new LabHandlingSop("SOP-LIS-AUTO-084", "AutoimmuneSerologySop Analytical Protocol #84", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-085", new LabHandlingSop("SOP-LIS-AUTO-085", "AutoimmuneSerologySop Analytical Protocol #85", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-086", new LabHandlingSop("SOP-LIS-AUTO-086", "AutoimmuneSerologySop Analytical Protocol #86", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-087", new LabHandlingSop("SOP-LIS-AUTO-087", "AutoimmuneSerologySop Analytical Protocol #87", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-088", new LabHandlingSop("SOP-LIS-AUTO-088", "AutoimmuneSerologySop Analytical Protocol #88", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-089", new LabHandlingSop("SOP-LIS-AUTO-089", "AutoimmuneSerologySop Analytical Protocol #89", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-090", new LabHandlingSop("SOP-LIS-AUTO-090", "AutoimmuneSerologySop Analytical Protocol #90", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-091", new LabHandlingSop("SOP-LIS-AUTO-091", "AutoimmuneSerologySop Analytical Protocol #91", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-092", new LabHandlingSop("SOP-LIS-AUTO-092", "AutoimmuneSerologySop Analytical Protocol #92", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-093", new LabHandlingSop("SOP-LIS-AUTO-093", "AutoimmuneSerologySop Analytical Protocol #93", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-094", new LabHandlingSop("SOP-LIS-AUTO-094", "AutoimmuneSerologySop Analytical Protocol #94", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-095", new LabHandlingSop("SOP-LIS-AUTO-095", "AutoimmuneSerologySop Analytical Protocol #95", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-096", new LabHandlingSop("SOP-LIS-AUTO-096", "AutoimmuneSerologySop Analytical Protocol #96", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-097", new LabHandlingSop("SOP-LIS-AUTO-097", "AutoimmuneSerologySop Analytical Protocol #97", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-098", new LabHandlingSop("SOP-LIS-AUTO-098", "AutoimmuneSerologySop Analytical Protocol #98", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-099", new LabHandlingSop("SOP-LIS-AUTO-099", "AutoimmuneSerologySop Analytical Protocol #99", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-100", new LabHandlingSop("SOP-LIS-AUTO-100", "AutoimmuneSerologySop Analytical Protocol #100", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-101", new LabHandlingSop("SOP-LIS-AUTO-101", "AutoimmuneSerologySop Analytical Protocol #101", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-102", new LabHandlingSop("SOP-LIS-AUTO-102", "AutoimmuneSerologySop Analytical Protocol #102", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-103", new LabHandlingSop("SOP-LIS-AUTO-103", "AutoimmuneSerologySop Analytical Protocol #103", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-104", new LabHandlingSop("SOP-LIS-AUTO-104", "AutoimmuneSerologySop Analytical Protocol #104", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-105", new LabHandlingSop("SOP-LIS-AUTO-105", "AutoimmuneSerologySop Analytical Protocol #105", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-106", new LabHandlingSop("SOP-LIS-AUTO-106", "AutoimmuneSerologySop Analytical Protocol #106", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-107", new LabHandlingSop("SOP-LIS-AUTO-107", "AutoimmuneSerologySop Analytical Protocol #107", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-108", new LabHandlingSop("SOP-LIS-AUTO-108", "AutoimmuneSerologySop Analytical Protocol #108", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-109", new LabHandlingSop("SOP-LIS-AUTO-109", "AutoimmuneSerologySop Analytical Protocol #109", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-110", new LabHandlingSop("SOP-LIS-AUTO-110", "AutoimmuneSerologySop Analytical Protocol #110", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-111", new LabHandlingSop("SOP-LIS-AUTO-111", "AutoimmuneSerologySop Analytical Protocol #111", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-112", new LabHandlingSop("SOP-LIS-AUTO-112", "AutoimmuneSerologySop Analytical Protocol #112", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-113", new LabHandlingSop("SOP-LIS-AUTO-113", "AutoimmuneSerologySop Analytical Protocol #113", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-114", new LabHandlingSop("SOP-LIS-AUTO-114", "AutoimmuneSerologySop Analytical Protocol #114", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-115", new LabHandlingSop("SOP-LIS-AUTO-115", "AutoimmuneSerologySop Analytical Protocol #115", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-116", new LabHandlingSop("SOP-LIS-AUTO-116", "AutoimmuneSerologySop Analytical Protocol #116", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-117", new LabHandlingSop("SOP-LIS-AUTO-117", "AutoimmuneSerologySop Analytical Protocol #117", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-118", new LabHandlingSop("SOP-LIS-AUTO-118", "AutoimmuneSerologySop Analytical Protocol #118", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-119", new LabHandlingSop("SOP-LIS-AUTO-119", "AutoimmuneSerologySop Analytical Protocol #119", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-120", new LabHandlingSop("SOP-LIS-AUTO-120", "AutoimmuneSerologySop Analytical Protocol #120", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-121", new LabHandlingSop("SOP-LIS-AUTO-121", "AutoimmuneSerologySop Analytical Protocol #121", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-122", new LabHandlingSop("SOP-LIS-AUTO-122", "AutoimmuneSerologySop Analytical Protocol #122", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-123", new LabHandlingSop("SOP-LIS-AUTO-123", "AutoimmuneSerologySop Analytical Protocol #123", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-124", new LabHandlingSop("SOP-LIS-AUTO-124", "AutoimmuneSerologySop Analytical Protocol #124", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-125", new LabHandlingSop("SOP-LIS-AUTO-125", "AutoimmuneSerologySop Analytical Protocol #125", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-126", new LabHandlingSop("SOP-LIS-AUTO-126", "AutoimmuneSerologySop Analytical Protocol #126", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-127", new LabHandlingSop("SOP-LIS-AUTO-127", "AutoimmuneSerologySop Analytical Protocol #127", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-128", new LabHandlingSop("SOP-LIS-AUTO-128", "AutoimmuneSerologySop Analytical Protocol #128", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-129", new LabHandlingSop("SOP-LIS-AUTO-129", "AutoimmuneSerologySop Analytical Protocol #129", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-130", new LabHandlingSop("SOP-LIS-AUTO-130", "AutoimmuneSerologySop Analytical Protocol #130", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-131", new LabHandlingSop("SOP-LIS-AUTO-131", "AutoimmuneSerologySop Analytical Protocol #131", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-132", new LabHandlingSop("SOP-LIS-AUTO-132", "AutoimmuneSerologySop Analytical Protocol #132", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-133", new LabHandlingSop("SOP-LIS-AUTO-133", "AutoimmuneSerologySop Analytical Protocol #133", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-134", new LabHandlingSop("SOP-LIS-AUTO-134", "AutoimmuneSerologySop Analytical Protocol #134", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-135", new LabHandlingSop("SOP-LIS-AUTO-135", "AutoimmuneSerologySop Analytical Protocol #135", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-136", new LabHandlingSop("SOP-LIS-AUTO-136", "AutoimmuneSerologySop Analytical Protocol #136", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-137", new LabHandlingSop("SOP-LIS-AUTO-137", "AutoimmuneSerologySop Analytical Protocol #137", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-138", new LabHandlingSop("SOP-LIS-AUTO-138", "AutoimmuneSerologySop Analytical Protocol #138", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-139", new LabHandlingSop("SOP-LIS-AUTO-139", "AutoimmuneSerologySop Analytical Protocol #139", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-AUTO-140", new LabHandlingSop("SOP-LIS-AUTO-140", "AutoimmuneSerologySop Analytical Protocol #140", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
    }

    public Optional<LabHandlingSop> findByCode(String code) {
        return Optional.ofNullable(sops.get(code));
    }

    public List<LabHandlingSop> getAllSops() {
        return new ArrayList<>(sops.values());
    }
}
