package com.hospital.ontology.lis;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;
import java.util.*;

@Component
public class ClinicalToxicologyScreeningSopCatalog {

    @Data
    @AllArgsConstructor
    public static class LabHandlingSop {
        private String sopCode;
        private String assayTitle;
        private String preAnalyticalStabilityProtocol;
        private String validatedAnalyzerPlatform;
        private String criticalActionGuideline;
    }

    private final Map<String, LabHandlingSop> sops = new LinkedHashMap<>();

    public ClinicalToxicologyScreeningSopCatalog() {
        initializeSops();
    }

    private void initializeSops() {
        sops.put("SOP-LIS-CLIN-001", new LabHandlingSop("SOP-LIS-CLIN-001", "ClinicalToxicologyScreeningSop Analytical Protocol #1", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-002", new LabHandlingSop("SOP-LIS-CLIN-002", "ClinicalToxicologyScreeningSop Analytical Protocol #2", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-003", new LabHandlingSop("SOP-LIS-CLIN-003", "ClinicalToxicologyScreeningSop Analytical Protocol #3", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-004", new LabHandlingSop("SOP-LIS-CLIN-004", "ClinicalToxicologyScreeningSop Analytical Protocol #4", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-005", new LabHandlingSop("SOP-LIS-CLIN-005", "ClinicalToxicologyScreeningSop Analytical Protocol #5", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-006", new LabHandlingSop("SOP-LIS-CLIN-006", "ClinicalToxicologyScreeningSop Analytical Protocol #6", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-007", new LabHandlingSop("SOP-LIS-CLIN-007", "ClinicalToxicologyScreeningSop Analytical Protocol #7", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-008", new LabHandlingSop("SOP-LIS-CLIN-008", "ClinicalToxicologyScreeningSop Analytical Protocol #8", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-009", new LabHandlingSop("SOP-LIS-CLIN-009", "ClinicalToxicologyScreeningSop Analytical Protocol #9", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-010", new LabHandlingSop("SOP-LIS-CLIN-010", "ClinicalToxicologyScreeningSop Analytical Protocol #10", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-011", new LabHandlingSop("SOP-LIS-CLIN-011", "ClinicalToxicologyScreeningSop Analytical Protocol #11", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-012", new LabHandlingSop("SOP-LIS-CLIN-012", "ClinicalToxicologyScreeningSop Analytical Protocol #12", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-013", new LabHandlingSop("SOP-LIS-CLIN-013", "ClinicalToxicologyScreeningSop Analytical Protocol #13", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-014", new LabHandlingSop("SOP-LIS-CLIN-014", "ClinicalToxicologyScreeningSop Analytical Protocol #14", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-015", new LabHandlingSop("SOP-LIS-CLIN-015", "ClinicalToxicologyScreeningSop Analytical Protocol #15", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-016", new LabHandlingSop("SOP-LIS-CLIN-016", "ClinicalToxicologyScreeningSop Analytical Protocol #16", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-017", new LabHandlingSop("SOP-LIS-CLIN-017", "ClinicalToxicologyScreeningSop Analytical Protocol #17", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-018", new LabHandlingSop("SOP-LIS-CLIN-018", "ClinicalToxicologyScreeningSop Analytical Protocol #18", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-019", new LabHandlingSop("SOP-LIS-CLIN-019", "ClinicalToxicologyScreeningSop Analytical Protocol #19", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-020", new LabHandlingSop("SOP-LIS-CLIN-020", "ClinicalToxicologyScreeningSop Analytical Protocol #20", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-021", new LabHandlingSop("SOP-LIS-CLIN-021", "ClinicalToxicologyScreeningSop Analytical Protocol #21", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-022", new LabHandlingSop("SOP-LIS-CLIN-022", "ClinicalToxicologyScreeningSop Analytical Protocol #22", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-023", new LabHandlingSop("SOP-LIS-CLIN-023", "ClinicalToxicologyScreeningSop Analytical Protocol #23", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-024", new LabHandlingSop("SOP-LIS-CLIN-024", "ClinicalToxicologyScreeningSop Analytical Protocol #24", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-025", new LabHandlingSop("SOP-LIS-CLIN-025", "ClinicalToxicologyScreeningSop Analytical Protocol #25", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-026", new LabHandlingSop("SOP-LIS-CLIN-026", "ClinicalToxicologyScreeningSop Analytical Protocol #26", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-027", new LabHandlingSop("SOP-LIS-CLIN-027", "ClinicalToxicologyScreeningSop Analytical Protocol #27", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-028", new LabHandlingSop("SOP-LIS-CLIN-028", "ClinicalToxicologyScreeningSop Analytical Protocol #28", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-029", new LabHandlingSop("SOP-LIS-CLIN-029", "ClinicalToxicologyScreeningSop Analytical Protocol #29", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-030", new LabHandlingSop("SOP-LIS-CLIN-030", "ClinicalToxicologyScreeningSop Analytical Protocol #30", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-031", new LabHandlingSop("SOP-LIS-CLIN-031", "ClinicalToxicologyScreeningSop Analytical Protocol #31", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-032", new LabHandlingSop("SOP-LIS-CLIN-032", "ClinicalToxicologyScreeningSop Analytical Protocol #32", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-033", new LabHandlingSop("SOP-LIS-CLIN-033", "ClinicalToxicologyScreeningSop Analytical Protocol #33", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-034", new LabHandlingSop("SOP-LIS-CLIN-034", "ClinicalToxicologyScreeningSop Analytical Protocol #34", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-035", new LabHandlingSop("SOP-LIS-CLIN-035", "ClinicalToxicologyScreeningSop Analytical Protocol #35", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-036", new LabHandlingSop("SOP-LIS-CLIN-036", "ClinicalToxicologyScreeningSop Analytical Protocol #36", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-037", new LabHandlingSop("SOP-LIS-CLIN-037", "ClinicalToxicologyScreeningSop Analytical Protocol #37", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-038", new LabHandlingSop("SOP-LIS-CLIN-038", "ClinicalToxicologyScreeningSop Analytical Protocol #38", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-039", new LabHandlingSop("SOP-LIS-CLIN-039", "ClinicalToxicologyScreeningSop Analytical Protocol #39", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-040", new LabHandlingSop("SOP-LIS-CLIN-040", "ClinicalToxicologyScreeningSop Analytical Protocol #40", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-041", new LabHandlingSop("SOP-LIS-CLIN-041", "ClinicalToxicologyScreeningSop Analytical Protocol #41", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-042", new LabHandlingSop("SOP-LIS-CLIN-042", "ClinicalToxicologyScreeningSop Analytical Protocol #42", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-043", new LabHandlingSop("SOP-LIS-CLIN-043", "ClinicalToxicologyScreeningSop Analytical Protocol #43", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-044", new LabHandlingSop("SOP-LIS-CLIN-044", "ClinicalToxicologyScreeningSop Analytical Protocol #44", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-045", new LabHandlingSop("SOP-LIS-CLIN-045", "ClinicalToxicologyScreeningSop Analytical Protocol #45", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-046", new LabHandlingSop("SOP-LIS-CLIN-046", "ClinicalToxicologyScreeningSop Analytical Protocol #46", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-047", new LabHandlingSop("SOP-LIS-CLIN-047", "ClinicalToxicologyScreeningSop Analytical Protocol #47", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-048", new LabHandlingSop("SOP-LIS-CLIN-048", "ClinicalToxicologyScreeningSop Analytical Protocol #48", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-049", new LabHandlingSop("SOP-LIS-CLIN-049", "ClinicalToxicologyScreeningSop Analytical Protocol #49", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-050", new LabHandlingSop("SOP-LIS-CLIN-050", "ClinicalToxicologyScreeningSop Analytical Protocol #50", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-051", new LabHandlingSop("SOP-LIS-CLIN-051", "ClinicalToxicologyScreeningSop Analytical Protocol #51", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-052", new LabHandlingSop("SOP-LIS-CLIN-052", "ClinicalToxicologyScreeningSop Analytical Protocol #52", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-053", new LabHandlingSop("SOP-LIS-CLIN-053", "ClinicalToxicologyScreeningSop Analytical Protocol #53", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-054", new LabHandlingSop("SOP-LIS-CLIN-054", "ClinicalToxicologyScreeningSop Analytical Protocol #54", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-055", new LabHandlingSop("SOP-LIS-CLIN-055", "ClinicalToxicologyScreeningSop Analytical Protocol #55", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-056", new LabHandlingSop("SOP-LIS-CLIN-056", "ClinicalToxicologyScreeningSop Analytical Protocol #56", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-057", new LabHandlingSop("SOP-LIS-CLIN-057", "ClinicalToxicologyScreeningSop Analytical Protocol #57", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-058", new LabHandlingSop("SOP-LIS-CLIN-058", "ClinicalToxicologyScreeningSop Analytical Protocol #58", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-059", new LabHandlingSop("SOP-LIS-CLIN-059", "ClinicalToxicologyScreeningSop Analytical Protocol #59", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-060", new LabHandlingSop("SOP-LIS-CLIN-060", "ClinicalToxicologyScreeningSop Analytical Protocol #60", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-061", new LabHandlingSop("SOP-LIS-CLIN-061", "ClinicalToxicologyScreeningSop Analytical Protocol #61", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-062", new LabHandlingSop("SOP-LIS-CLIN-062", "ClinicalToxicologyScreeningSop Analytical Protocol #62", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-063", new LabHandlingSop("SOP-LIS-CLIN-063", "ClinicalToxicologyScreeningSop Analytical Protocol #63", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-064", new LabHandlingSop("SOP-LIS-CLIN-064", "ClinicalToxicologyScreeningSop Analytical Protocol #64", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-065", new LabHandlingSop("SOP-LIS-CLIN-065", "ClinicalToxicologyScreeningSop Analytical Protocol #65", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-066", new LabHandlingSop("SOP-LIS-CLIN-066", "ClinicalToxicologyScreeningSop Analytical Protocol #66", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-067", new LabHandlingSop("SOP-LIS-CLIN-067", "ClinicalToxicologyScreeningSop Analytical Protocol #67", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-068", new LabHandlingSop("SOP-LIS-CLIN-068", "ClinicalToxicologyScreeningSop Analytical Protocol #68", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-069", new LabHandlingSop("SOP-LIS-CLIN-069", "ClinicalToxicologyScreeningSop Analytical Protocol #69", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-070", new LabHandlingSop("SOP-LIS-CLIN-070", "ClinicalToxicologyScreeningSop Analytical Protocol #70", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-071", new LabHandlingSop("SOP-LIS-CLIN-071", "ClinicalToxicologyScreeningSop Analytical Protocol #71", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-072", new LabHandlingSop("SOP-LIS-CLIN-072", "ClinicalToxicologyScreeningSop Analytical Protocol #72", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-073", new LabHandlingSop("SOP-LIS-CLIN-073", "ClinicalToxicologyScreeningSop Analytical Protocol #73", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-074", new LabHandlingSop("SOP-LIS-CLIN-074", "ClinicalToxicologyScreeningSop Analytical Protocol #74", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-075", new LabHandlingSop("SOP-LIS-CLIN-075", "ClinicalToxicologyScreeningSop Analytical Protocol #75", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-076", new LabHandlingSop("SOP-LIS-CLIN-076", "ClinicalToxicologyScreeningSop Analytical Protocol #76", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-077", new LabHandlingSop("SOP-LIS-CLIN-077", "ClinicalToxicologyScreeningSop Analytical Protocol #77", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-078", new LabHandlingSop("SOP-LIS-CLIN-078", "ClinicalToxicologyScreeningSop Analytical Protocol #78", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-079", new LabHandlingSop("SOP-LIS-CLIN-079", "ClinicalToxicologyScreeningSop Analytical Protocol #79", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-080", new LabHandlingSop("SOP-LIS-CLIN-080", "ClinicalToxicologyScreeningSop Analytical Protocol #80", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-081", new LabHandlingSop("SOP-LIS-CLIN-081", "ClinicalToxicologyScreeningSop Analytical Protocol #81", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-082", new LabHandlingSop("SOP-LIS-CLIN-082", "ClinicalToxicologyScreeningSop Analytical Protocol #82", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-083", new LabHandlingSop("SOP-LIS-CLIN-083", "ClinicalToxicologyScreeningSop Analytical Protocol #83", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-084", new LabHandlingSop("SOP-LIS-CLIN-084", "ClinicalToxicologyScreeningSop Analytical Protocol #84", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-085", new LabHandlingSop("SOP-LIS-CLIN-085", "ClinicalToxicologyScreeningSop Analytical Protocol #85", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-086", new LabHandlingSop("SOP-LIS-CLIN-086", "ClinicalToxicologyScreeningSop Analytical Protocol #86", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-087", new LabHandlingSop("SOP-LIS-CLIN-087", "ClinicalToxicologyScreeningSop Analytical Protocol #87", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-088", new LabHandlingSop("SOP-LIS-CLIN-088", "ClinicalToxicologyScreeningSop Analytical Protocol #88", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-089", new LabHandlingSop("SOP-LIS-CLIN-089", "ClinicalToxicologyScreeningSop Analytical Protocol #89", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-090", new LabHandlingSop("SOP-LIS-CLIN-090", "ClinicalToxicologyScreeningSop Analytical Protocol #90", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-091", new LabHandlingSop("SOP-LIS-CLIN-091", "ClinicalToxicologyScreeningSop Analytical Protocol #91", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-092", new LabHandlingSop("SOP-LIS-CLIN-092", "ClinicalToxicologyScreeningSop Analytical Protocol #92", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-093", new LabHandlingSop("SOP-LIS-CLIN-093", "ClinicalToxicologyScreeningSop Analytical Protocol #93", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-094", new LabHandlingSop("SOP-LIS-CLIN-094", "ClinicalToxicologyScreeningSop Analytical Protocol #94", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-095", new LabHandlingSop("SOP-LIS-CLIN-095", "ClinicalToxicologyScreeningSop Analytical Protocol #95", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-096", new LabHandlingSop("SOP-LIS-CLIN-096", "ClinicalToxicologyScreeningSop Analytical Protocol #96", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-097", new LabHandlingSop("SOP-LIS-CLIN-097", "ClinicalToxicologyScreeningSop Analytical Protocol #97", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-098", new LabHandlingSop("SOP-LIS-CLIN-098", "ClinicalToxicologyScreeningSop Analytical Protocol #98", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-099", new LabHandlingSop("SOP-LIS-CLIN-099", "ClinicalToxicologyScreeningSop Analytical Protocol #99", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-100", new LabHandlingSop("SOP-LIS-CLIN-100", "ClinicalToxicologyScreeningSop Analytical Protocol #100", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-101", new LabHandlingSop("SOP-LIS-CLIN-101", "ClinicalToxicologyScreeningSop Analytical Protocol #101", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-102", new LabHandlingSop("SOP-LIS-CLIN-102", "ClinicalToxicologyScreeningSop Analytical Protocol #102", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-103", new LabHandlingSop("SOP-LIS-CLIN-103", "ClinicalToxicologyScreeningSop Analytical Protocol #103", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-104", new LabHandlingSop("SOP-LIS-CLIN-104", "ClinicalToxicologyScreeningSop Analytical Protocol #104", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-105", new LabHandlingSop("SOP-LIS-CLIN-105", "ClinicalToxicologyScreeningSop Analytical Protocol #105", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-106", new LabHandlingSop("SOP-LIS-CLIN-106", "ClinicalToxicologyScreeningSop Analytical Protocol #106", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-107", new LabHandlingSop("SOP-LIS-CLIN-107", "ClinicalToxicologyScreeningSop Analytical Protocol #107", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-108", new LabHandlingSop("SOP-LIS-CLIN-108", "ClinicalToxicologyScreeningSop Analytical Protocol #108", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-109", new LabHandlingSop("SOP-LIS-CLIN-109", "ClinicalToxicologyScreeningSop Analytical Protocol #109", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-110", new LabHandlingSop("SOP-LIS-CLIN-110", "ClinicalToxicologyScreeningSop Analytical Protocol #110", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-111", new LabHandlingSop("SOP-LIS-CLIN-111", "ClinicalToxicologyScreeningSop Analytical Protocol #111", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-112", new LabHandlingSop("SOP-LIS-CLIN-112", "ClinicalToxicologyScreeningSop Analytical Protocol #112", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-113", new LabHandlingSop("SOP-LIS-CLIN-113", "ClinicalToxicologyScreeningSop Analytical Protocol #113", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-114", new LabHandlingSop("SOP-LIS-CLIN-114", "ClinicalToxicologyScreeningSop Analytical Protocol #114", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-115", new LabHandlingSop("SOP-LIS-CLIN-115", "ClinicalToxicologyScreeningSop Analytical Protocol #115", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-116", new LabHandlingSop("SOP-LIS-CLIN-116", "ClinicalToxicologyScreeningSop Analytical Protocol #116", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-117", new LabHandlingSop("SOP-LIS-CLIN-117", "ClinicalToxicologyScreeningSop Analytical Protocol #117", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-118", new LabHandlingSop("SOP-LIS-CLIN-118", "ClinicalToxicologyScreeningSop Analytical Protocol #118", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-119", new LabHandlingSop("SOP-LIS-CLIN-119", "ClinicalToxicologyScreeningSop Analytical Protocol #119", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-120", new LabHandlingSop("SOP-LIS-CLIN-120", "ClinicalToxicologyScreeningSop Analytical Protocol #120", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-121", new LabHandlingSop("SOP-LIS-CLIN-121", "ClinicalToxicologyScreeningSop Analytical Protocol #121", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-122", new LabHandlingSop("SOP-LIS-CLIN-122", "ClinicalToxicologyScreeningSop Analytical Protocol #122", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-123", new LabHandlingSop("SOP-LIS-CLIN-123", "ClinicalToxicologyScreeningSop Analytical Protocol #123", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-124", new LabHandlingSop("SOP-LIS-CLIN-124", "ClinicalToxicologyScreeningSop Analytical Protocol #124", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-125", new LabHandlingSop("SOP-LIS-CLIN-125", "ClinicalToxicologyScreeningSop Analytical Protocol #125", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-126", new LabHandlingSop("SOP-LIS-CLIN-126", "ClinicalToxicologyScreeningSop Analytical Protocol #126", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-127", new LabHandlingSop("SOP-LIS-CLIN-127", "ClinicalToxicologyScreeningSop Analytical Protocol #127", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-128", new LabHandlingSop("SOP-LIS-CLIN-128", "ClinicalToxicologyScreeningSop Analytical Protocol #128", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-129", new LabHandlingSop("SOP-LIS-CLIN-129", "ClinicalToxicologyScreeningSop Analytical Protocol #129", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-130", new LabHandlingSop("SOP-LIS-CLIN-130", "ClinicalToxicologyScreeningSop Analytical Protocol #130", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-131", new LabHandlingSop("SOP-LIS-CLIN-131", "ClinicalToxicologyScreeningSop Analytical Protocol #131", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-132", new LabHandlingSop("SOP-LIS-CLIN-132", "ClinicalToxicologyScreeningSop Analytical Protocol #132", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-133", new LabHandlingSop("SOP-LIS-CLIN-133", "ClinicalToxicologyScreeningSop Analytical Protocol #133", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-134", new LabHandlingSop("SOP-LIS-CLIN-134", "ClinicalToxicologyScreeningSop Analytical Protocol #134", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-135", new LabHandlingSop("SOP-LIS-CLIN-135", "ClinicalToxicologyScreeningSop Analytical Protocol #135", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-136", new LabHandlingSop("SOP-LIS-CLIN-136", "ClinicalToxicologyScreeningSop Analytical Protocol #136", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-137", new LabHandlingSop("SOP-LIS-CLIN-137", "ClinicalToxicologyScreeningSop Analytical Protocol #137", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-138", new LabHandlingSop("SOP-LIS-CLIN-138", "ClinicalToxicologyScreeningSop Analytical Protocol #138", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-139", new LabHandlingSop("SOP-LIS-CLIN-139", "ClinicalToxicologyScreeningSop Analytical Protocol #139", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-CLIN-140", new LabHandlingSop("SOP-LIS-CLIN-140", "ClinicalToxicologyScreeningSop Analytical Protocol #140", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
    }

    public Optional<LabHandlingSop> findByCode(String code) {
        return Optional.ofNullable(sops.get(code));
    }

    public List<LabHandlingSop> getAllSops() {
        return new ArrayList<>(sops.values());
    }
}
