package com.hospital.ontology.lis;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;
import java.util.*;

@Component
public class FlowCytometryLeukemiaSopCatalog {

    @Data
    @AllArgsConstructor
    public static class LabHandlingSop {
        private String sopCode;
        private String assayTitle;
        private String preAnalyticalStabilityProtocol;
        private String validatedAnalyzerPlatform;
        private String criticalActionGuideline;
    }

    private final Map<String, LabHandlingSop> sops = new LinkedHashMap<>();

    public FlowCytometryLeukemiaSopCatalog() {
        initializeSops();
    }

    private void initializeSops() {
        sops.put("SOP-LIS-FLOW-001", new LabHandlingSop("SOP-LIS-FLOW-001", "FlowCytometryLeukemiaSop Analytical Protocol #1", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-002", new LabHandlingSop("SOP-LIS-FLOW-002", "FlowCytometryLeukemiaSop Analytical Protocol #2", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-003", new LabHandlingSop("SOP-LIS-FLOW-003", "FlowCytometryLeukemiaSop Analytical Protocol #3", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-004", new LabHandlingSop("SOP-LIS-FLOW-004", "FlowCytometryLeukemiaSop Analytical Protocol #4", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-005", new LabHandlingSop("SOP-LIS-FLOW-005", "FlowCytometryLeukemiaSop Analytical Protocol #5", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-006", new LabHandlingSop("SOP-LIS-FLOW-006", "FlowCytometryLeukemiaSop Analytical Protocol #6", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-007", new LabHandlingSop("SOP-LIS-FLOW-007", "FlowCytometryLeukemiaSop Analytical Protocol #7", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-008", new LabHandlingSop("SOP-LIS-FLOW-008", "FlowCytometryLeukemiaSop Analytical Protocol #8", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-009", new LabHandlingSop("SOP-LIS-FLOW-009", "FlowCytometryLeukemiaSop Analytical Protocol #9", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-010", new LabHandlingSop("SOP-LIS-FLOW-010", "FlowCytometryLeukemiaSop Analytical Protocol #10", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-011", new LabHandlingSop("SOP-LIS-FLOW-011", "FlowCytometryLeukemiaSop Analytical Protocol #11", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-012", new LabHandlingSop("SOP-LIS-FLOW-012", "FlowCytometryLeukemiaSop Analytical Protocol #12", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-013", new LabHandlingSop("SOP-LIS-FLOW-013", "FlowCytometryLeukemiaSop Analytical Protocol #13", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-014", new LabHandlingSop("SOP-LIS-FLOW-014", "FlowCytometryLeukemiaSop Analytical Protocol #14", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-015", new LabHandlingSop("SOP-LIS-FLOW-015", "FlowCytometryLeukemiaSop Analytical Protocol #15", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-016", new LabHandlingSop("SOP-LIS-FLOW-016", "FlowCytometryLeukemiaSop Analytical Protocol #16", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-017", new LabHandlingSop("SOP-LIS-FLOW-017", "FlowCytometryLeukemiaSop Analytical Protocol #17", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-018", new LabHandlingSop("SOP-LIS-FLOW-018", "FlowCytometryLeukemiaSop Analytical Protocol #18", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-019", new LabHandlingSop("SOP-LIS-FLOW-019", "FlowCytometryLeukemiaSop Analytical Protocol #19", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-020", new LabHandlingSop("SOP-LIS-FLOW-020", "FlowCytometryLeukemiaSop Analytical Protocol #20", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-021", new LabHandlingSop("SOP-LIS-FLOW-021", "FlowCytometryLeukemiaSop Analytical Protocol #21", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-022", new LabHandlingSop("SOP-LIS-FLOW-022", "FlowCytometryLeukemiaSop Analytical Protocol #22", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-023", new LabHandlingSop("SOP-LIS-FLOW-023", "FlowCytometryLeukemiaSop Analytical Protocol #23", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-024", new LabHandlingSop("SOP-LIS-FLOW-024", "FlowCytometryLeukemiaSop Analytical Protocol #24", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-025", new LabHandlingSop("SOP-LIS-FLOW-025", "FlowCytometryLeukemiaSop Analytical Protocol #25", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-026", new LabHandlingSop("SOP-LIS-FLOW-026", "FlowCytometryLeukemiaSop Analytical Protocol #26", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-027", new LabHandlingSop("SOP-LIS-FLOW-027", "FlowCytometryLeukemiaSop Analytical Protocol #27", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-028", new LabHandlingSop("SOP-LIS-FLOW-028", "FlowCytometryLeukemiaSop Analytical Protocol #28", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-029", new LabHandlingSop("SOP-LIS-FLOW-029", "FlowCytometryLeukemiaSop Analytical Protocol #29", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-030", new LabHandlingSop("SOP-LIS-FLOW-030", "FlowCytometryLeukemiaSop Analytical Protocol #30", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-031", new LabHandlingSop("SOP-LIS-FLOW-031", "FlowCytometryLeukemiaSop Analytical Protocol #31", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-032", new LabHandlingSop("SOP-LIS-FLOW-032", "FlowCytometryLeukemiaSop Analytical Protocol #32", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-033", new LabHandlingSop("SOP-LIS-FLOW-033", "FlowCytometryLeukemiaSop Analytical Protocol #33", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-034", new LabHandlingSop("SOP-LIS-FLOW-034", "FlowCytometryLeukemiaSop Analytical Protocol #34", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-035", new LabHandlingSop("SOP-LIS-FLOW-035", "FlowCytometryLeukemiaSop Analytical Protocol #35", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-036", new LabHandlingSop("SOP-LIS-FLOW-036", "FlowCytometryLeukemiaSop Analytical Protocol #36", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-037", new LabHandlingSop("SOP-LIS-FLOW-037", "FlowCytometryLeukemiaSop Analytical Protocol #37", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-038", new LabHandlingSop("SOP-LIS-FLOW-038", "FlowCytometryLeukemiaSop Analytical Protocol #38", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-039", new LabHandlingSop("SOP-LIS-FLOW-039", "FlowCytometryLeukemiaSop Analytical Protocol #39", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-040", new LabHandlingSop("SOP-LIS-FLOW-040", "FlowCytometryLeukemiaSop Analytical Protocol #40", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-041", new LabHandlingSop("SOP-LIS-FLOW-041", "FlowCytometryLeukemiaSop Analytical Protocol #41", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-042", new LabHandlingSop("SOP-LIS-FLOW-042", "FlowCytometryLeukemiaSop Analytical Protocol #42", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-043", new LabHandlingSop("SOP-LIS-FLOW-043", "FlowCytometryLeukemiaSop Analytical Protocol #43", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-044", new LabHandlingSop("SOP-LIS-FLOW-044", "FlowCytometryLeukemiaSop Analytical Protocol #44", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-045", new LabHandlingSop("SOP-LIS-FLOW-045", "FlowCytometryLeukemiaSop Analytical Protocol #45", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-046", new LabHandlingSop("SOP-LIS-FLOW-046", "FlowCytometryLeukemiaSop Analytical Protocol #46", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-047", new LabHandlingSop("SOP-LIS-FLOW-047", "FlowCytometryLeukemiaSop Analytical Protocol #47", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-048", new LabHandlingSop("SOP-LIS-FLOW-048", "FlowCytometryLeukemiaSop Analytical Protocol #48", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-049", new LabHandlingSop("SOP-LIS-FLOW-049", "FlowCytometryLeukemiaSop Analytical Protocol #49", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-050", new LabHandlingSop("SOP-LIS-FLOW-050", "FlowCytometryLeukemiaSop Analytical Protocol #50", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-051", new LabHandlingSop("SOP-LIS-FLOW-051", "FlowCytometryLeukemiaSop Analytical Protocol #51", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-052", new LabHandlingSop("SOP-LIS-FLOW-052", "FlowCytometryLeukemiaSop Analytical Protocol #52", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-053", new LabHandlingSop("SOP-LIS-FLOW-053", "FlowCytometryLeukemiaSop Analytical Protocol #53", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-054", new LabHandlingSop("SOP-LIS-FLOW-054", "FlowCytometryLeukemiaSop Analytical Protocol #54", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-055", new LabHandlingSop("SOP-LIS-FLOW-055", "FlowCytometryLeukemiaSop Analytical Protocol #55", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-056", new LabHandlingSop("SOP-LIS-FLOW-056", "FlowCytometryLeukemiaSop Analytical Protocol #56", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-057", new LabHandlingSop("SOP-LIS-FLOW-057", "FlowCytometryLeukemiaSop Analytical Protocol #57", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-058", new LabHandlingSop("SOP-LIS-FLOW-058", "FlowCytometryLeukemiaSop Analytical Protocol #58", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-059", new LabHandlingSop("SOP-LIS-FLOW-059", "FlowCytometryLeukemiaSop Analytical Protocol #59", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-060", new LabHandlingSop("SOP-LIS-FLOW-060", "FlowCytometryLeukemiaSop Analytical Protocol #60", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-061", new LabHandlingSop("SOP-LIS-FLOW-061", "FlowCytometryLeukemiaSop Analytical Protocol #61", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-062", new LabHandlingSop("SOP-LIS-FLOW-062", "FlowCytometryLeukemiaSop Analytical Protocol #62", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-063", new LabHandlingSop("SOP-LIS-FLOW-063", "FlowCytometryLeukemiaSop Analytical Protocol #63", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-064", new LabHandlingSop("SOP-LIS-FLOW-064", "FlowCytometryLeukemiaSop Analytical Protocol #64", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-065", new LabHandlingSop("SOP-LIS-FLOW-065", "FlowCytometryLeukemiaSop Analytical Protocol #65", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-066", new LabHandlingSop("SOP-LIS-FLOW-066", "FlowCytometryLeukemiaSop Analytical Protocol #66", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-067", new LabHandlingSop("SOP-LIS-FLOW-067", "FlowCytometryLeukemiaSop Analytical Protocol #67", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-068", new LabHandlingSop("SOP-LIS-FLOW-068", "FlowCytometryLeukemiaSop Analytical Protocol #68", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-069", new LabHandlingSop("SOP-LIS-FLOW-069", "FlowCytometryLeukemiaSop Analytical Protocol #69", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-070", new LabHandlingSop("SOP-LIS-FLOW-070", "FlowCytometryLeukemiaSop Analytical Protocol #70", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-071", new LabHandlingSop("SOP-LIS-FLOW-071", "FlowCytometryLeukemiaSop Analytical Protocol #71", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-072", new LabHandlingSop("SOP-LIS-FLOW-072", "FlowCytometryLeukemiaSop Analytical Protocol #72", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-073", new LabHandlingSop("SOP-LIS-FLOW-073", "FlowCytometryLeukemiaSop Analytical Protocol #73", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-074", new LabHandlingSop("SOP-LIS-FLOW-074", "FlowCytometryLeukemiaSop Analytical Protocol #74", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-075", new LabHandlingSop("SOP-LIS-FLOW-075", "FlowCytometryLeukemiaSop Analytical Protocol #75", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-076", new LabHandlingSop("SOP-LIS-FLOW-076", "FlowCytometryLeukemiaSop Analytical Protocol #76", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-077", new LabHandlingSop("SOP-LIS-FLOW-077", "FlowCytometryLeukemiaSop Analytical Protocol #77", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-078", new LabHandlingSop("SOP-LIS-FLOW-078", "FlowCytometryLeukemiaSop Analytical Protocol #78", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-079", new LabHandlingSop("SOP-LIS-FLOW-079", "FlowCytometryLeukemiaSop Analytical Protocol #79", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-080", new LabHandlingSop("SOP-LIS-FLOW-080", "FlowCytometryLeukemiaSop Analytical Protocol #80", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-081", new LabHandlingSop("SOP-LIS-FLOW-081", "FlowCytometryLeukemiaSop Analytical Protocol #81", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-082", new LabHandlingSop("SOP-LIS-FLOW-082", "FlowCytometryLeukemiaSop Analytical Protocol #82", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-083", new LabHandlingSop("SOP-LIS-FLOW-083", "FlowCytometryLeukemiaSop Analytical Protocol #83", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-084", new LabHandlingSop("SOP-LIS-FLOW-084", "FlowCytometryLeukemiaSop Analytical Protocol #84", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-085", new LabHandlingSop("SOP-LIS-FLOW-085", "FlowCytometryLeukemiaSop Analytical Protocol #85", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-086", new LabHandlingSop("SOP-LIS-FLOW-086", "FlowCytometryLeukemiaSop Analytical Protocol #86", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-087", new LabHandlingSop("SOP-LIS-FLOW-087", "FlowCytometryLeukemiaSop Analytical Protocol #87", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-088", new LabHandlingSop("SOP-LIS-FLOW-088", "FlowCytometryLeukemiaSop Analytical Protocol #88", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-089", new LabHandlingSop("SOP-LIS-FLOW-089", "FlowCytometryLeukemiaSop Analytical Protocol #89", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-090", new LabHandlingSop("SOP-LIS-FLOW-090", "FlowCytometryLeukemiaSop Analytical Protocol #90", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-091", new LabHandlingSop("SOP-LIS-FLOW-091", "FlowCytometryLeukemiaSop Analytical Protocol #91", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-092", new LabHandlingSop("SOP-LIS-FLOW-092", "FlowCytometryLeukemiaSop Analytical Protocol #92", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-093", new LabHandlingSop("SOP-LIS-FLOW-093", "FlowCytometryLeukemiaSop Analytical Protocol #93", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-094", new LabHandlingSop("SOP-LIS-FLOW-094", "FlowCytometryLeukemiaSop Analytical Protocol #94", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-095", new LabHandlingSop("SOP-LIS-FLOW-095", "FlowCytometryLeukemiaSop Analytical Protocol #95", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-096", new LabHandlingSop("SOP-LIS-FLOW-096", "FlowCytometryLeukemiaSop Analytical Protocol #96", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-097", new LabHandlingSop("SOP-LIS-FLOW-097", "FlowCytometryLeukemiaSop Analytical Protocol #97", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-098", new LabHandlingSop("SOP-LIS-FLOW-098", "FlowCytometryLeukemiaSop Analytical Protocol #98", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-099", new LabHandlingSop("SOP-LIS-FLOW-099", "FlowCytometryLeukemiaSop Analytical Protocol #99", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-100", new LabHandlingSop("SOP-LIS-FLOW-100", "FlowCytometryLeukemiaSop Analytical Protocol #100", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-101", new LabHandlingSop("SOP-LIS-FLOW-101", "FlowCytometryLeukemiaSop Analytical Protocol #101", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-102", new LabHandlingSop("SOP-LIS-FLOW-102", "FlowCytometryLeukemiaSop Analytical Protocol #102", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-103", new LabHandlingSop("SOP-LIS-FLOW-103", "FlowCytometryLeukemiaSop Analytical Protocol #103", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-104", new LabHandlingSop("SOP-LIS-FLOW-104", "FlowCytometryLeukemiaSop Analytical Protocol #104", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-105", new LabHandlingSop("SOP-LIS-FLOW-105", "FlowCytometryLeukemiaSop Analytical Protocol #105", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-106", new LabHandlingSop("SOP-LIS-FLOW-106", "FlowCytometryLeukemiaSop Analytical Protocol #106", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-107", new LabHandlingSop("SOP-LIS-FLOW-107", "FlowCytometryLeukemiaSop Analytical Protocol #107", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-108", new LabHandlingSop("SOP-LIS-FLOW-108", "FlowCytometryLeukemiaSop Analytical Protocol #108", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-109", new LabHandlingSop("SOP-LIS-FLOW-109", "FlowCytometryLeukemiaSop Analytical Protocol #109", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-110", new LabHandlingSop("SOP-LIS-FLOW-110", "FlowCytometryLeukemiaSop Analytical Protocol #110", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-111", new LabHandlingSop("SOP-LIS-FLOW-111", "FlowCytometryLeukemiaSop Analytical Protocol #111", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-112", new LabHandlingSop("SOP-LIS-FLOW-112", "FlowCytometryLeukemiaSop Analytical Protocol #112", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-113", new LabHandlingSop("SOP-LIS-FLOW-113", "FlowCytometryLeukemiaSop Analytical Protocol #113", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-114", new LabHandlingSop("SOP-LIS-FLOW-114", "FlowCytometryLeukemiaSop Analytical Protocol #114", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-115", new LabHandlingSop("SOP-LIS-FLOW-115", "FlowCytometryLeukemiaSop Analytical Protocol #115", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-116", new LabHandlingSop("SOP-LIS-FLOW-116", "FlowCytometryLeukemiaSop Analytical Protocol #116", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-117", new LabHandlingSop("SOP-LIS-FLOW-117", "FlowCytometryLeukemiaSop Analytical Protocol #117", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-118", new LabHandlingSop("SOP-LIS-FLOW-118", "FlowCytometryLeukemiaSop Analytical Protocol #118", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-119", new LabHandlingSop("SOP-LIS-FLOW-119", "FlowCytometryLeukemiaSop Analytical Protocol #119", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-120", new LabHandlingSop("SOP-LIS-FLOW-120", "FlowCytometryLeukemiaSop Analytical Protocol #120", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-121", new LabHandlingSop("SOP-LIS-FLOW-121", "FlowCytometryLeukemiaSop Analytical Protocol #121", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-122", new LabHandlingSop("SOP-LIS-FLOW-122", "FlowCytometryLeukemiaSop Analytical Protocol #122", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-123", new LabHandlingSop("SOP-LIS-FLOW-123", "FlowCytometryLeukemiaSop Analytical Protocol #123", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-124", new LabHandlingSop("SOP-LIS-FLOW-124", "FlowCytometryLeukemiaSop Analytical Protocol #124", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-125", new LabHandlingSop("SOP-LIS-FLOW-125", "FlowCytometryLeukemiaSop Analytical Protocol #125", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-126", new LabHandlingSop("SOP-LIS-FLOW-126", "FlowCytometryLeukemiaSop Analytical Protocol #126", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-127", new LabHandlingSop("SOP-LIS-FLOW-127", "FlowCytometryLeukemiaSop Analytical Protocol #127", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-128", new LabHandlingSop("SOP-LIS-FLOW-128", "FlowCytometryLeukemiaSop Analytical Protocol #128", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-129", new LabHandlingSop("SOP-LIS-FLOW-129", "FlowCytometryLeukemiaSop Analytical Protocol #129", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-130", new LabHandlingSop("SOP-LIS-FLOW-130", "FlowCytometryLeukemiaSop Analytical Protocol #130", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-131", new LabHandlingSop("SOP-LIS-FLOW-131", "FlowCytometryLeukemiaSop Analytical Protocol #131", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-132", new LabHandlingSop("SOP-LIS-FLOW-132", "FlowCytometryLeukemiaSop Analytical Protocol #132", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-133", new LabHandlingSop("SOP-LIS-FLOW-133", "FlowCytometryLeukemiaSop Analytical Protocol #133", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-134", new LabHandlingSop("SOP-LIS-FLOW-134", "FlowCytometryLeukemiaSop Analytical Protocol #134", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-135", new LabHandlingSop("SOP-LIS-FLOW-135", "FlowCytometryLeukemiaSop Analytical Protocol #135", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-136", new LabHandlingSop("SOP-LIS-FLOW-136", "FlowCytometryLeukemiaSop Analytical Protocol #136", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-137", new LabHandlingSop("SOP-LIS-FLOW-137", "FlowCytometryLeukemiaSop Analytical Protocol #137", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-138", new LabHandlingSop("SOP-LIS-FLOW-138", "FlowCytometryLeukemiaSop Analytical Protocol #138", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-139", new LabHandlingSop("SOP-LIS-FLOW-139", "FlowCytometryLeukemiaSop Analytical Protocol #139", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-FLOW-140", new LabHandlingSop("SOP-LIS-FLOW-140", "FlowCytometryLeukemiaSop Analytical Protocol #140", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
    }

    public Optional<LabHandlingSop> findByCode(String code) {
        return Optional.ofNullable(sops.get(code));
    }

    public List<LabHandlingSop> getAllSops() {
        return new ArrayList<>(sops.values());
    }
}
