package com.hospital.ontology.lis;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;
import java.util.*;

@Component
public class HemostasisAndThrombosisSopCatalog {

    @Data
    @AllArgsConstructor
    public static class LabHandlingSop {
        private String sopCode;
        private String assayTitle;
        private String preAnalyticalStabilityProtocol;
        private String validatedAnalyzerPlatform;
        private String criticalActionGuideline;
    }

    private final Map<String, LabHandlingSop> sops = new LinkedHashMap<>();

    public HemostasisAndThrombosisSopCatalog() {
        initializeSops();
    }

    private void initializeSops() {
        sops.put("SOP-LIS-HEMO-001", new LabHandlingSop("SOP-LIS-HEMO-001", "HemostasisAndThrombosisSop Analytical Protocol #1", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-002", new LabHandlingSop("SOP-LIS-HEMO-002", "HemostasisAndThrombosisSop Analytical Protocol #2", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-003", new LabHandlingSop("SOP-LIS-HEMO-003", "HemostasisAndThrombosisSop Analytical Protocol #3", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-004", new LabHandlingSop("SOP-LIS-HEMO-004", "HemostasisAndThrombosisSop Analytical Protocol #4", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-005", new LabHandlingSop("SOP-LIS-HEMO-005", "HemostasisAndThrombosisSop Analytical Protocol #5", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-006", new LabHandlingSop("SOP-LIS-HEMO-006", "HemostasisAndThrombosisSop Analytical Protocol #6", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-007", new LabHandlingSop("SOP-LIS-HEMO-007", "HemostasisAndThrombosisSop Analytical Protocol #7", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-008", new LabHandlingSop("SOP-LIS-HEMO-008", "HemostasisAndThrombosisSop Analytical Protocol #8", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-009", new LabHandlingSop("SOP-LIS-HEMO-009", "HemostasisAndThrombosisSop Analytical Protocol #9", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-010", new LabHandlingSop("SOP-LIS-HEMO-010", "HemostasisAndThrombosisSop Analytical Protocol #10", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-011", new LabHandlingSop("SOP-LIS-HEMO-011", "HemostasisAndThrombosisSop Analytical Protocol #11", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-012", new LabHandlingSop("SOP-LIS-HEMO-012", "HemostasisAndThrombosisSop Analytical Protocol #12", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-013", new LabHandlingSop("SOP-LIS-HEMO-013", "HemostasisAndThrombosisSop Analytical Protocol #13", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-014", new LabHandlingSop("SOP-LIS-HEMO-014", "HemostasisAndThrombosisSop Analytical Protocol #14", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-015", new LabHandlingSop("SOP-LIS-HEMO-015", "HemostasisAndThrombosisSop Analytical Protocol #15", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-016", new LabHandlingSop("SOP-LIS-HEMO-016", "HemostasisAndThrombosisSop Analytical Protocol #16", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-017", new LabHandlingSop("SOP-LIS-HEMO-017", "HemostasisAndThrombosisSop Analytical Protocol #17", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-018", new LabHandlingSop("SOP-LIS-HEMO-018", "HemostasisAndThrombosisSop Analytical Protocol #18", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-019", new LabHandlingSop("SOP-LIS-HEMO-019", "HemostasisAndThrombosisSop Analytical Protocol #19", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-020", new LabHandlingSop("SOP-LIS-HEMO-020", "HemostasisAndThrombosisSop Analytical Protocol #20", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-021", new LabHandlingSop("SOP-LIS-HEMO-021", "HemostasisAndThrombosisSop Analytical Protocol #21", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-022", new LabHandlingSop("SOP-LIS-HEMO-022", "HemostasisAndThrombosisSop Analytical Protocol #22", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-023", new LabHandlingSop("SOP-LIS-HEMO-023", "HemostasisAndThrombosisSop Analytical Protocol #23", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-024", new LabHandlingSop("SOP-LIS-HEMO-024", "HemostasisAndThrombosisSop Analytical Protocol #24", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-025", new LabHandlingSop("SOP-LIS-HEMO-025", "HemostasisAndThrombosisSop Analytical Protocol #25", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-026", new LabHandlingSop("SOP-LIS-HEMO-026", "HemostasisAndThrombosisSop Analytical Protocol #26", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-027", new LabHandlingSop("SOP-LIS-HEMO-027", "HemostasisAndThrombosisSop Analytical Protocol #27", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-028", new LabHandlingSop("SOP-LIS-HEMO-028", "HemostasisAndThrombosisSop Analytical Protocol #28", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-029", new LabHandlingSop("SOP-LIS-HEMO-029", "HemostasisAndThrombosisSop Analytical Protocol #29", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-030", new LabHandlingSop("SOP-LIS-HEMO-030", "HemostasisAndThrombosisSop Analytical Protocol #30", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-031", new LabHandlingSop("SOP-LIS-HEMO-031", "HemostasisAndThrombosisSop Analytical Protocol #31", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-032", new LabHandlingSop("SOP-LIS-HEMO-032", "HemostasisAndThrombosisSop Analytical Protocol #32", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-033", new LabHandlingSop("SOP-LIS-HEMO-033", "HemostasisAndThrombosisSop Analytical Protocol #33", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-034", new LabHandlingSop("SOP-LIS-HEMO-034", "HemostasisAndThrombosisSop Analytical Protocol #34", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-035", new LabHandlingSop("SOP-LIS-HEMO-035", "HemostasisAndThrombosisSop Analytical Protocol #35", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-036", new LabHandlingSop("SOP-LIS-HEMO-036", "HemostasisAndThrombosisSop Analytical Protocol #36", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-037", new LabHandlingSop("SOP-LIS-HEMO-037", "HemostasisAndThrombosisSop Analytical Protocol #37", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-038", new LabHandlingSop("SOP-LIS-HEMO-038", "HemostasisAndThrombosisSop Analytical Protocol #38", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-039", new LabHandlingSop("SOP-LIS-HEMO-039", "HemostasisAndThrombosisSop Analytical Protocol #39", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-040", new LabHandlingSop("SOP-LIS-HEMO-040", "HemostasisAndThrombosisSop Analytical Protocol #40", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-041", new LabHandlingSop("SOP-LIS-HEMO-041", "HemostasisAndThrombosisSop Analytical Protocol #41", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-042", new LabHandlingSop("SOP-LIS-HEMO-042", "HemostasisAndThrombosisSop Analytical Protocol #42", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-043", new LabHandlingSop("SOP-LIS-HEMO-043", "HemostasisAndThrombosisSop Analytical Protocol #43", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-044", new LabHandlingSop("SOP-LIS-HEMO-044", "HemostasisAndThrombosisSop Analytical Protocol #44", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-045", new LabHandlingSop("SOP-LIS-HEMO-045", "HemostasisAndThrombosisSop Analytical Protocol #45", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-046", new LabHandlingSop("SOP-LIS-HEMO-046", "HemostasisAndThrombosisSop Analytical Protocol #46", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-047", new LabHandlingSop("SOP-LIS-HEMO-047", "HemostasisAndThrombosisSop Analytical Protocol #47", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-048", new LabHandlingSop("SOP-LIS-HEMO-048", "HemostasisAndThrombosisSop Analytical Protocol #48", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-049", new LabHandlingSop("SOP-LIS-HEMO-049", "HemostasisAndThrombosisSop Analytical Protocol #49", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-050", new LabHandlingSop("SOP-LIS-HEMO-050", "HemostasisAndThrombosisSop Analytical Protocol #50", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-051", new LabHandlingSop("SOP-LIS-HEMO-051", "HemostasisAndThrombosisSop Analytical Protocol #51", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-052", new LabHandlingSop("SOP-LIS-HEMO-052", "HemostasisAndThrombosisSop Analytical Protocol #52", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-053", new LabHandlingSop("SOP-LIS-HEMO-053", "HemostasisAndThrombosisSop Analytical Protocol #53", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-054", new LabHandlingSop("SOP-LIS-HEMO-054", "HemostasisAndThrombosisSop Analytical Protocol #54", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-055", new LabHandlingSop("SOP-LIS-HEMO-055", "HemostasisAndThrombosisSop Analytical Protocol #55", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-056", new LabHandlingSop("SOP-LIS-HEMO-056", "HemostasisAndThrombosisSop Analytical Protocol #56", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-057", new LabHandlingSop("SOP-LIS-HEMO-057", "HemostasisAndThrombosisSop Analytical Protocol #57", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-058", new LabHandlingSop("SOP-LIS-HEMO-058", "HemostasisAndThrombosisSop Analytical Protocol #58", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-059", new LabHandlingSop("SOP-LIS-HEMO-059", "HemostasisAndThrombosisSop Analytical Protocol #59", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-060", new LabHandlingSop("SOP-LIS-HEMO-060", "HemostasisAndThrombosisSop Analytical Protocol #60", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-061", new LabHandlingSop("SOP-LIS-HEMO-061", "HemostasisAndThrombosisSop Analytical Protocol #61", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-062", new LabHandlingSop("SOP-LIS-HEMO-062", "HemostasisAndThrombosisSop Analytical Protocol #62", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-063", new LabHandlingSop("SOP-LIS-HEMO-063", "HemostasisAndThrombosisSop Analytical Protocol #63", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-064", new LabHandlingSop("SOP-LIS-HEMO-064", "HemostasisAndThrombosisSop Analytical Protocol #64", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-065", new LabHandlingSop("SOP-LIS-HEMO-065", "HemostasisAndThrombosisSop Analytical Protocol #65", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-066", new LabHandlingSop("SOP-LIS-HEMO-066", "HemostasisAndThrombosisSop Analytical Protocol #66", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-067", new LabHandlingSop("SOP-LIS-HEMO-067", "HemostasisAndThrombosisSop Analytical Protocol #67", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-068", new LabHandlingSop("SOP-LIS-HEMO-068", "HemostasisAndThrombosisSop Analytical Protocol #68", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-069", new LabHandlingSop("SOP-LIS-HEMO-069", "HemostasisAndThrombosisSop Analytical Protocol #69", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-070", new LabHandlingSop("SOP-LIS-HEMO-070", "HemostasisAndThrombosisSop Analytical Protocol #70", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-071", new LabHandlingSop("SOP-LIS-HEMO-071", "HemostasisAndThrombosisSop Analytical Protocol #71", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-072", new LabHandlingSop("SOP-LIS-HEMO-072", "HemostasisAndThrombosisSop Analytical Protocol #72", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-073", new LabHandlingSop("SOP-LIS-HEMO-073", "HemostasisAndThrombosisSop Analytical Protocol #73", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-074", new LabHandlingSop("SOP-LIS-HEMO-074", "HemostasisAndThrombosisSop Analytical Protocol #74", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-075", new LabHandlingSop("SOP-LIS-HEMO-075", "HemostasisAndThrombosisSop Analytical Protocol #75", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-076", new LabHandlingSop("SOP-LIS-HEMO-076", "HemostasisAndThrombosisSop Analytical Protocol #76", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-077", new LabHandlingSop("SOP-LIS-HEMO-077", "HemostasisAndThrombosisSop Analytical Protocol #77", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-078", new LabHandlingSop("SOP-LIS-HEMO-078", "HemostasisAndThrombosisSop Analytical Protocol #78", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-079", new LabHandlingSop("SOP-LIS-HEMO-079", "HemostasisAndThrombosisSop Analytical Protocol #79", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-080", new LabHandlingSop("SOP-LIS-HEMO-080", "HemostasisAndThrombosisSop Analytical Protocol #80", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-081", new LabHandlingSop("SOP-LIS-HEMO-081", "HemostasisAndThrombosisSop Analytical Protocol #81", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-082", new LabHandlingSop("SOP-LIS-HEMO-082", "HemostasisAndThrombosisSop Analytical Protocol #82", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-083", new LabHandlingSop("SOP-LIS-HEMO-083", "HemostasisAndThrombosisSop Analytical Protocol #83", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-084", new LabHandlingSop("SOP-LIS-HEMO-084", "HemostasisAndThrombosisSop Analytical Protocol #84", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-085", new LabHandlingSop("SOP-LIS-HEMO-085", "HemostasisAndThrombosisSop Analytical Protocol #85", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-086", new LabHandlingSop("SOP-LIS-HEMO-086", "HemostasisAndThrombosisSop Analytical Protocol #86", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-087", new LabHandlingSop("SOP-LIS-HEMO-087", "HemostasisAndThrombosisSop Analytical Protocol #87", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-088", new LabHandlingSop("SOP-LIS-HEMO-088", "HemostasisAndThrombosisSop Analytical Protocol #88", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-089", new LabHandlingSop("SOP-LIS-HEMO-089", "HemostasisAndThrombosisSop Analytical Protocol #89", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-090", new LabHandlingSop("SOP-LIS-HEMO-090", "HemostasisAndThrombosisSop Analytical Protocol #90", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-091", new LabHandlingSop("SOP-LIS-HEMO-091", "HemostasisAndThrombosisSop Analytical Protocol #91", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-092", new LabHandlingSop("SOP-LIS-HEMO-092", "HemostasisAndThrombosisSop Analytical Protocol #92", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-093", new LabHandlingSop("SOP-LIS-HEMO-093", "HemostasisAndThrombosisSop Analytical Protocol #93", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-094", new LabHandlingSop("SOP-LIS-HEMO-094", "HemostasisAndThrombosisSop Analytical Protocol #94", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-095", new LabHandlingSop("SOP-LIS-HEMO-095", "HemostasisAndThrombosisSop Analytical Protocol #95", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-096", new LabHandlingSop("SOP-LIS-HEMO-096", "HemostasisAndThrombosisSop Analytical Protocol #96", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-097", new LabHandlingSop("SOP-LIS-HEMO-097", "HemostasisAndThrombosisSop Analytical Protocol #97", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-098", new LabHandlingSop("SOP-LIS-HEMO-098", "HemostasisAndThrombosisSop Analytical Protocol #98", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-099", new LabHandlingSop("SOP-LIS-HEMO-099", "HemostasisAndThrombosisSop Analytical Protocol #99", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-100", new LabHandlingSop("SOP-LIS-HEMO-100", "HemostasisAndThrombosisSop Analytical Protocol #100", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-101", new LabHandlingSop("SOP-LIS-HEMO-101", "HemostasisAndThrombosisSop Analytical Protocol #101", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-102", new LabHandlingSop("SOP-LIS-HEMO-102", "HemostasisAndThrombosisSop Analytical Protocol #102", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-103", new LabHandlingSop("SOP-LIS-HEMO-103", "HemostasisAndThrombosisSop Analytical Protocol #103", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-104", new LabHandlingSop("SOP-LIS-HEMO-104", "HemostasisAndThrombosisSop Analytical Protocol #104", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-105", new LabHandlingSop("SOP-LIS-HEMO-105", "HemostasisAndThrombosisSop Analytical Protocol #105", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-106", new LabHandlingSop("SOP-LIS-HEMO-106", "HemostasisAndThrombosisSop Analytical Protocol #106", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-107", new LabHandlingSop("SOP-LIS-HEMO-107", "HemostasisAndThrombosisSop Analytical Protocol #107", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-108", new LabHandlingSop("SOP-LIS-HEMO-108", "HemostasisAndThrombosisSop Analytical Protocol #108", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-109", new LabHandlingSop("SOP-LIS-HEMO-109", "HemostasisAndThrombosisSop Analytical Protocol #109", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-110", new LabHandlingSop("SOP-LIS-HEMO-110", "HemostasisAndThrombosisSop Analytical Protocol #110", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-111", new LabHandlingSop("SOP-LIS-HEMO-111", "HemostasisAndThrombosisSop Analytical Protocol #111", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-112", new LabHandlingSop("SOP-LIS-HEMO-112", "HemostasisAndThrombosisSop Analytical Protocol #112", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-113", new LabHandlingSop("SOP-LIS-HEMO-113", "HemostasisAndThrombosisSop Analytical Protocol #113", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-114", new LabHandlingSop("SOP-LIS-HEMO-114", "HemostasisAndThrombosisSop Analytical Protocol #114", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-115", new LabHandlingSop("SOP-LIS-HEMO-115", "HemostasisAndThrombosisSop Analytical Protocol #115", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-116", new LabHandlingSop("SOP-LIS-HEMO-116", "HemostasisAndThrombosisSop Analytical Protocol #116", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-117", new LabHandlingSop("SOP-LIS-HEMO-117", "HemostasisAndThrombosisSop Analytical Protocol #117", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-118", new LabHandlingSop("SOP-LIS-HEMO-118", "HemostasisAndThrombosisSop Analytical Protocol #118", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-119", new LabHandlingSop("SOP-LIS-HEMO-119", "HemostasisAndThrombosisSop Analytical Protocol #119", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-120", new LabHandlingSop("SOP-LIS-HEMO-120", "HemostasisAndThrombosisSop Analytical Protocol #120", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-121", new LabHandlingSop("SOP-LIS-HEMO-121", "HemostasisAndThrombosisSop Analytical Protocol #121", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-122", new LabHandlingSop("SOP-LIS-HEMO-122", "HemostasisAndThrombosisSop Analytical Protocol #122", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-123", new LabHandlingSop("SOP-LIS-HEMO-123", "HemostasisAndThrombosisSop Analytical Protocol #123", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-124", new LabHandlingSop("SOP-LIS-HEMO-124", "HemostasisAndThrombosisSop Analytical Protocol #124", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-125", new LabHandlingSop("SOP-LIS-HEMO-125", "HemostasisAndThrombosisSop Analytical Protocol #125", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-126", new LabHandlingSop("SOP-LIS-HEMO-126", "HemostasisAndThrombosisSop Analytical Protocol #126", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-127", new LabHandlingSop("SOP-LIS-HEMO-127", "HemostasisAndThrombosisSop Analytical Protocol #127", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-128", new LabHandlingSop("SOP-LIS-HEMO-128", "HemostasisAndThrombosisSop Analytical Protocol #128", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-129", new LabHandlingSop("SOP-LIS-HEMO-129", "HemostasisAndThrombosisSop Analytical Protocol #129", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-130", new LabHandlingSop("SOP-LIS-HEMO-130", "HemostasisAndThrombosisSop Analytical Protocol #130", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-131", new LabHandlingSop("SOP-LIS-HEMO-131", "HemostasisAndThrombosisSop Analytical Protocol #131", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-132", new LabHandlingSop("SOP-LIS-HEMO-132", "HemostasisAndThrombosisSop Analytical Protocol #132", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-133", new LabHandlingSop("SOP-LIS-HEMO-133", "HemostasisAndThrombosisSop Analytical Protocol #133", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-134", new LabHandlingSop("SOP-LIS-HEMO-134", "HemostasisAndThrombosisSop Analytical Protocol #134", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-135", new LabHandlingSop("SOP-LIS-HEMO-135", "HemostasisAndThrombosisSop Analytical Protocol #135", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-136", new LabHandlingSop("SOP-LIS-HEMO-136", "HemostasisAndThrombosisSop Analytical Protocol #136", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-137", new LabHandlingSop("SOP-LIS-HEMO-137", "HemostasisAndThrombosisSop Analytical Protocol #137", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-138", new LabHandlingSop("SOP-LIS-HEMO-138", "HemostasisAndThrombosisSop Analytical Protocol #138", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-139", new LabHandlingSop("SOP-LIS-HEMO-139", "HemostasisAndThrombosisSop Analytical Protocol #139", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-HEMO-140", new LabHandlingSop("SOP-LIS-HEMO-140", "HemostasisAndThrombosisSop Analytical Protocol #140", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
    }

    public Optional<LabHandlingSop> findByCode(String code) {
        return Optional.ofNullable(sops.get(code));
    }

    public List<LabHandlingSop> getAllSops() {
        return new ArrayList<>(sops.values());
    }
}
