package com.hospital.ontology.lis;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;
import java.util.*;

@Component
public class MolecularVirologySopCatalog {

    @Data
    @AllArgsConstructor
    public static class LabHandlingSop {
        private String sopCode;
        private String assayTitle;
        private String preAnalyticalStabilityProtocol;
        private String validatedAnalyzerPlatform;
        private String criticalActionGuideline;
    }

    private final Map<String, LabHandlingSop> sops = new LinkedHashMap<>();

    public MolecularVirologySopCatalog() {
        initializeSops();
    }

    private void initializeSops() {
        sops.put("SOP-LIS-MOLE-001", new LabHandlingSop("SOP-LIS-MOLE-001", "MolecularVirologySop Analytical Protocol #1", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-002", new LabHandlingSop("SOP-LIS-MOLE-002", "MolecularVirologySop Analytical Protocol #2", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-003", new LabHandlingSop("SOP-LIS-MOLE-003", "MolecularVirologySop Analytical Protocol #3", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-004", new LabHandlingSop("SOP-LIS-MOLE-004", "MolecularVirologySop Analytical Protocol #4", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-005", new LabHandlingSop("SOP-LIS-MOLE-005", "MolecularVirologySop Analytical Protocol #5", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-006", new LabHandlingSop("SOP-LIS-MOLE-006", "MolecularVirologySop Analytical Protocol #6", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-007", new LabHandlingSop("SOP-LIS-MOLE-007", "MolecularVirologySop Analytical Protocol #7", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-008", new LabHandlingSop("SOP-LIS-MOLE-008", "MolecularVirologySop Analytical Protocol #8", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-009", new LabHandlingSop("SOP-LIS-MOLE-009", "MolecularVirologySop Analytical Protocol #9", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-010", new LabHandlingSop("SOP-LIS-MOLE-010", "MolecularVirologySop Analytical Protocol #10", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-011", new LabHandlingSop("SOP-LIS-MOLE-011", "MolecularVirologySop Analytical Protocol #11", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-012", new LabHandlingSop("SOP-LIS-MOLE-012", "MolecularVirologySop Analytical Protocol #12", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-013", new LabHandlingSop("SOP-LIS-MOLE-013", "MolecularVirologySop Analytical Protocol #13", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-014", new LabHandlingSop("SOP-LIS-MOLE-014", "MolecularVirologySop Analytical Protocol #14", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-015", new LabHandlingSop("SOP-LIS-MOLE-015", "MolecularVirologySop Analytical Protocol #15", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-016", new LabHandlingSop("SOP-LIS-MOLE-016", "MolecularVirologySop Analytical Protocol #16", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-017", new LabHandlingSop("SOP-LIS-MOLE-017", "MolecularVirologySop Analytical Protocol #17", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-018", new LabHandlingSop("SOP-LIS-MOLE-018", "MolecularVirologySop Analytical Protocol #18", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-019", new LabHandlingSop("SOP-LIS-MOLE-019", "MolecularVirologySop Analytical Protocol #19", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-020", new LabHandlingSop("SOP-LIS-MOLE-020", "MolecularVirologySop Analytical Protocol #20", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-021", new LabHandlingSop("SOP-LIS-MOLE-021", "MolecularVirologySop Analytical Protocol #21", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-022", new LabHandlingSop("SOP-LIS-MOLE-022", "MolecularVirologySop Analytical Protocol #22", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-023", new LabHandlingSop("SOP-LIS-MOLE-023", "MolecularVirologySop Analytical Protocol #23", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-024", new LabHandlingSop("SOP-LIS-MOLE-024", "MolecularVirologySop Analytical Protocol #24", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-025", new LabHandlingSop("SOP-LIS-MOLE-025", "MolecularVirologySop Analytical Protocol #25", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-026", new LabHandlingSop("SOP-LIS-MOLE-026", "MolecularVirologySop Analytical Protocol #26", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-027", new LabHandlingSop("SOP-LIS-MOLE-027", "MolecularVirologySop Analytical Protocol #27", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-028", new LabHandlingSop("SOP-LIS-MOLE-028", "MolecularVirologySop Analytical Protocol #28", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-029", new LabHandlingSop("SOP-LIS-MOLE-029", "MolecularVirologySop Analytical Protocol #29", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-030", new LabHandlingSop("SOP-LIS-MOLE-030", "MolecularVirologySop Analytical Protocol #30", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-031", new LabHandlingSop("SOP-LIS-MOLE-031", "MolecularVirologySop Analytical Protocol #31", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-032", new LabHandlingSop("SOP-LIS-MOLE-032", "MolecularVirologySop Analytical Protocol #32", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-033", new LabHandlingSop("SOP-LIS-MOLE-033", "MolecularVirologySop Analytical Protocol #33", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-034", new LabHandlingSop("SOP-LIS-MOLE-034", "MolecularVirologySop Analytical Protocol #34", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-035", new LabHandlingSop("SOP-LIS-MOLE-035", "MolecularVirologySop Analytical Protocol #35", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-036", new LabHandlingSop("SOP-LIS-MOLE-036", "MolecularVirologySop Analytical Protocol #36", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-037", new LabHandlingSop("SOP-LIS-MOLE-037", "MolecularVirologySop Analytical Protocol #37", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-038", new LabHandlingSop("SOP-LIS-MOLE-038", "MolecularVirologySop Analytical Protocol #38", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-039", new LabHandlingSop("SOP-LIS-MOLE-039", "MolecularVirologySop Analytical Protocol #39", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-040", new LabHandlingSop("SOP-LIS-MOLE-040", "MolecularVirologySop Analytical Protocol #40", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-041", new LabHandlingSop("SOP-LIS-MOLE-041", "MolecularVirologySop Analytical Protocol #41", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-042", new LabHandlingSop("SOP-LIS-MOLE-042", "MolecularVirologySop Analytical Protocol #42", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-043", new LabHandlingSop("SOP-LIS-MOLE-043", "MolecularVirologySop Analytical Protocol #43", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-044", new LabHandlingSop("SOP-LIS-MOLE-044", "MolecularVirologySop Analytical Protocol #44", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-045", new LabHandlingSop("SOP-LIS-MOLE-045", "MolecularVirologySop Analytical Protocol #45", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-046", new LabHandlingSop("SOP-LIS-MOLE-046", "MolecularVirologySop Analytical Protocol #46", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-047", new LabHandlingSop("SOP-LIS-MOLE-047", "MolecularVirologySop Analytical Protocol #47", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-048", new LabHandlingSop("SOP-LIS-MOLE-048", "MolecularVirologySop Analytical Protocol #48", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-049", new LabHandlingSop("SOP-LIS-MOLE-049", "MolecularVirologySop Analytical Protocol #49", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-050", new LabHandlingSop("SOP-LIS-MOLE-050", "MolecularVirologySop Analytical Protocol #50", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-051", new LabHandlingSop("SOP-LIS-MOLE-051", "MolecularVirologySop Analytical Protocol #51", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-052", new LabHandlingSop("SOP-LIS-MOLE-052", "MolecularVirologySop Analytical Protocol #52", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-053", new LabHandlingSop("SOP-LIS-MOLE-053", "MolecularVirologySop Analytical Protocol #53", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-054", new LabHandlingSop("SOP-LIS-MOLE-054", "MolecularVirologySop Analytical Protocol #54", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-055", new LabHandlingSop("SOP-LIS-MOLE-055", "MolecularVirologySop Analytical Protocol #55", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-056", new LabHandlingSop("SOP-LIS-MOLE-056", "MolecularVirologySop Analytical Protocol #56", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-057", new LabHandlingSop("SOP-LIS-MOLE-057", "MolecularVirologySop Analytical Protocol #57", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-058", new LabHandlingSop("SOP-LIS-MOLE-058", "MolecularVirologySop Analytical Protocol #58", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-059", new LabHandlingSop("SOP-LIS-MOLE-059", "MolecularVirologySop Analytical Protocol #59", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-060", new LabHandlingSop("SOP-LIS-MOLE-060", "MolecularVirologySop Analytical Protocol #60", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-061", new LabHandlingSop("SOP-LIS-MOLE-061", "MolecularVirologySop Analytical Protocol #61", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-062", new LabHandlingSop("SOP-LIS-MOLE-062", "MolecularVirologySop Analytical Protocol #62", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-063", new LabHandlingSop("SOP-LIS-MOLE-063", "MolecularVirologySop Analytical Protocol #63", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-064", new LabHandlingSop("SOP-LIS-MOLE-064", "MolecularVirologySop Analytical Protocol #64", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-065", new LabHandlingSop("SOP-LIS-MOLE-065", "MolecularVirologySop Analytical Protocol #65", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-066", new LabHandlingSop("SOP-LIS-MOLE-066", "MolecularVirologySop Analytical Protocol #66", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-067", new LabHandlingSop("SOP-LIS-MOLE-067", "MolecularVirologySop Analytical Protocol #67", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-068", new LabHandlingSop("SOP-LIS-MOLE-068", "MolecularVirologySop Analytical Protocol #68", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-069", new LabHandlingSop("SOP-LIS-MOLE-069", "MolecularVirologySop Analytical Protocol #69", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-070", new LabHandlingSop("SOP-LIS-MOLE-070", "MolecularVirologySop Analytical Protocol #70", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-071", new LabHandlingSop("SOP-LIS-MOLE-071", "MolecularVirologySop Analytical Protocol #71", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-072", new LabHandlingSop("SOP-LIS-MOLE-072", "MolecularVirologySop Analytical Protocol #72", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-073", new LabHandlingSop("SOP-LIS-MOLE-073", "MolecularVirologySop Analytical Protocol #73", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-074", new LabHandlingSop("SOP-LIS-MOLE-074", "MolecularVirologySop Analytical Protocol #74", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-075", new LabHandlingSop("SOP-LIS-MOLE-075", "MolecularVirologySop Analytical Protocol #75", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-076", new LabHandlingSop("SOP-LIS-MOLE-076", "MolecularVirologySop Analytical Protocol #76", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-077", new LabHandlingSop("SOP-LIS-MOLE-077", "MolecularVirologySop Analytical Protocol #77", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-078", new LabHandlingSop("SOP-LIS-MOLE-078", "MolecularVirologySop Analytical Protocol #78", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-079", new LabHandlingSop("SOP-LIS-MOLE-079", "MolecularVirologySop Analytical Protocol #79", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-080", new LabHandlingSop("SOP-LIS-MOLE-080", "MolecularVirologySop Analytical Protocol #80", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-081", new LabHandlingSop("SOP-LIS-MOLE-081", "MolecularVirologySop Analytical Protocol #81", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-082", new LabHandlingSop("SOP-LIS-MOLE-082", "MolecularVirologySop Analytical Protocol #82", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-083", new LabHandlingSop("SOP-LIS-MOLE-083", "MolecularVirologySop Analytical Protocol #83", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-084", new LabHandlingSop("SOP-LIS-MOLE-084", "MolecularVirologySop Analytical Protocol #84", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-085", new LabHandlingSop("SOP-LIS-MOLE-085", "MolecularVirologySop Analytical Protocol #85", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-086", new LabHandlingSop("SOP-LIS-MOLE-086", "MolecularVirologySop Analytical Protocol #86", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-087", new LabHandlingSop("SOP-LIS-MOLE-087", "MolecularVirologySop Analytical Protocol #87", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-088", new LabHandlingSop("SOP-LIS-MOLE-088", "MolecularVirologySop Analytical Protocol #88", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-089", new LabHandlingSop("SOP-LIS-MOLE-089", "MolecularVirologySop Analytical Protocol #89", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-090", new LabHandlingSop("SOP-LIS-MOLE-090", "MolecularVirologySop Analytical Protocol #90", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-091", new LabHandlingSop("SOP-LIS-MOLE-091", "MolecularVirologySop Analytical Protocol #91", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-092", new LabHandlingSop("SOP-LIS-MOLE-092", "MolecularVirologySop Analytical Protocol #92", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-093", new LabHandlingSop("SOP-LIS-MOLE-093", "MolecularVirologySop Analytical Protocol #93", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-094", new LabHandlingSop("SOP-LIS-MOLE-094", "MolecularVirologySop Analytical Protocol #94", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-095", new LabHandlingSop("SOP-LIS-MOLE-095", "MolecularVirologySop Analytical Protocol #95", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-096", new LabHandlingSop("SOP-LIS-MOLE-096", "MolecularVirologySop Analytical Protocol #96", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-097", new LabHandlingSop("SOP-LIS-MOLE-097", "MolecularVirologySop Analytical Protocol #97", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-098", new LabHandlingSop("SOP-LIS-MOLE-098", "MolecularVirologySop Analytical Protocol #98", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-099", new LabHandlingSop("SOP-LIS-MOLE-099", "MolecularVirologySop Analytical Protocol #99", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-100", new LabHandlingSop("SOP-LIS-MOLE-100", "MolecularVirologySop Analytical Protocol #100", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-101", new LabHandlingSop("SOP-LIS-MOLE-101", "MolecularVirologySop Analytical Protocol #101", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-102", new LabHandlingSop("SOP-LIS-MOLE-102", "MolecularVirologySop Analytical Protocol #102", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-103", new LabHandlingSop("SOP-LIS-MOLE-103", "MolecularVirologySop Analytical Protocol #103", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-104", new LabHandlingSop("SOP-LIS-MOLE-104", "MolecularVirologySop Analytical Protocol #104", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-105", new LabHandlingSop("SOP-LIS-MOLE-105", "MolecularVirologySop Analytical Protocol #105", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-106", new LabHandlingSop("SOP-LIS-MOLE-106", "MolecularVirologySop Analytical Protocol #106", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-107", new LabHandlingSop("SOP-LIS-MOLE-107", "MolecularVirologySop Analytical Protocol #107", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-108", new LabHandlingSop("SOP-LIS-MOLE-108", "MolecularVirologySop Analytical Protocol #108", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-109", new LabHandlingSop("SOP-LIS-MOLE-109", "MolecularVirologySop Analytical Protocol #109", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-110", new LabHandlingSop("SOP-LIS-MOLE-110", "MolecularVirologySop Analytical Protocol #110", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-111", new LabHandlingSop("SOP-LIS-MOLE-111", "MolecularVirologySop Analytical Protocol #111", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-112", new LabHandlingSop("SOP-LIS-MOLE-112", "MolecularVirologySop Analytical Protocol #112", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-113", new LabHandlingSop("SOP-LIS-MOLE-113", "MolecularVirologySop Analytical Protocol #113", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-114", new LabHandlingSop("SOP-LIS-MOLE-114", "MolecularVirologySop Analytical Protocol #114", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-115", new LabHandlingSop("SOP-LIS-MOLE-115", "MolecularVirologySop Analytical Protocol #115", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-116", new LabHandlingSop("SOP-LIS-MOLE-116", "MolecularVirologySop Analytical Protocol #116", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-117", new LabHandlingSop("SOP-LIS-MOLE-117", "MolecularVirologySop Analytical Protocol #117", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-118", new LabHandlingSop("SOP-LIS-MOLE-118", "MolecularVirologySop Analytical Protocol #118", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-119", new LabHandlingSop("SOP-LIS-MOLE-119", "MolecularVirologySop Analytical Protocol #119", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-120", new LabHandlingSop("SOP-LIS-MOLE-120", "MolecularVirologySop Analytical Protocol #120", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-121", new LabHandlingSop("SOP-LIS-MOLE-121", "MolecularVirologySop Analytical Protocol #121", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-122", new LabHandlingSop("SOP-LIS-MOLE-122", "MolecularVirologySop Analytical Protocol #122", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-123", new LabHandlingSop("SOP-LIS-MOLE-123", "MolecularVirologySop Analytical Protocol #123", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-124", new LabHandlingSop("SOP-LIS-MOLE-124", "MolecularVirologySop Analytical Protocol #124", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-125", new LabHandlingSop("SOP-LIS-MOLE-125", "MolecularVirologySop Analytical Protocol #125", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-126", new LabHandlingSop("SOP-LIS-MOLE-126", "MolecularVirologySop Analytical Protocol #126", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-127", new LabHandlingSop("SOP-LIS-MOLE-127", "MolecularVirologySop Analytical Protocol #127", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-128", new LabHandlingSop("SOP-LIS-MOLE-128", "MolecularVirologySop Analytical Protocol #128", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-129", new LabHandlingSop("SOP-LIS-MOLE-129", "MolecularVirologySop Analytical Protocol #129", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-130", new LabHandlingSop("SOP-LIS-MOLE-130", "MolecularVirologySop Analytical Protocol #130", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-131", new LabHandlingSop("SOP-LIS-MOLE-131", "MolecularVirologySop Analytical Protocol #131", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-132", new LabHandlingSop("SOP-LIS-MOLE-132", "MolecularVirologySop Analytical Protocol #132", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-133", new LabHandlingSop("SOP-LIS-MOLE-133", "MolecularVirologySop Analytical Protocol #133", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-134", new LabHandlingSop("SOP-LIS-MOLE-134", "MolecularVirologySop Analytical Protocol #134", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-135", new LabHandlingSop("SOP-LIS-MOLE-135", "MolecularVirologySop Analytical Protocol #135", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-136", new LabHandlingSop("SOP-LIS-MOLE-136", "MolecularVirologySop Analytical Protocol #136", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-137", new LabHandlingSop("SOP-LIS-MOLE-137", "MolecularVirologySop Analytical Protocol #137", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-138", new LabHandlingSop("SOP-LIS-MOLE-138", "MolecularVirologySop Analytical Protocol #138", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-139", new LabHandlingSop("SOP-LIS-MOLE-139", "MolecularVirologySop Analytical Protocol #139", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
        sops.put("SOP-LIS-MOLE-140", new LabHandlingSop("SOP-LIS-MOLE-140", "MolecularVirologySop Analytical Protocol #140", "Specimen stability 48h at 2-8 C. Centrifuge at 3000 RPM for 10 min.", "Roche Cobas 8000 / Sysmex XN-9000", "Critical panic callback within 15 minutes."));
    }

    public Optional<LabHandlingSop> findByCode(String code) {
        return Optional.ofNullable(sops.get(code));
    }

    public List<LabHandlingSop> getAllSops() {
        return new ArrayList<>(sops.values());
    }
}
