-- ==============================================================================
-- Flyway Database Migration: V3__comprehensive_medical_catalogs.sql
-- Description: Comprehensive Medical Catalogs (ICD-10-CM, LOINC, CPT, SNOMED-CT, Formulary)
-- ==============================================================================

-- 1. EXTENDED ICD-10-CM DIAGNOSTIC CATALOG
INSERT INTO icd10_codes (code, description, chapter, is_chronic, is_notifiable, created_at, updated_at) VALUES
('I10', 'Essential (primary) hypertension', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I11.0', 'Hypertensive heart disease with heart failure', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I11.9', 'Hypertensive heart disease without heart failure', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I12.0', 'Hypertensive chronic kidney disease with stage 5 chronic kidney disease or end stage renal disease', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I12.9', 'Hypertensive chronic kidney disease with stage 1 through stage 4 chronic kidney disease', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I20.0', 'Unstable angina', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I20.1', 'Angina pectoris with documented spasm', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I20.8', 'Other forms of angina pectoris', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I20.9', 'Angina pectoris, unspecified', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I21.0', 'ST elevation (STEMI) myocardial infarction of anterior wall', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I21.1', 'ST elevation (STEMI) myocardial infarction of inferior wall', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I21.2', 'ST elevation (STEMI) myocardial infarction of other sites', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I21.3', 'ST elevation (STEMI) myocardial infarction of unspecified site', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I21.4', 'Non-ST elevation (NSTEMI) myocardial infarction', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I25.10', 'Atherosclerotic heart disease of native coronary artery without angina pectoris', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I25.110', 'Atherosclerotic heart disease of native coronary artery with unstable angina pectoris', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I26.0', 'Pulmonary embolism with acute cor pulmonale', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I26.9', 'Pulmonary embolism without acute cor pulmonale', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I48.0', 'Paroxysmal atrial fibrillation', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I48.1', 'Persistent atrial fibrillation', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I48.2', 'Chronic atrial fibrillation', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I50.1', 'Left ventricular failure, unspecified', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I50.20', 'Unspecified systolic (congestive) heart failure', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I50.21', 'Acute systolic (congestive) heart failure', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I50.22', 'Chronic systolic (congestive) heart failure', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I50.23', 'Acute on chronic systolic (congestive) heart failure', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I50.30', 'Unspecified diastolic (congestive) heart failure', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I50.31', 'Acute diastolic (congestive) heart failure', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I50.32', 'Chronic diastolic (congestive) heart failure', 'Diseases of the circulatory system', true, false, NOW(), NOW()),
('I50.33', 'Acute on chronic diastolic (congestive) heart failure', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I63.0', 'Cerebral infarction due to thrombosis of precerebral arteries', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I63.1', 'Cerebral infarction due to embolism of precerebral arteries', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I63.2', 'Cerebral infarction due to unspecified occlusion or stenosis of precerebral arteries', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I63.3', 'Cerebral infarction due to thrombosis of cerebral arteries', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I63.4', 'Cerebral infarction due to embolism of cerebral arteries', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I63.5', 'Cerebral infarction due to unspecified occlusion or stenosis of cerebral arteries', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I63.9', 'Cerebral infarction, unspecified', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I61.0', 'Nontraumatic intracerebral hemorrhage in hemisphere, subcortical', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I61.1', 'Nontraumatic intracerebral hemorrhage in hemisphere, cortical', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('I61.9', 'Nontraumatic intracerebral hemorrhage, unspecified', 'Diseases of the circulatory system', false, false, NOW(), NOW()),
('E10.10', 'Type 1 diabetes mellitus with ketoacidosis without coma', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E10.11', 'Type 1 diabetes mellitus with ketoacidosis with coma', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E10.21', 'Type 1 diabetes mellitus with diabetic nephropathy', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E10.22', 'Type 1 diabetes mellitus with diabetic chronic kidney disease', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E10.311', 'Type 1 diabetes mellitus with unspecified diabetic retinopathy with macular edema', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E10.40', 'Type 1 diabetes mellitus with diabetic neuropathy, unspecified', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E10.65', 'Type 1 diabetes mellitus with hyperglycemia', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E10.9', 'Type 1 diabetes mellitus without complications', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E11.00', 'Type 2 diabetes mellitus with hyperosmolarity without nonketotic hyperglycemic-hyperosmolar coma (NKHHC)', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E11.01', 'Type 2 diabetes mellitus with hyperosmolarity with coma', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E11.21', 'Type 2 diabetes mellitus with diabetic nephropathy', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E11.22', 'Type 2 diabetes mellitus with diabetic chronic kidney disease', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E11.311', 'Type 2 diabetes mellitus with unspecified diabetic retinopathy with macular edema', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E11.40', 'Type 2 diabetes mellitus with diabetic neuropathy, unspecified', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E11.51', 'Type 2 diabetes mellitus with diabetic peripheral angiopathy without gangrene', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E11.52', 'Type 2 diabetes mellitus with diabetic peripheral angiopathy with gangrene', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E11.65', 'Type 2 diabetes mellitus with hyperglycemia', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E11.69', 'Type 2 diabetes mellitus with other specified complication', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E11.9', 'Type 2 diabetes mellitus without complications', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E03.0', 'Congenital hypothyroidism with diffuse goiter', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E03.1', 'Congenital hypothyroidism without goiter', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E03.8', 'Other specified hypothyroidism', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E03.9', 'Hypothyroidism, unspecified', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E05.00', 'Thyrotoxicosis with diffuse goiter without thyrotoxic crisis or storm', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E05.01', 'Thyrotoxicosis with diffuse goiter with thyrotoxic crisis or storm', 'Endocrine, nutritional and metabolic diseases', false, false, NOW(), NOW()),
('E66.01', 'Morbid (severe) obesity due to excess calories', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E66.09', 'Other obesity due to excess calories', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E78.00', 'Pure hypercholesterolemia, unspecified', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E78.01', 'Familial hypercholesterolemia', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E78.1', 'Pure hyperglyceridemia', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E78.2', 'Mixed hyperlipidemia', 'Endocrine, nutritional and metabolic diseases', true, false, NOW(), NOW()),
('E87.0', 'Hyperosmolality and hypernatremia', 'Endocrine, nutritional and metabolic diseases', false, false, NOW(), NOW()),
('E87.1', 'Hypo-osmolality and hyponatremia', 'Endocrine, nutritional and metabolic diseases', false, false, NOW(), NOW()),
('E87.2', 'Acidosis', 'Endocrine, nutritional and metabolic diseases', false, false, NOW(), NOW()),
('E87.5', 'Hyperkalemia', 'Endocrine, nutritional and metabolic diseases', false, false, NOW(), NOW()),
('E87.6', 'Hypokalemia', 'Endocrine, nutritional and metabolic diseases', false, false, NOW(), NOW()),
('J44.0', 'Chronic obstructive pulmonary disease with (acute) lower respiratory infection', 'Diseases of the respiratory system', true, false, NOW(), NOW()),
('J44.1', 'Chronic obstructive pulmonary disease with (acute) exacerbation', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J44.9', 'Chronic obstructive pulmonary disease, unspecified', 'Diseases of the respiratory system', true, false, NOW(), NOW()),
('J45.20', 'Mild intermittent asthma, uncomplicated', 'Diseases of the respiratory system', true, false, NOW(), NOW()),
('J45.21', 'Mild intermittent asthma with (acute) exacerbation', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J45.30', 'Mild persistent asthma, uncomplicated', 'Diseases of the respiratory system', true, false, NOW(), NOW()),
('J45.31', 'Mild persistent asthma with (acute) exacerbation', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J45.40', 'Moderate persistent asthma, uncomplicated', 'Diseases of the respiratory system', true, false, NOW(), NOW()),
('J45.41', 'Moderate persistent asthma with (acute) exacerbation', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J45.50', 'Severe persistent asthma, uncomplicated', 'Diseases of the respiratory system', true, false, NOW(), NOW()),
('J45.51', 'Severe persistent asthma with (acute) exacerbation', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J45.52', 'Severe persistent asthma with status asthmaticus', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J18.0', 'Bronchopneumonia, unspecified organism', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J18.1', 'Lobar pneumonia, unspecified organism', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J18.9', 'Pneumonia, unspecified organism', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J80', 'Acute respiratory distress syndrome', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J96.00', 'Acute respiratory failure, unspecified with hypoxia or hypercapnia', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J96.01', 'Acute respiratory failure with hypoxia', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('J96.02', 'Acute respiratory failure with hypercapnia', 'Diseases of the respiratory system', false, false, NOW(), NOW()),
('K21.0', 'Gastro-esophageal reflux disease with esophagitis', 'Diseases of the digestive system', true, false, NOW(), NOW()),
('K21.9', 'Gastro-esophageal reflux disease without esophagitis', 'Diseases of the digestive system', true, false, NOW(), NOW()),
('K25.0', 'Acute gastric ulcer with hemorrhage', 'Diseases of the digestive system', false, false, NOW(), NOW()),
('K25.1', 'Acute gastric ulcer with perforation', 'Diseases of the digestive system', false, false, NOW(), NOW()),
('K25.9', 'Gastric ulcer, unspecified as acute or chronic, without hemorrhage or perforation', 'Diseases of the digestive system', true, false, NOW(), NOW()),
('K35.20', 'Acute appendicitis with generalized peritonitis, without perforation or abscess', 'Diseases of the digestive system', false, false, NOW(), NOW()),
('K35.30', 'Acute appendicitis with localized peritonitis, without perforation or gangrene', 'Diseases of the digestive system', false, false, NOW(), NOW()),
('K35.80', 'Unspecified acute appendicitis', 'Diseases of the digestive system', false, false, NOW(), NOW()),
('K80.00', 'Calculus of gallbladder with acute cholecystitis without obstruction', 'Diseases of the digestive system', false, false, NOW(), NOW()),
('K80.10', 'Calculus of gallbladder with chronic cholecystitis without obstruction', 'Diseases of the digestive system', true, false, NOW(), NOW()),
('K85.90', 'Acute pancreatitis without necrosis or infection, unspecified', 'Diseases of the digestive system', false, false, NOW(), NOW()),
('K70.30', 'Alcoholic cirrhosis of liver without ascites', 'Diseases of the digestive system', true, false, NOW(), NOW()),
('K70.31', 'Alcoholic cirrhosis of liver with ascites', 'Diseases of the digestive system', true, false, NOW(), NOW()),
('K74.60', 'Unspecified cirrhosis of liver', 'Diseases of the digestive system', true, false, NOW(), NOW()),
('N17.0', 'Acute kidney injury with tubular necrosis', 'Diseases of the genitourinary system', false, false, NOW(), NOW()),
('N17.9', 'Acute kidney injury, unspecified', 'Diseases of the genitourinary system', false, false, NOW(), NOW()),
('N18.1', 'Chronic kidney disease, stage 1', 'Diseases of the genitourinary system', true, false, NOW(), NOW()),
('N18.2', 'Chronic kidney disease, stage 2 (mild)', 'Diseases of the genitourinary system', true, false, NOW(), NOW()),
('N18.30', 'Chronic kidney disease, stage 3 unspecified', 'Diseases of the genitourinary system', true, false, NOW(), NOW()),
('N18.31', 'Chronic kidney disease, stage 3a', 'Diseases of the genitourinary system', true, false, NOW(), NOW()),
('N18.32', 'Chronic kidney disease, stage 3b', 'Diseases of the genitourinary system', true, false, NOW(), NOW()),
('N18.4', 'Chronic kidney disease, stage 4 (severe)', 'Diseases of the genitourinary system', true, false, NOW(), NOW()),
('N18.5', 'Chronic kidney disease, stage 5', 'Diseases of the genitourinary system', true, false, NOW(), NOW()),
('N18.6', 'End stage renal disease', 'Diseases of the genitourinary system', true, false, NOW(), NOW()),
('N39.0', 'Urinary tract infection, site not specified', 'Diseases of the genitourinary system', false, false, NOW(), NOW())
ON CONFLICT (code) DO UPDATE 
SET description = EXCLUDED.description,
    chapter = EXCLUDED.chapter,
    is_chronic = EXCLUDED.is_chronic,
    is_notifiable = EXCLUDED.is_notifiable,
    updated_at = NOW();

-- 2. EXTENDED SURGICAL CPT PRICE LIST CATALOG
INSERT INTO service_items (code, name, category, standard_rate, tax_rate, active, created_at, updated_at) VALUES
('CPT-99202', 'Outpatient New Visit Level 2 (15-29 min)', 'CONSULTATION', 850.00, 0.00, true, NOW(), NOW()),
('CPT-99203', 'Outpatient New Visit Level 3 (30-44 min)', 'CONSULTATION', 1200.00, 0.00, true, NOW(), NOW()),
('CPT-99204', 'Outpatient New Visit Level 4 (45-59 min)', 'CONSULTATION', 1800.00, 0.00, true, NOW(), NOW()),
('CPT-99205', 'Outpatient New Visit Level 5 (60-74 min)', 'CONSULTATION', 2500.00, 0.00, true, NOW(), NOW()),
('CPT-99213', 'Outpatient Established Visit Level 3 (20-29 min)', 'CONSULTATION', 900.00, 0.00, true, NOW(), NOW()),
('CPT-99214', 'Outpatient Established Visit Level 4 (30-39 min)', 'CONSULTATION', 1400.00, 0.00, true, NOW(), NOW()),
('CPT-99215', 'Outpatient Established Visit Level 5 (40-54 min)', 'CONSULTATION', 2000.00, 0.00, true, NOW(), NOW()),
('CPT-99221', 'Initial Hospital Inpatient Care (Low MDM)', 'INPATIENT', 1500.00, 0.00, true, NOW(), NOW()),
('CPT-99222', 'Initial Hospital Inpatient Care (Moderate MDM)', 'INPATIENT', 2200.00, 0.00, true, NOW(), NOW()),
('CPT-99223', 'Initial Hospital Inpatient Care (High MDM)', 'INPATIENT', 3200.00, 0.00, true, NOW(), NOW()),
('CPT-99283', 'Emergency Dept Visit (Moderate Severity)', 'EMERGENCY', 1600.00, 0.00, true, NOW(), NOW()),
('CPT-99284', 'Emergency Dept Visit (High Severity Urgent)', 'EMERGENCY', 2500.00, 0.00, true, NOW(), NOW()),
('CPT-99285', 'Emergency Dept Visit (Immediate Life Threat)', 'EMERGENCY', 4000.00, 0.00, true, NOW(), NOW()),
('CPT-99291', 'Critical Care First 30-74 Minutes', 'CRITICAL_CARE', 5500.00, 0.00, true, NOW(), NOW()),
('CPT-33510', 'Coronary Artery Bypass Graft (CABG x 1 Vessel)', 'SURGERY', 180000.00, 5.00, true, NOW(), NOW()),
('CPT-33511', 'Coronary Artery Bypass Graft (CABG x 2 Vessels)', 'SURGERY', 210000.00, 5.00, true, NOW(), NOW()),
('CPT-33512', 'Coronary Artery Bypass Graft (CABG x 3 Vessels)', 'SURGERY', 240000.00, 5.00, true, NOW(), NOW()),
('CPT-92928', 'Percutaneous Coronary Intervention (PCI Single Stent)', 'PROCEDURE', 95000.00, 5.00, true, NOW(), NOW()),
('CPT-27447', 'Total Knee Arthroplasty (TKA)', 'SURGERY', 160000.00, 5.00, true, NOW(), NOW()),
('CPT-27130', 'Total Hip Arthroplasty (THA)', 'SURGERY', 175000.00, 5.00, true, NOW(), NOW()),
('CPT-47562', 'Laparoscopic Cholecystectomy', 'SURGERY', 55000.00, 5.00, true, NOW(), NOW()),
('CPT-44970', 'Laparoscopic Appendectomy', 'SURGERY', 48000.00, 5.00, true, NOW(), NOW()),
('CPT-90935', 'Hemodialysis Single Evaluation Session', 'PROCEDURE', 2500.00, 0.00, true, NOW(), NOW()),
('CPT-96413', 'Chemotherapy IV Infusion First Hour', 'PROCEDURE', 3500.00, 0.00, true, NOW(), NOW())
ON CONFLICT (code) DO UPDATE 
SET name = EXCLUDED.name,
    category = EXCLUDED.category,
    standard_rate = EXCLUDED.standard_rate,
    tax_rate = EXCLUDED.tax_rate,
    updated_at = NOW();
