package com.hospital.ontology.beers;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;
import java.util.*;

@Component
public class AnticholinergicGeriatricRisksDirectory {

    @Data
    @AllArgsConstructor
    public static class BeersRiskEntry {
        private String riskCode;
        private String medicationName;
        private String agsTier;
        private String rationale;
        private String recommendation;
    }

    private final Map<String, BeersRiskEntry> risks = new LinkedHashMap<>();

    public AnticholinergicGeriatricRisksDirectory() {
        initializeRisks();
    }

    private void initializeRisks() {
        risks.put("BEERS-ANTI-001", new BeersRiskEntry("BEERS-ANTI-001", "AnticholinergicGeriatricRisks Medication #1", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-002", new BeersRiskEntry("BEERS-ANTI-002", "AnticholinergicGeriatricRisks Medication #2", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-003", new BeersRiskEntry("BEERS-ANTI-003", "AnticholinergicGeriatricRisks Medication #3", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-004", new BeersRiskEntry("BEERS-ANTI-004", "AnticholinergicGeriatricRisks Medication #4", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-005", new BeersRiskEntry("BEERS-ANTI-005", "AnticholinergicGeriatricRisks Medication #5", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-006", new BeersRiskEntry("BEERS-ANTI-006", "AnticholinergicGeriatricRisks Medication #6", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-007", new BeersRiskEntry("BEERS-ANTI-007", "AnticholinergicGeriatricRisks Medication #7", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-008", new BeersRiskEntry("BEERS-ANTI-008", "AnticholinergicGeriatricRisks Medication #8", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-009", new BeersRiskEntry("BEERS-ANTI-009", "AnticholinergicGeriatricRisks Medication #9", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-010", new BeersRiskEntry("BEERS-ANTI-010", "AnticholinergicGeriatricRisks Medication #10", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-011", new BeersRiskEntry("BEERS-ANTI-011", "AnticholinergicGeriatricRisks Medication #11", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-012", new BeersRiskEntry("BEERS-ANTI-012", "AnticholinergicGeriatricRisks Medication #12", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-013", new BeersRiskEntry("BEERS-ANTI-013", "AnticholinergicGeriatricRisks Medication #13", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-014", new BeersRiskEntry("BEERS-ANTI-014", "AnticholinergicGeriatricRisks Medication #14", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-015", new BeersRiskEntry("BEERS-ANTI-015", "AnticholinergicGeriatricRisks Medication #15", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-016", new BeersRiskEntry("BEERS-ANTI-016", "AnticholinergicGeriatricRisks Medication #16", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-017", new BeersRiskEntry("BEERS-ANTI-017", "AnticholinergicGeriatricRisks Medication #17", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-018", new BeersRiskEntry("BEERS-ANTI-018", "AnticholinergicGeriatricRisks Medication #18", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-019", new BeersRiskEntry("BEERS-ANTI-019", "AnticholinergicGeriatricRisks Medication #19", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-020", new BeersRiskEntry("BEERS-ANTI-020", "AnticholinergicGeriatricRisks Medication #20", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-021", new BeersRiskEntry("BEERS-ANTI-021", "AnticholinergicGeriatricRisks Medication #21", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-022", new BeersRiskEntry("BEERS-ANTI-022", "AnticholinergicGeriatricRisks Medication #22", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-023", new BeersRiskEntry("BEERS-ANTI-023", "AnticholinergicGeriatricRisks Medication #23", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-024", new BeersRiskEntry("BEERS-ANTI-024", "AnticholinergicGeriatricRisks Medication #24", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-025", new BeersRiskEntry("BEERS-ANTI-025", "AnticholinergicGeriatricRisks Medication #25", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-026", new BeersRiskEntry("BEERS-ANTI-026", "AnticholinergicGeriatricRisks Medication #26", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-027", new BeersRiskEntry("BEERS-ANTI-027", "AnticholinergicGeriatricRisks Medication #27", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-028", new BeersRiskEntry("BEERS-ANTI-028", "AnticholinergicGeriatricRisks Medication #28", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-029", new BeersRiskEntry("BEERS-ANTI-029", "AnticholinergicGeriatricRisks Medication #29", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-030", new BeersRiskEntry("BEERS-ANTI-030", "AnticholinergicGeriatricRisks Medication #30", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-031", new BeersRiskEntry("BEERS-ANTI-031", "AnticholinergicGeriatricRisks Medication #31", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-032", new BeersRiskEntry("BEERS-ANTI-032", "AnticholinergicGeriatricRisks Medication #32", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-033", new BeersRiskEntry("BEERS-ANTI-033", "AnticholinergicGeriatricRisks Medication #33", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-034", new BeersRiskEntry("BEERS-ANTI-034", "AnticholinergicGeriatricRisks Medication #34", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-035", new BeersRiskEntry("BEERS-ANTI-035", "AnticholinergicGeriatricRisks Medication #35", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-036", new BeersRiskEntry("BEERS-ANTI-036", "AnticholinergicGeriatricRisks Medication #36", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-037", new BeersRiskEntry("BEERS-ANTI-037", "AnticholinergicGeriatricRisks Medication #37", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-038", new BeersRiskEntry("BEERS-ANTI-038", "AnticholinergicGeriatricRisks Medication #38", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-039", new BeersRiskEntry("BEERS-ANTI-039", "AnticholinergicGeriatricRisks Medication #39", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-040", new BeersRiskEntry("BEERS-ANTI-040", "AnticholinergicGeriatricRisks Medication #40", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-041", new BeersRiskEntry("BEERS-ANTI-041", "AnticholinergicGeriatricRisks Medication #41", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-042", new BeersRiskEntry("BEERS-ANTI-042", "AnticholinergicGeriatricRisks Medication #42", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-043", new BeersRiskEntry("BEERS-ANTI-043", "AnticholinergicGeriatricRisks Medication #43", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-044", new BeersRiskEntry("BEERS-ANTI-044", "AnticholinergicGeriatricRisks Medication #44", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-045", new BeersRiskEntry("BEERS-ANTI-045", "AnticholinergicGeriatricRisks Medication #45", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-046", new BeersRiskEntry("BEERS-ANTI-046", "AnticholinergicGeriatricRisks Medication #46", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-047", new BeersRiskEntry("BEERS-ANTI-047", "AnticholinergicGeriatricRisks Medication #47", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-048", new BeersRiskEntry("BEERS-ANTI-048", "AnticholinergicGeriatricRisks Medication #48", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-049", new BeersRiskEntry("BEERS-ANTI-049", "AnticholinergicGeriatricRisks Medication #49", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-050", new BeersRiskEntry("BEERS-ANTI-050", "AnticholinergicGeriatricRisks Medication #50", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-051", new BeersRiskEntry("BEERS-ANTI-051", "AnticholinergicGeriatricRisks Medication #51", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-052", new BeersRiskEntry("BEERS-ANTI-052", "AnticholinergicGeriatricRisks Medication #52", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-053", new BeersRiskEntry("BEERS-ANTI-053", "AnticholinergicGeriatricRisks Medication #53", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-054", new BeersRiskEntry("BEERS-ANTI-054", "AnticholinergicGeriatricRisks Medication #54", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-055", new BeersRiskEntry("BEERS-ANTI-055", "AnticholinergicGeriatricRisks Medication #55", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-056", new BeersRiskEntry("BEERS-ANTI-056", "AnticholinergicGeriatricRisks Medication #56", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-057", new BeersRiskEntry("BEERS-ANTI-057", "AnticholinergicGeriatricRisks Medication #57", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-058", new BeersRiskEntry("BEERS-ANTI-058", "AnticholinergicGeriatricRisks Medication #58", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-059", new BeersRiskEntry("BEERS-ANTI-059", "AnticholinergicGeriatricRisks Medication #59", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-060", new BeersRiskEntry("BEERS-ANTI-060", "AnticholinergicGeriatricRisks Medication #60", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-061", new BeersRiskEntry("BEERS-ANTI-061", "AnticholinergicGeriatricRisks Medication #61", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-062", new BeersRiskEntry("BEERS-ANTI-062", "AnticholinergicGeriatricRisks Medication #62", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-063", new BeersRiskEntry("BEERS-ANTI-063", "AnticholinergicGeriatricRisks Medication #63", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-064", new BeersRiskEntry("BEERS-ANTI-064", "AnticholinergicGeriatricRisks Medication #64", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-065", new BeersRiskEntry("BEERS-ANTI-065", "AnticholinergicGeriatricRisks Medication #65", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-066", new BeersRiskEntry("BEERS-ANTI-066", "AnticholinergicGeriatricRisks Medication #66", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-067", new BeersRiskEntry("BEERS-ANTI-067", "AnticholinergicGeriatricRisks Medication #67", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-068", new BeersRiskEntry("BEERS-ANTI-068", "AnticholinergicGeriatricRisks Medication #68", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-069", new BeersRiskEntry("BEERS-ANTI-069", "AnticholinergicGeriatricRisks Medication #69", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-070", new BeersRiskEntry("BEERS-ANTI-070", "AnticholinergicGeriatricRisks Medication #70", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-071", new BeersRiskEntry("BEERS-ANTI-071", "AnticholinergicGeriatricRisks Medication #71", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-072", new BeersRiskEntry("BEERS-ANTI-072", "AnticholinergicGeriatricRisks Medication #72", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-073", new BeersRiskEntry("BEERS-ANTI-073", "AnticholinergicGeriatricRisks Medication #73", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-074", new BeersRiskEntry("BEERS-ANTI-074", "AnticholinergicGeriatricRisks Medication #74", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-075", new BeersRiskEntry("BEERS-ANTI-075", "AnticholinergicGeriatricRisks Medication #75", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-076", new BeersRiskEntry("BEERS-ANTI-076", "AnticholinergicGeriatricRisks Medication #76", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-077", new BeersRiskEntry("BEERS-ANTI-077", "AnticholinergicGeriatricRisks Medication #77", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-078", new BeersRiskEntry("BEERS-ANTI-078", "AnticholinergicGeriatricRisks Medication #78", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-079", new BeersRiskEntry("BEERS-ANTI-079", "AnticholinergicGeriatricRisks Medication #79", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-080", new BeersRiskEntry("BEERS-ANTI-080", "AnticholinergicGeriatricRisks Medication #80", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-081", new BeersRiskEntry("BEERS-ANTI-081", "AnticholinergicGeriatricRisks Medication #81", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-082", new BeersRiskEntry("BEERS-ANTI-082", "AnticholinergicGeriatricRisks Medication #82", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-083", new BeersRiskEntry("BEERS-ANTI-083", "AnticholinergicGeriatricRisks Medication #83", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-084", new BeersRiskEntry("BEERS-ANTI-084", "AnticholinergicGeriatricRisks Medication #84", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-085", new BeersRiskEntry("BEERS-ANTI-085", "AnticholinergicGeriatricRisks Medication #85", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-086", new BeersRiskEntry("BEERS-ANTI-086", "AnticholinergicGeriatricRisks Medication #86", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-087", new BeersRiskEntry("BEERS-ANTI-087", "AnticholinergicGeriatricRisks Medication #87", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-088", new BeersRiskEntry("BEERS-ANTI-088", "AnticholinergicGeriatricRisks Medication #88", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-089", new BeersRiskEntry("BEERS-ANTI-089", "AnticholinergicGeriatricRisks Medication #89", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-090", new BeersRiskEntry("BEERS-ANTI-090", "AnticholinergicGeriatricRisks Medication #90", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-091", new BeersRiskEntry("BEERS-ANTI-091", "AnticholinergicGeriatricRisks Medication #91", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-092", new BeersRiskEntry("BEERS-ANTI-092", "AnticholinergicGeriatricRisks Medication #92", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-093", new BeersRiskEntry("BEERS-ANTI-093", "AnticholinergicGeriatricRisks Medication #93", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-094", new BeersRiskEntry("BEERS-ANTI-094", "AnticholinergicGeriatricRisks Medication #94", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-095", new BeersRiskEntry("BEERS-ANTI-095", "AnticholinergicGeriatricRisks Medication #95", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-096", new BeersRiskEntry("BEERS-ANTI-096", "AnticholinergicGeriatricRisks Medication #96", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-097", new BeersRiskEntry("BEERS-ANTI-097", "AnticholinergicGeriatricRisks Medication #97", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-098", new BeersRiskEntry("BEERS-ANTI-098", "AnticholinergicGeriatricRisks Medication #98", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-099", new BeersRiskEntry("BEERS-ANTI-099", "AnticholinergicGeriatricRisks Medication #99", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-100", new BeersRiskEntry("BEERS-ANTI-100", "AnticholinergicGeriatricRisks Medication #100", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-101", new BeersRiskEntry("BEERS-ANTI-101", "AnticholinergicGeriatricRisks Medication #101", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-102", new BeersRiskEntry("BEERS-ANTI-102", "AnticholinergicGeriatricRisks Medication #102", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-103", new BeersRiskEntry("BEERS-ANTI-103", "AnticholinergicGeriatricRisks Medication #103", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-104", new BeersRiskEntry("BEERS-ANTI-104", "AnticholinergicGeriatricRisks Medication #104", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-105", new BeersRiskEntry("BEERS-ANTI-105", "AnticholinergicGeriatricRisks Medication #105", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-106", new BeersRiskEntry("BEERS-ANTI-106", "AnticholinergicGeriatricRisks Medication #106", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-107", new BeersRiskEntry("BEERS-ANTI-107", "AnticholinergicGeriatricRisks Medication #107", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-108", new BeersRiskEntry("BEERS-ANTI-108", "AnticholinergicGeriatricRisks Medication #108", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-109", new BeersRiskEntry("BEERS-ANTI-109", "AnticholinergicGeriatricRisks Medication #109", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-110", new BeersRiskEntry("BEERS-ANTI-110", "AnticholinergicGeriatricRisks Medication #110", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-111", new BeersRiskEntry("BEERS-ANTI-111", "AnticholinergicGeriatricRisks Medication #111", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-112", new BeersRiskEntry("BEERS-ANTI-112", "AnticholinergicGeriatricRisks Medication #112", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-113", new BeersRiskEntry("BEERS-ANTI-113", "AnticholinergicGeriatricRisks Medication #113", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-114", new BeersRiskEntry("BEERS-ANTI-114", "AnticholinergicGeriatricRisks Medication #114", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-115", new BeersRiskEntry("BEERS-ANTI-115", "AnticholinergicGeriatricRisks Medication #115", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-116", new BeersRiskEntry("BEERS-ANTI-116", "AnticholinergicGeriatricRisks Medication #116", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-117", new BeersRiskEntry("BEERS-ANTI-117", "AnticholinergicGeriatricRisks Medication #117", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-118", new BeersRiskEntry("BEERS-ANTI-118", "AnticholinergicGeriatricRisks Medication #118", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-119", new BeersRiskEntry("BEERS-ANTI-119", "AnticholinergicGeriatricRisks Medication #119", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-120", new BeersRiskEntry("BEERS-ANTI-120", "AnticholinergicGeriatricRisks Medication #120", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-121", new BeersRiskEntry("BEERS-ANTI-121", "AnticholinergicGeriatricRisks Medication #121", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-122", new BeersRiskEntry("BEERS-ANTI-122", "AnticholinergicGeriatricRisks Medication #122", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-123", new BeersRiskEntry("BEERS-ANTI-123", "AnticholinergicGeriatricRisks Medication #123", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-124", new BeersRiskEntry("BEERS-ANTI-124", "AnticholinergicGeriatricRisks Medication #124", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-125", new BeersRiskEntry("BEERS-ANTI-125", "AnticholinergicGeriatricRisks Medication #125", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-126", new BeersRiskEntry("BEERS-ANTI-126", "AnticholinergicGeriatricRisks Medication #126", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-127", new BeersRiskEntry("BEERS-ANTI-127", "AnticholinergicGeriatricRisks Medication #127", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-128", new BeersRiskEntry("BEERS-ANTI-128", "AnticholinergicGeriatricRisks Medication #128", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-129", new BeersRiskEntry("BEERS-ANTI-129", "AnticholinergicGeriatricRisks Medication #129", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-130", new BeersRiskEntry("BEERS-ANTI-130", "AnticholinergicGeriatricRisks Medication #130", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-131", new BeersRiskEntry("BEERS-ANTI-131", "AnticholinergicGeriatricRisks Medication #131", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-132", new BeersRiskEntry("BEERS-ANTI-132", "AnticholinergicGeriatricRisks Medication #132", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-133", new BeersRiskEntry("BEERS-ANTI-133", "AnticholinergicGeriatricRisks Medication #133", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-134", new BeersRiskEntry("BEERS-ANTI-134", "AnticholinergicGeriatricRisks Medication #134", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-135", new BeersRiskEntry("BEERS-ANTI-135", "AnticholinergicGeriatricRisks Medication #135", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-136", new BeersRiskEntry("BEERS-ANTI-136", "AnticholinergicGeriatricRisks Medication #136", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-137", new BeersRiskEntry("BEERS-ANTI-137", "AnticholinergicGeriatricRisks Medication #137", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-138", new BeersRiskEntry("BEERS-ANTI-138", "AnticholinergicGeriatricRisks Medication #138", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-139", new BeersRiskEntry("BEERS-ANTI-139", "AnticholinergicGeriatricRisks Medication #139", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ANTI-140", new BeersRiskEntry("BEERS-ANTI-140", "AnticholinergicGeriatricRisks Medication #140", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
    }

    public Optional<BeersRiskEntry> getByCode(String code) {
        return Optional.ofNullable(risks.get(code));
    }

    public List<BeersRiskEntry> getAllRisks() {
        return new ArrayList<>(risks.values());
    }
}
