package com.hospital.ontology.beers;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;
import java.util.*;

@Component
public class CardiovascularGeriatricRisksDirectory {

    @Data
    @AllArgsConstructor
    public static class BeersRiskEntry {
        private String riskCode;
        private String medicationName;
        private String agsTier;
        private String rationale;
        private String recommendation;
    }

    private final Map<String, BeersRiskEntry> risks = new LinkedHashMap<>();

    public CardiovascularGeriatricRisksDirectory() {
        initializeRisks();
    }

    private void initializeRisks() {
        risks.put("BEERS-CARD-001", new BeersRiskEntry("BEERS-CARD-001", "CardiovascularGeriatricRisks Medication #1", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-002", new BeersRiskEntry("BEERS-CARD-002", "CardiovascularGeriatricRisks Medication #2", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-003", new BeersRiskEntry("BEERS-CARD-003", "CardiovascularGeriatricRisks Medication #3", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-004", new BeersRiskEntry("BEERS-CARD-004", "CardiovascularGeriatricRisks Medication #4", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-005", new BeersRiskEntry("BEERS-CARD-005", "CardiovascularGeriatricRisks Medication #5", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-006", new BeersRiskEntry("BEERS-CARD-006", "CardiovascularGeriatricRisks Medication #6", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-007", new BeersRiskEntry("BEERS-CARD-007", "CardiovascularGeriatricRisks Medication #7", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-008", new BeersRiskEntry("BEERS-CARD-008", "CardiovascularGeriatricRisks Medication #8", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-009", new BeersRiskEntry("BEERS-CARD-009", "CardiovascularGeriatricRisks Medication #9", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-010", new BeersRiskEntry("BEERS-CARD-010", "CardiovascularGeriatricRisks Medication #10", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-011", new BeersRiskEntry("BEERS-CARD-011", "CardiovascularGeriatricRisks Medication #11", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-012", new BeersRiskEntry("BEERS-CARD-012", "CardiovascularGeriatricRisks Medication #12", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-013", new BeersRiskEntry("BEERS-CARD-013", "CardiovascularGeriatricRisks Medication #13", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-014", new BeersRiskEntry("BEERS-CARD-014", "CardiovascularGeriatricRisks Medication #14", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-015", new BeersRiskEntry("BEERS-CARD-015", "CardiovascularGeriatricRisks Medication #15", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-016", new BeersRiskEntry("BEERS-CARD-016", "CardiovascularGeriatricRisks Medication #16", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-017", new BeersRiskEntry("BEERS-CARD-017", "CardiovascularGeriatricRisks Medication #17", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-018", new BeersRiskEntry("BEERS-CARD-018", "CardiovascularGeriatricRisks Medication #18", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-019", new BeersRiskEntry("BEERS-CARD-019", "CardiovascularGeriatricRisks Medication #19", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-020", new BeersRiskEntry("BEERS-CARD-020", "CardiovascularGeriatricRisks Medication #20", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-021", new BeersRiskEntry("BEERS-CARD-021", "CardiovascularGeriatricRisks Medication #21", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-022", new BeersRiskEntry("BEERS-CARD-022", "CardiovascularGeriatricRisks Medication #22", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-023", new BeersRiskEntry("BEERS-CARD-023", "CardiovascularGeriatricRisks Medication #23", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-024", new BeersRiskEntry("BEERS-CARD-024", "CardiovascularGeriatricRisks Medication #24", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-025", new BeersRiskEntry("BEERS-CARD-025", "CardiovascularGeriatricRisks Medication #25", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-026", new BeersRiskEntry("BEERS-CARD-026", "CardiovascularGeriatricRisks Medication #26", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-027", new BeersRiskEntry("BEERS-CARD-027", "CardiovascularGeriatricRisks Medication #27", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-028", new BeersRiskEntry("BEERS-CARD-028", "CardiovascularGeriatricRisks Medication #28", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-029", new BeersRiskEntry("BEERS-CARD-029", "CardiovascularGeriatricRisks Medication #29", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-030", new BeersRiskEntry("BEERS-CARD-030", "CardiovascularGeriatricRisks Medication #30", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-031", new BeersRiskEntry("BEERS-CARD-031", "CardiovascularGeriatricRisks Medication #31", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-032", new BeersRiskEntry("BEERS-CARD-032", "CardiovascularGeriatricRisks Medication #32", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-033", new BeersRiskEntry("BEERS-CARD-033", "CardiovascularGeriatricRisks Medication #33", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-034", new BeersRiskEntry("BEERS-CARD-034", "CardiovascularGeriatricRisks Medication #34", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-035", new BeersRiskEntry("BEERS-CARD-035", "CardiovascularGeriatricRisks Medication #35", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-036", new BeersRiskEntry("BEERS-CARD-036", "CardiovascularGeriatricRisks Medication #36", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-037", new BeersRiskEntry("BEERS-CARD-037", "CardiovascularGeriatricRisks Medication #37", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-038", new BeersRiskEntry("BEERS-CARD-038", "CardiovascularGeriatricRisks Medication #38", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-039", new BeersRiskEntry("BEERS-CARD-039", "CardiovascularGeriatricRisks Medication #39", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-040", new BeersRiskEntry("BEERS-CARD-040", "CardiovascularGeriatricRisks Medication #40", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-041", new BeersRiskEntry("BEERS-CARD-041", "CardiovascularGeriatricRisks Medication #41", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-042", new BeersRiskEntry("BEERS-CARD-042", "CardiovascularGeriatricRisks Medication #42", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-043", new BeersRiskEntry("BEERS-CARD-043", "CardiovascularGeriatricRisks Medication #43", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-044", new BeersRiskEntry("BEERS-CARD-044", "CardiovascularGeriatricRisks Medication #44", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-045", new BeersRiskEntry("BEERS-CARD-045", "CardiovascularGeriatricRisks Medication #45", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-046", new BeersRiskEntry("BEERS-CARD-046", "CardiovascularGeriatricRisks Medication #46", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-047", new BeersRiskEntry("BEERS-CARD-047", "CardiovascularGeriatricRisks Medication #47", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-048", new BeersRiskEntry("BEERS-CARD-048", "CardiovascularGeriatricRisks Medication #48", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-049", new BeersRiskEntry("BEERS-CARD-049", "CardiovascularGeriatricRisks Medication #49", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-050", new BeersRiskEntry("BEERS-CARD-050", "CardiovascularGeriatricRisks Medication #50", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-051", new BeersRiskEntry("BEERS-CARD-051", "CardiovascularGeriatricRisks Medication #51", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-052", new BeersRiskEntry("BEERS-CARD-052", "CardiovascularGeriatricRisks Medication #52", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-053", new BeersRiskEntry("BEERS-CARD-053", "CardiovascularGeriatricRisks Medication #53", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-054", new BeersRiskEntry("BEERS-CARD-054", "CardiovascularGeriatricRisks Medication #54", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-055", new BeersRiskEntry("BEERS-CARD-055", "CardiovascularGeriatricRisks Medication #55", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-056", new BeersRiskEntry("BEERS-CARD-056", "CardiovascularGeriatricRisks Medication #56", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-057", new BeersRiskEntry("BEERS-CARD-057", "CardiovascularGeriatricRisks Medication #57", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-058", new BeersRiskEntry("BEERS-CARD-058", "CardiovascularGeriatricRisks Medication #58", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-059", new BeersRiskEntry("BEERS-CARD-059", "CardiovascularGeriatricRisks Medication #59", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-060", new BeersRiskEntry("BEERS-CARD-060", "CardiovascularGeriatricRisks Medication #60", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-061", new BeersRiskEntry("BEERS-CARD-061", "CardiovascularGeriatricRisks Medication #61", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-062", new BeersRiskEntry("BEERS-CARD-062", "CardiovascularGeriatricRisks Medication #62", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-063", new BeersRiskEntry("BEERS-CARD-063", "CardiovascularGeriatricRisks Medication #63", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-064", new BeersRiskEntry("BEERS-CARD-064", "CardiovascularGeriatricRisks Medication #64", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-065", new BeersRiskEntry("BEERS-CARD-065", "CardiovascularGeriatricRisks Medication #65", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-066", new BeersRiskEntry("BEERS-CARD-066", "CardiovascularGeriatricRisks Medication #66", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-067", new BeersRiskEntry("BEERS-CARD-067", "CardiovascularGeriatricRisks Medication #67", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-068", new BeersRiskEntry("BEERS-CARD-068", "CardiovascularGeriatricRisks Medication #68", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-069", new BeersRiskEntry("BEERS-CARD-069", "CardiovascularGeriatricRisks Medication #69", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-070", new BeersRiskEntry("BEERS-CARD-070", "CardiovascularGeriatricRisks Medication #70", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-071", new BeersRiskEntry("BEERS-CARD-071", "CardiovascularGeriatricRisks Medication #71", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-072", new BeersRiskEntry("BEERS-CARD-072", "CardiovascularGeriatricRisks Medication #72", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-073", new BeersRiskEntry("BEERS-CARD-073", "CardiovascularGeriatricRisks Medication #73", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-074", new BeersRiskEntry("BEERS-CARD-074", "CardiovascularGeriatricRisks Medication #74", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-075", new BeersRiskEntry("BEERS-CARD-075", "CardiovascularGeriatricRisks Medication #75", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-076", new BeersRiskEntry("BEERS-CARD-076", "CardiovascularGeriatricRisks Medication #76", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-077", new BeersRiskEntry("BEERS-CARD-077", "CardiovascularGeriatricRisks Medication #77", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-078", new BeersRiskEntry("BEERS-CARD-078", "CardiovascularGeriatricRisks Medication #78", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-079", new BeersRiskEntry("BEERS-CARD-079", "CardiovascularGeriatricRisks Medication #79", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-080", new BeersRiskEntry("BEERS-CARD-080", "CardiovascularGeriatricRisks Medication #80", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-081", new BeersRiskEntry("BEERS-CARD-081", "CardiovascularGeriatricRisks Medication #81", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-082", new BeersRiskEntry("BEERS-CARD-082", "CardiovascularGeriatricRisks Medication #82", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-083", new BeersRiskEntry("BEERS-CARD-083", "CardiovascularGeriatricRisks Medication #83", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-084", new BeersRiskEntry("BEERS-CARD-084", "CardiovascularGeriatricRisks Medication #84", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-085", new BeersRiskEntry("BEERS-CARD-085", "CardiovascularGeriatricRisks Medication #85", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-086", new BeersRiskEntry("BEERS-CARD-086", "CardiovascularGeriatricRisks Medication #86", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-087", new BeersRiskEntry("BEERS-CARD-087", "CardiovascularGeriatricRisks Medication #87", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-088", new BeersRiskEntry("BEERS-CARD-088", "CardiovascularGeriatricRisks Medication #88", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-089", new BeersRiskEntry("BEERS-CARD-089", "CardiovascularGeriatricRisks Medication #89", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-090", new BeersRiskEntry("BEERS-CARD-090", "CardiovascularGeriatricRisks Medication #90", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-091", new BeersRiskEntry("BEERS-CARD-091", "CardiovascularGeriatricRisks Medication #91", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-092", new BeersRiskEntry("BEERS-CARD-092", "CardiovascularGeriatricRisks Medication #92", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-093", new BeersRiskEntry("BEERS-CARD-093", "CardiovascularGeriatricRisks Medication #93", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-094", new BeersRiskEntry("BEERS-CARD-094", "CardiovascularGeriatricRisks Medication #94", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-095", new BeersRiskEntry("BEERS-CARD-095", "CardiovascularGeriatricRisks Medication #95", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-096", new BeersRiskEntry("BEERS-CARD-096", "CardiovascularGeriatricRisks Medication #96", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-097", new BeersRiskEntry("BEERS-CARD-097", "CardiovascularGeriatricRisks Medication #97", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-098", new BeersRiskEntry("BEERS-CARD-098", "CardiovascularGeriatricRisks Medication #98", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-099", new BeersRiskEntry("BEERS-CARD-099", "CardiovascularGeriatricRisks Medication #99", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-100", new BeersRiskEntry("BEERS-CARD-100", "CardiovascularGeriatricRisks Medication #100", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-101", new BeersRiskEntry("BEERS-CARD-101", "CardiovascularGeriatricRisks Medication #101", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-102", new BeersRiskEntry("BEERS-CARD-102", "CardiovascularGeriatricRisks Medication #102", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-103", new BeersRiskEntry("BEERS-CARD-103", "CardiovascularGeriatricRisks Medication #103", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-104", new BeersRiskEntry("BEERS-CARD-104", "CardiovascularGeriatricRisks Medication #104", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-105", new BeersRiskEntry("BEERS-CARD-105", "CardiovascularGeriatricRisks Medication #105", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-106", new BeersRiskEntry("BEERS-CARD-106", "CardiovascularGeriatricRisks Medication #106", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-107", new BeersRiskEntry("BEERS-CARD-107", "CardiovascularGeriatricRisks Medication #107", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-108", new BeersRiskEntry("BEERS-CARD-108", "CardiovascularGeriatricRisks Medication #108", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-109", new BeersRiskEntry("BEERS-CARD-109", "CardiovascularGeriatricRisks Medication #109", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-110", new BeersRiskEntry("BEERS-CARD-110", "CardiovascularGeriatricRisks Medication #110", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-111", new BeersRiskEntry("BEERS-CARD-111", "CardiovascularGeriatricRisks Medication #111", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-112", new BeersRiskEntry("BEERS-CARD-112", "CardiovascularGeriatricRisks Medication #112", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-113", new BeersRiskEntry("BEERS-CARD-113", "CardiovascularGeriatricRisks Medication #113", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-114", new BeersRiskEntry("BEERS-CARD-114", "CardiovascularGeriatricRisks Medication #114", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-115", new BeersRiskEntry("BEERS-CARD-115", "CardiovascularGeriatricRisks Medication #115", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-116", new BeersRiskEntry("BEERS-CARD-116", "CardiovascularGeriatricRisks Medication #116", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-117", new BeersRiskEntry("BEERS-CARD-117", "CardiovascularGeriatricRisks Medication #117", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-118", new BeersRiskEntry("BEERS-CARD-118", "CardiovascularGeriatricRisks Medication #118", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-119", new BeersRiskEntry("BEERS-CARD-119", "CardiovascularGeriatricRisks Medication #119", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-120", new BeersRiskEntry("BEERS-CARD-120", "CardiovascularGeriatricRisks Medication #120", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-121", new BeersRiskEntry("BEERS-CARD-121", "CardiovascularGeriatricRisks Medication #121", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-122", new BeersRiskEntry("BEERS-CARD-122", "CardiovascularGeriatricRisks Medication #122", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-123", new BeersRiskEntry("BEERS-CARD-123", "CardiovascularGeriatricRisks Medication #123", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-124", new BeersRiskEntry("BEERS-CARD-124", "CardiovascularGeriatricRisks Medication #124", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-125", new BeersRiskEntry("BEERS-CARD-125", "CardiovascularGeriatricRisks Medication #125", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-126", new BeersRiskEntry("BEERS-CARD-126", "CardiovascularGeriatricRisks Medication #126", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-127", new BeersRiskEntry("BEERS-CARD-127", "CardiovascularGeriatricRisks Medication #127", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-128", new BeersRiskEntry("BEERS-CARD-128", "CardiovascularGeriatricRisks Medication #128", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-129", new BeersRiskEntry("BEERS-CARD-129", "CardiovascularGeriatricRisks Medication #129", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-130", new BeersRiskEntry("BEERS-CARD-130", "CardiovascularGeriatricRisks Medication #130", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-131", new BeersRiskEntry("BEERS-CARD-131", "CardiovascularGeriatricRisks Medication #131", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-132", new BeersRiskEntry("BEERS-CARD-132", "CardiovascularGeriatricRisks Medication #132", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-133", new BeersRiskEntry("BEERS-CARD-133", "CardiovascularGeriatricRisks Medication #133", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-134", new BeersRiskEntry("BEERS-CARD-134", "CardiovascularGeriatricRisks Medication #134", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-135", new BeersRiskEntry("BEERS-CARD-135", "CardiovascularGeriatricRisks Medication #135", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-136", new BeersRiskEntry("BEERS-CARD-136", "CardiovascularGeriatricRisks Medication #136", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-137", new BeersRiskEntry("BEERS-CARD-137", "CardiovascularGeriatricRisks Medication #137", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-138", new BeersRiskEntry("BEERS-CARD-138", "CardiovascularGeriatricRisks Medication #138", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-139", new BeersRiskEntry("BEERS-CARD-139", "CardiovascularGeriatricRisks Medication #139", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CARD-140", new BeersRiskEntry("BEERS-CARD-140", "CardiovascularGeriatricRisks Medication #140", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
    }

    public Optional<BeersRiskEntry> getByCode(String code) {
        return Optional.ofNullable(risks.get(code));
    }

    public List<BeersRiskEntry> getAllRisks() {
        return new ArrayList<>(risks.values());
    }
}
