package com.hospital.ontology.beers;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;
import java.util.*;

@Component
public class CentralNervousSystemGeriatricRisksDirectory {

    @Data
    @AllArgsConstructor
    public static class BeersRiskEntry {
        private String riskCode;
        private String medicationName;
        private String agsTier;
        private String rationale;
        private String recommendation;
    }

    private final Map<String, BeersRiskEntry> risks = new LinkedHashMap<>();

    public CentralNervousSystemGeriatricRisksDirectory() {
        initializeRisks();
    }

    private void initializeRisks() {
        risks.put("BEERS-CENT-001", new BeersRiskEntry("BEERS-CENT-001", "CentralNervousSystemGeriatricRisks Medication #1", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-002", new BeersRiskEntry("BEERS-CENT-002", "CentralNervousSystemGeriatricRisks Medication #2", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-003", new BeersRiskEntry("BEERS-CENT-003", "CentralNervousSystemGeriatricRisks Medication #3", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-004", new BeersRiskEntry("BEERS-CENT-004", "CentralNervousSystemGeriatricRisks Medication #4", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-005", new BeersRiskEntry("BEERS-CENT-005", "CentralNervousSystemGeriatricRisks Medication #5", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-006", new BeersRiskEntry("BEERS-CENT-006", "CentralNervousSystemGeriatricRisks Medication #6", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-007", new BeersRiskEntry("BEERS-CENT-007", "CentralNervousSystemGeriatricRisks Medication #7", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-008", new BeersRiskEntry("BEERS-CENT-008", "CentralNervousSystemGeriatricRisks Medication #8", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-009", new BeersRiskEntry("BEERS-CENT-009", "CentralNervousSystemGeriatricRisks Medication #9", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-010", new BeersRiskEntry("BEERS-CENT-010", "CentralNervousSystemGeriatricRisks Medication #10", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-011", new BeersRiskEntry("BEERS-CENT-011", "CentralNervousSystemGeriatricRisks Medication #11", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-012", new BeersRiskEntry("BEERS-CENT-012", "CentralNervousSystemGeriatricRisks Medication #12", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-013", new BeersRiskEntry("BEERS-CENT-013", "CentralNervousSystemGeriatricRisks Medication #13", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-014", new BeersRiskEntry("BEERS-CENT-014", "CentralNervousSystemGeriatricRisks Medication #14", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-015", new BeersRiskEntry("BEERS-CENT-015", "CentralNervousSystemGeriatricRisks Medication #15", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-016", new BeersRiskEntry("BEERS-CENT-016", "CentralNervousSystemGeriatricRisks Medication #16", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-017", new BeersRiskEntry("BEERS-CENT-017", "CentralNervousSystemGeriatricRisks Medication #17", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-018", new BeersRiskEntry("BEERS-CENT-018", "CentralNervousSystemGeriatricRisks Medication #18", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-019", new BeersRiskEntry("BEERS-CENT-019", "CentralNervousSystemGeriatricRisks Medication #19", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-020", new BeersRiskEntry("BEERS-CENT-020", "CentralNervousSystemGeriatricRisks Medication #20", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-021", new BeersRiskEntry("BEERS-CENT-021", "CentralNervousSystemGeriatricRisks Medication #21", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-022", new BeersRiskEntry("BEERS-CENT-022", "CentralNervousSystemGeriatricRisks Medication #22", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-023", new BeersRiskEntry("BEERS-CENT-023", "CentralNervousSystemGeriatricRisks Medication #23", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-024", new BeersRiskEntry("BEERS-CENT-024", "CentralNervousSystemGeriatricRisks Medication #24", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-025", new BeersRiskEntry("BEERS-CENT-025", "CentralNervousSystemGeriatricRisks Medication #25", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-026", new BeersRiskEntry("BEERS-CENT-026", "CentralNervousSystemGeriatricRisks Medication #26", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-027", new BeersRiskEntry("BEERS-CENT-027", "CentralNervousSystemGeriatricRisks Medication #27", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-028", new BeersRiskEntry("BEERS-CENT-028", "CentralNervousSystemGeriatricRisks Medication #28", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-029", new BeersRiskEntry("BEERS-CENT-029", "CentralNervousSystemGeriatricRisks Medication #29", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-030", new BeersRiskEntry("BEERS-CENT-030", "CentralNervousSystemGeriatricRisks Medication #30", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-031", new BeersRiskEntry("BEERS-CENT-031", "CentralNervousSystemGeriatricRisks Medication #31", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-032", new BeersRiskEntry("BEERS-CENT-032", "CentralNervousSystemGeriatricRisks Medication #32", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-033", new BeersRiskEntry("BEERS-CENT-033", "CentralNervousSystemGeriatricRisks Medication #33", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-034", new BeersRiskEntry("BEERS-CENT-034", "CentralNervousSystemGeriatricRisks Medication #34", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-035", new BeersRiskEntry("BEERS-CENT-035", "CentralNervousSystemGeriatricRisks Medication #35", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-036", new BeersRiskEntry("BEERS-CENT-036", "CentralNervousSystemGeriatricRisks Medication #36", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-037", new BeersRiskEntry("BEERS-CENT-037", "CentralNervousSystemGeriatricRisks Medication #37", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-038", new BeersRiskEntry("BEERS-CENT-038", "CentralNervousSystemGeriatricRisks Medication #38", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-039", new BeersRiskEntry("BEERS-CENT-039", "CentralNervousSystemGeriatricRisks Medication #39", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-040", new BeersRiskEntry("BEERS-CENT-040", "CentralNervousSystemGeriatricRisks Medication #40", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-041", new BeersRiskEntry("BEERS-CENT-041", "CentralNervousSystemGeriatricRisks Medication #41", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-042", new BeersRiskEntry("BEERS-CENT-042", "CentralNervousSystemGeriatricRisks Medication #42", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-043", new BeersRiskEntry("BEERS-CENT-043", "CentralNervousSystemGeriatricRisks Medication #43", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-044", new BeersRiskEntry("BEERS-CENT-044", "CentralNervousSystemGeriatricRisks Medication #44", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-045", new BeersRiskEntry("BEERS-CENT-045", "CentralNervousSystemGeriatricRisks Medication #45", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-046", new BeersRiskEntry("BEERS-CENT-046", "CentralNervousSystemGeriatricRisks Medication #46", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-047", new BeersRiskEntry("BEERS-CENT-047", "CentralNervousSystemGeriatricRisks Medication #47", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-048", new BeersRiskEntry("BEERS-CENT-048", "CentralNervousSystemGeriatricRisks Medication #48", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-049", new BeersRiskEntry("BEERS-CENT-049", "CentralNervousSystemGeriatricRisks Medication #49", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-050", new BeersRiskEntry("BEERS-CENT-050", "CentralNervousSystemGeriatricRisks Medication #50", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-051", new BeersRiskEntry("BEERS-CENT-051", "CentralNervousSystemGeriatricRisks Medication #51", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-052", new BeersRiskEntry("BEERS-CENT-052", "CentralNervousSystemGeriatricRisks Medication #52", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-053", new BeersRiskEntry("BEERS-CENT-053", "CentralNervousSystemGeriatricRisks Medication #53", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-054", new BeersRiskEntry("BEERS-CENT-054", "CentralNervousSystemGeriatricRisks Medication #54", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-055", new BeersRiskEntry("BEERS-CENT-055", "CentralNervousSystemGeriatricRisks Medication #55", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-056", new BeersRiskEntry("BEERS-CENT-056", "CentralNervousSystemGeriatricRisks Medication #56", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-057", new BeersRiskEntry("BEERS-CENT-057", "CentralNervousSystemGeriatricRisks Medication #57", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-058", new BeersRiskEntry("BEERS-CENT-058", "CentralNervousSystemGeriatricRisks Medication #58", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-059", new BeersRiskEntry("BEERS-CENT-059", "CentralNervousSystemGeriatricRisks Medication #59", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-060", new BeersRiskEntry("BEERS-CENT-060", "CentralNervousSystemGeriatricRisks Medication #60", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-061", new BeersRiskEntry("BEERS-CENT-061", "CentralNervousSystemGeriatricRisks Medication #61", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-062", new BeersRiskEntry("BEERS-CENT-062", "CentralNervousSystemGeriatricRisks Medication #62", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-063", new BeersRiskEntry("BEERS-CENT-063", "CentralNervousSystemGeriatricRisks Medication #63", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-064", new BeersRiskEntry("BEERS-CENT-064", "CentralNervousSystemGeriatricRisks Medication #64", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-065", new BeersRiskEntry("BEERS-CENT-065", "CentralNervousSystemGeriatricRisks Medication #65", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-066", new BeersRiskEntry("BEERS-CENT-066", "CentralNervousSystemGeriatricRisks Medication #66", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-067", new BeersRiskEntry("BEERS-CENT-067", "CentralNervousSystemGeriatricRisks Medication #67", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-068", new BeersRiskEntry("BEERS-CENT-068", "CentralNervousSystemGeriatricRisks Medication #68", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-069", new BeersRiskEntry("BEERS-CENT-069", "CentralNervousSystemGeriatricRisks Medication #69", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-070", new BeersRiskEntry("BEERS-CENT-070", "CentralNervousSystemGeriatricRisks Medication #70", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-071", new BeersRiskEntry("BEERS-CENT-071", "CentralNervousSystemGeriatricRisks Medication #71", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-072", new BeersRiskEntry("BEERS-CENT-072", "CentralNervousSystemGeriatricRisks Medication #72", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-073", new BeersRiskEntry("BEERS-CENT-073", "CentralNervousSystemGeriatricRisks Medication #73", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-074", new BeersRiskEntry("BEERS-CENT-074", "CentralNervousSystemGeriatricRisks Medication #74", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-075", new BeersRiskEntry("BEERS-CENT-075", "CentralNervousSystemGeriatricRisks Medication #75", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-076", new BeersRiskEntry("BEERS-CENT-076", "CentralNervousSystemGeriatricRisks Medication #76", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-077", new BeersRiskEntry("BEERS-CENT-077", "CentralNervousSystemGeriatricRisks Medication #77", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-078", new BeersRiskEntry("BEERS-CENT-078", "CentralNervousSystemGeriatricRisks Medication #78", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-079", new BeersRiskEntry("BEERS-CENT-079", "CentralNervousSystemGeriatricRisks Medication #79", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-080", new BeersRiskEntry("BEERS-CENT-080", "CentralNervousSystemGeriatricRisks Medication #80", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-081", new BeersRiskEntry("BEERS-CENT-081", "CentralNervousSystemGeriatricRisks Medication #81", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-082", new BeersRiskEntry("BEERS-CENT-082", "CentralNervousSystemGeriatricRisks Medication #82", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-083", new BeersRiskEntry("BEERS-CENT-083", "CentralNervousSystemGeriatricRisks Medication #83", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-084", new BeersRiskEntry("BEERS-CENT-084", "CentralNervousSystemGeriatricRisks Medication #84", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-085", new BeersRiskEntry("BEERS-CENT-085", "CentralNervousSystemGeriatricRisks Medication #85", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-086", new BeersRiskEntry("BEERS-CENT-086", "CentralNervousSystemGeriatricRisks Medication #86", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-087", new BeersRiskEntry("BEERS-CENT-087", "CentralNervousSystemGeriatricRisks Medication #87", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-088", new BeersRiskEntry("BEERS-CENT-088", "CentralNervousSystemGeriatricRisks Medication #88", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-089", new BeersRiskEntry("BEERS-CENT-089", "CentralNervousSystemGeriatricRisks Medication #89", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-090", new BeersRiskEntry("BEERS-CENT-090", "CentralNervousSystemGeriatricRisks Medication #90", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-091", new BeersRiskEntry("BEERS-CENT-091", "CentralNervousSystemGeriatricRisks Medication #91", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-092", new BeersRiskEntry("BEERS-CENT-092", "CentralNervousSystemGeriatricRisks Medication #92", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-093", new BeersRiskEntry("BEERS-CENT-093", "CentralNervousSystemGeriatricRisks Medication #93", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-094", new BeersRiskEntry("BEERS-CENT-094", "CentralNervousSystemGeriatricRisks Medication #94", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-095", new BeersRiskEntry("BEERS-CENT-095", "CentralNervousSystemGeriatricRisks Medication #95", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-096", new BeersRiskEntry("BEERS-CENT-096", "CentralNervousSystemGeriatricRisks Medication #96", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-097", new BeersRiskEntry("BEERS-CENT-097", "CentralNervousSystemGeriatricRisks Medication #97", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-098", new BeersRiskEntry("BEERS-CENT-098", "CentralNervousSystemGeriatricRisks Medication #98", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-099", new BeersRiskEntry("BEERS-CENT-099", "CentralNervousSystemGeriatricRisks Medication #99", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-100", new BeersRiskEntry("BEERS-CENT-100", "CentralNervousSystemGeriatricRisks Medication #100", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-101", new BeersRiskEntry("BEERS-CENT-101", "CentralNervousSystemGeriatricRisks Medication #101", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-102", new BeersRiskEntry("BEERS-CENT-102", "CentralNervousSystemGeriatricRisks Medication #102", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-103", new BeersRiskEntry("BEERS-CENT-103", "CentralNervousSystemGeriatricRisks Medication #103", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-104", new BeersRiskEntry("BEERS-CENT-104", "CentralNervousSystemGeriatricRisks Medication #104", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-105", new BeersRiskEntry("BEERS-CENT-105", "CentralNervousSystemGeriatricRisks Medication #105", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-106", new BeersRiskEntry("BEERS-CENT-106", "CentralNervousSystemGeriatricRisks Medication #106", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-107", new BeersRiskEntry("BEERS-CENT-107", "CentralNervousSystemGeriatricRisks Medication #107", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-108", new BeersRiskEntry("BEERS-CENT-108", "CentralNervousSystemGeriatricRisks Medication #108", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-109", new BeersRiskEntry("BEERS-CENT-109", "CentralNervousSystemGeriatricRisks Medication #109", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-110", new BeersRiskEntry("BEERS-CENT-110", "CentralNervousSystemGeriatricRisks Medication #110", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-111", new BeersRiskEntry("BEERS-CENT-111", "CentralNervousSystemGeriatricRisks Medication #111", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-112", new BeersRiskEntry("BEERS-CENT-112", "CentralNervousSystemGeriatricRisks Medication #112", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-113", new BeersRiskEntry("BEERS-CENT-113", "CentralNervousSystemGeriatricRisks Medication #113", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-114", new BeersRiskEntry("BEERS-CENT-114", "CentralNervousSystemGeriatricRisks Medication #114", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-115", new BeersRiskEntry("BEERS-CENT-115", "CentralNervousSystemGeriatricRisks Medication #115", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-116", new BeersRiskEntry("BEERS-CENT-116", "CentralNervousSystemGeriatricRisks Medication #116", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-117", new BeersRiskEntry("BEERS-CENT-117", "CentralNervousSystemGeriatricRisks Medication #117", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-118", new BeersRiskEntry("BEERS-CENT-118", "CentralNervousSystemGeriatricRisks Medication #118", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-119", new BeersRiskEntry("BEERS-CENT-119", "CentralNervousSystemGeriatricRisks Medication #119", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-120", new BeersRiskEntry("BEERS-CENT-120", "CentralNervousSystemGeriatricRisks Medication #120", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-121", new BeersRiskEntry("BEERS-CENT-121", "CentralNervousSystemGeriatricRisks Medication #121", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-122", new BeersRiskEntry("BEERS-CENT-122", "CentralNervousSystemGeriatricRisks Medication #122", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-123", new BeersRiskEntry("BEERS-CENT-123", "CentralNervousSystemGeriatricRisks Medication #123", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-124", new BeersRiskEntry("BEERS-CENT-124", "CentralNervousSystemGeriatricRisks Medication #124", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-125", new BeersRiskEntry("BEERS-CENT-125", "CentralNervousSystemGeriatricRisks Medication #125", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-126", new BeersRiskEntry("BEERS-CENT-126", "CentralNervousSystemGeriatricRisks Medication #126", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-127", new BeersRiskEntry("BEERS-CENT-127", "CentralNervousSystemGeriatricRisks Medication #127", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-128", new BeersRiskEntry("BEERS-CENT-128", "CentralNervousSystemGeriatricRisks Medication #128", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-129", new BeersRiskEntry("BEERS-CENT-129", "CentralNervousSystemGeriatricRisks Medication #129", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-130", new BeersRiskEntry("BEERS-CENT-130", "CentralNervousSystemGeriatricRisks Medication #130", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-131", new BeersRiskEntry("BEERS-CENT-131", "CentralNervousSystemGeriatricRisks Medication #131", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-132", new BeersRiskEntry("BEERS-CENT-132", "CentralNervousSystemGeriatricRisks Medication #132", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-133", new BeersRiskEntry("BEERS-CENT-133", "CentralNervousSystemGeriatricRisks Medication #133", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-134", new BeersRiskEntry("BEERS-CENT-134", "CentralNervousSystemGeriatricRisks Medication #134", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-135", new BeersRiskEntry("BEERS-CENT-135", "CentralNervousSystemGeriatricRisks Medication #135", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-136", new BeersRiskEntry("BEERS-CENT-136", "CentralNervousSystemGeriatricRisks Medication #136", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-137", new BeersRiskEntry("BEERS-CENT-137", "CentralNervousSystemGeriatricRisks Medication #137", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-138", new BeersRiskEntry("BEERS-CENT-138", "CentralNervousSystemGeriatricRisks Medication #138", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-139", new BeersRiskEntry("BEERS-CENT-139", "CentralNervousSystemGeriatricRisks Medication #139", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-CENT-140", new BeersRiskEntry("BEERS-CENT-140", "CentralNervousSystemGeriatricRisks Medication #140", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
    }

    public Optional<BeersRiskEntry> getByCode(String code) {
        return Optional.ofNullable(risks.get(code));
    }

    public List<BeersRiskEntry> getAllRisks() {
        return new ArrayList<>(risks.values());
    }
}
