package com.hospital.ontology.beers;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;
import java.util.*;

@Component
public class EndocrineGeriatricRisksDirectory {

    @Data
    @AllArgsConstructor
    public static class BeersRiskEntry {
        private String riskCode;
        private String medicationName;
        private String agsTier;
        private String rationale;
        private String recommendation;
    }

    private final Map<String, BeersRiskEntry> risks = new LinkedHashMap<>();

    public EndocrineGeriatricRisksDirectory() {
        initializeRisks();
    }

    private void initializeRisks() {
        risks.put("BEERS-ENDO-001", new BeersRiskEntry("BEERS-ENDO-001", "EndocrineGeriatricRisks Medication #1", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-002", new BeersRiskEntry("BEERS-ENDO-002", "EndocrineGeriatricRisks Medication #2", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-003", new BeersRiskEntry("BEERS-ENDO-003", "EndocrineGeriatricRisks Medication #3", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-004", new BeersRiskEntry("BEERS-ENDO-004", "EndocrineGeriatricRisks Medication #4", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-005", new BeersRiskEntry("BEERS-ENDO-005", "EndocrineGeriatricRisks Medication #5", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-006", new BeersRiskEntry("BEERS-ENDO-006", "EndocrineGeriatricRisks Medication #6", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-007", new BeersRiskEntry("BEERS-ENDO-007", "EndocrineGeriatricRisks Medication #7", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-008", new BeersRiskEntry("BEERS-ENDO-008", "EndocrineGeriatricRisks Medication #8", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-009", new BeersRiskEntry("BEERS-ENDO-009", "EndocrineGeriatricRisks Medication #9", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-010", new BeersRiskEntry("BEERS-ENDO-010", "EndocrineGeriatricRisks Medication #10", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-011", new BeersRiskEntry("BEERS-ENDO-011", "EndocrineGeriatricRisks Medication #11", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-012", new BeersRiskEntry("BEERS-ENDO-012", "EndocrineGeriatricRisks Medication #12", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-013", new BeersRiskEntry("BEERS-ENDO-013", "EndocrineGeriatricRisks Medication #13", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-014", new BeersRiskEntry("BEERS-ENDO-014", "EndocrineGeriatricRisks Medication #14", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-015", new BeersRiskEntry("BEERS-ENDO-015", "EndocrineGeriatricRisks Medication #15", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-016", new BeersRiskEntry("BEERS-ENDO-016", "EndocrineGeriatricRisks Medication #16", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-017", new BeersRiskEntry("BEERS-ENDO-017", "EndocrineGeriatricRisks Medication #17", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-018", new BeersRiskEntry("BEERS-ENDO-018", "EndocrineGeriatricRisks Medication #18", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-019", new BeersRiskEntry("BEERS-ENDO-019", "EndocrineGeriatricRisks Medication #19", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-020", new BeersRiskEntry("BEERS-ENDO-020", "EndocrineGeriatricRisks Medication #20", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-021", new BeersRiskEntry("BEERS-ENDO-021", "EndocrineGeriatricRisks Medication #21", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-022", new BeersRiskEntry("BEERS-ENDO-022", "EndocrineGeriatricRisks Medication #22", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-023", new BeersRiskEntry("BEERS-ENDO-023", "EndocrineGeriatricRisks Medication #23", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-024", new BeersRiskEntry("BEERS-ENDO-024", "EndocrineGeriatricRisks Medication #24", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-025", new BeersRiskEntry("BEERS-ENDO-025", "EndocrineGeriatricRisks Medication #25", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-026", new BeersRiskEntry("BEERS-ENDO-026", "EndocrineGeriatricRisks Medication #26", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-027", new BeersRiskEntry("BEERS-ENDO-027", "EndocrineGeriatricRisks Medication #27", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-028", new BeersRiskEntry("BEERS-ENDO-028", "EndocrineGeriatricRisks Medication #28", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-029", new BeersRiskEntry("BEERS-ENDO-029", "EndocrineGeriatricRisks Medication #29", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-030", new BeersRiskEntry("BEERS-ENDO-030", "EndocrineGeriatricRisks Medication #30", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-031", new BeersRiskEntry("BEERS-ENDO-031", "EndocrineGeriatricRisks Medication #31", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-032", new BeersRiskEntry("BEERS-ENDO-032", "EndocrineGeriatricRisks Medication #32", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-033", new BeersRiskEntry("BEERS-ENDO-033", "EndocrineGeriatricRisks Medication #33", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-034", new BeersRiskEntry("BEERS-ENDO-034", "EndocrineGeriatricRisks Medication #34", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-035", new BeersRiskEntry("BEERS-ENDO-035", "EndocrineGeriatricRisks Medication #35", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-036", new BeersRiskEntry("BEERS-ENDO-036", "EndocrineGeriatricRisks Medication #36", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-037", new BeersRiskEntry("BEERS-ENDO-037", "EndocrineGeriatricRisks Medication #37", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-038", new BeersRiskEntry("BEERS-ENDO-038", "EndocrineGeriatricRisks Medication #38", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-039", new BeersRiskEntry("BEERS-ENDO-039", "EndocrineGeriatricRisks Medication #39", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-040", new BeersRiskEntry("BEERS-ENDO-040", "EndocrineGeriatricRisks Medication #40", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-041", new BeersRiskEntry("BEERS-ENDO-041", "EndocrineGeriatricRisks Medication #41", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-042", new BeersRiskEntry("BEERS-ENDO-042", "EndocrineGeriatricRisks Medication #42", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-043", new BeersRiskEntry("BEERS-ENDO-043", "EndocrineGeriatricRisks Medication #43", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-044", new BeersRiskEntry("BEERS-ENDO-044", "EndocrineGeriatricRisks Medication #44", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-045", new BeersRiskEntry("BEERS-ENDO-045", "EndocrineGeriatricRisks Medication #45", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-046", new BeersRiskEntry("BEERS-ENDO-046", "EndocrineGeriatricRisks Medication #46", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-047", new BeersRiskEntry("BEERS-ENDO-047", "EndocrineGeriatricRisks Medication #47", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-048", new BeersRiskEntry("BEERS-ENDO-048", "EndocrineGeriatricRisks Medication #48", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-049", new BeersRiskEntry("BEERS-ENDO-049", "EndocrineGeriatricRisks Medication #49", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-050", new BeersRiskEntry("BEERS-ENDO-050", "EndocrineGeriatricRisks Medication #50", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-051", new BeersRiskEntry("BEERS-ENDO-051", "EndocrineGeriatricRisks Medication #51", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-052", new BeersRiskEntry("BEERS-ENDO-052", "EndocrineGeriatricRisks Medication #52", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-053", new BeersRiskEntry("BEERS-ENDO-053", "EndocrineGeriatricRisks Medication #53", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-054", new BeersRiskEntry("BEERS-ENDO-054", "EndocrineGeriatricRisks Medication #54", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-055", new BeersRiskEntry("BEERS-ENDO-055", "EndocrineGeriatricRisks Medication #55", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-056", new BeersRiskEntry("BEERS-ENDO-056", "EndocrineGeriatricRisks Medication #56", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-057", new BeersRiskEntry("BEERS-ENDO-057", "EndocrineGeriatricRisks Medication #57", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-058", new BeersRiskEntry("BEERS-ENDO-058", "EndocrineGeriatricRisks Medication #58", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-059", new BeersRiskEntry("BEERS-ENDO-059", "EndocrineGeriatricRisks Medication #59", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-060", new BeersRiskEntry("BEERS-ENDO-060", "EndocrineGeriatricRisks Medication #60", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-061", new BeersRiskEntry("BEERS-ENDO-061", "EndocrineGeriatricRisks Medication #61", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-062", new BeersRiskEntry("BEERS-ENDO-062", "EndocrineGeriatricRisks Medication #62", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-063", new BeersRiskEntry("BEERS-ENDO-063", "EndocrineGeriatricRisks Medication #63", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-064", new BeersRiskEntry("BEERS-ENDO-064", "EndocrineGeriatricRisks Medication #64", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-065", new BeersRiskEntry("BEERS-ENDO-065", "EndocrineGeriatricRisks Medication #65", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-066", new BeersRiskEntry("BEERS-ENDO-066", "EndocrineGeriatricRisks Medication #66", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-067", new BeersRiskEntry("BEERS-ENDO-067", "EndocrineGeriatricRisks Medication #67", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-068", new BeersRiskEntry("BEERS-ENDO-068", "EndocrineGeriatricRisks Medication #68", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-069", new BeersRiskEntry("BEERS-ENDO-069", "EndocrineGeriatricRisks Medication #69", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-070", new BeersRiskEntry("BEERS-ENDO-070", "EndocrineGeriatricRisks Medication #70", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-071", new BeersRiskEntry("BEERS-ENDO-071", "EndocrineGeriatricRisks Medication #71", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-072", new BeersRiskEntry("BEERS-ENDO-072", "EndocrineGeriatricRisks Medication #72", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-073", new BeersRiskEntry("BEERS-ENDO-073", "EndocrineGeriatricRisks Medication #73", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-074", new BeersRiskEntry("BEERS-ENDO-074", "EndocrineGeriatricRisks Medication #74", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-075", new BeersRiskEntry("BEERS-ENDO-075", "EndocrineGeriatricRisks Medication #75", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-076", new BeersRiskEntry("BEERS-ENDO-076", "EndocrineGeriatricRisks Medication #76", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-077", new BeersRiskEntry("BEERS-ENDO-077", "EndocrineGeriatricRisks Medication #77", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-078", new BeersRiskEntry("BEERS-ENDO-078", "EndocrineGeriatricRisks Medication #78", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-079", new BeersRiskEntry("BEERS-ENDO-079", "EndocrineGeriatricRisks Medication #79", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-080", new BeersRiskEntry("BEERS-ENDO-080", "EndocrineGeriatricRisks Medication #80", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-081", new BeersRiskEntry("BEERS-ENDO-081", "EndocrineGeriatricRisks Medication #81", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-082", new BeersRiskEntry("BEERS-ENDO-082", "EndocrineGeriatricRisks Medication #82", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-083", new BeersRiskEntry("BEERS-ENDO-083", "EndocrineGeriatricRisks Medication #83", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-084", new BeersRiskEntry("BEERS-ENDO-084", "EndocrineGeriatricRisks Medication #84", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-085", new BeersRiskEntry("BEERS-ENDO-085", "EndocrineGeriatricRisks Medication #85", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-086", new BeersRiskEntry("BEERS-ENDO-086", "EndocrineGeriatricRisks Medication #86", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-087", new BeersRiskEntry("BEERS-ENDO-087", "EndocrineGeriatricRisks Medication #87", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-088", new BeersRiskEntry("BEERS-ENDO-088", "EndocrineGeriatricRisks Medication #88", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-089", new BeersRiskEntry("BEERS-ENDO-089", "EndocrineGeriatricRisks Medication #89", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-090", new BeersRiskEntry("BEERS-ENDO-090", "EndocrineGeriatricRisks Medication #90", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-091", new BeersRiskEntry("BEERS-ENDO-091", "EndocrineGeriatricRisks Medication #91", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-092", new BeersRiskEntry("BEERS-ENDO-092", "EndocrineGeriatricRisks Medication #92", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-093", new BeersRiskEntry("BEERS-ENDO-093", "EndocrineGeriatricRisks Medication #93", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-094", new BeersRiskEntry("BEERS-ENDO-094", "EndocrineGeriatricRisks Medication #94", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-095", new BeersRiskEntry("BEERS-ENDO-095", "EndocrineGeriatricRisks Medication #95", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-096", new BeersRiskEntry("BEERS-ENDO-096", "EndocrineGeriatricRisks Medication #96", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-097", new BeersRiskEntry("BEERS-ENDO-097", "EndocrineGeriatricRisks Medication #97", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-098", new BeersRiskEntry("BEERS-ENDO-098", "EndocrineGeriatricRisks Medication #98", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-099", new BeersRiskEntry("BEERS-ENDO-099", "EndocrineGeriatricRisks Medication #99", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-100", new BeersRiskEntry("BEERS-ENDO-100", "EndocrineGeriatricRisks Medication #100", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-101", new BeersRiskEntry("BEERS-ENDO-101", "EndocrineGeriatricRisks Medication #101", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-102", new BeersRiskEntry("BEERS-ENDO-102", "EndocrineGeriatricRisks Medication #102", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-103", new BeersRiskEntry("BEERS-ENDO-103", "EndocrineGeriatricRisks Medication #103", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-104", new BeersRiskEntry("BEERS-ENDO-104", "EndocrineGeriatricRisks Medication #104", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-105", new BeersRiskEntry("BEERS-ENDO-105", "EndocrineGeriatricRisks Medication #105", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-106", new BeersRiskEntry("BEERS-ENDO-106", "EndocrineGeriatricRisks Medication #106", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-107", new BeersRiskEntry("BEERS-ENDO-107", "EndocrineGeriatricRisks Medication #107", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-108", new BeersRiskEntry("BEERS-ENDO-108", "EndocrineGeriatricRisks Medication #108", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-109", new BeersRiskEntry("BEERS-ENDO-109", "EndocrineGeriatricRisks Medication #109", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-110", new BeersRiskEntry("BEERS-ENDO-110", "EndocrineGeriatricRisks Medication #110", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-111", new BeersRiskEntry("BEERS-ENDO-111", "EndocrineGeriatricRisks Medication #111", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-112", new BeersRiskEntry("BEERS-ENDO-112", "EndocrineGeriatricRisks Medication #112", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-113", new BeersRiskEntry("BEERS-ENDO-113", "EndocrineGeriatricRisks Medication #113", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-114", new BeersRiskEntry("BEERS-ENDO-114", "EndocrineGeriatricRisks Medication #114", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-115", new BeersRiskEntry("BEERS-ENDO-115", "EndocrineGeriatricRisks Medication #115", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-116", new BeersRiskEntry("BEERS-ENDO-116", "EndocrineGeriatricRisks Medication #116", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-117", new BeersRiskEntry("BEERS-ENDO-117", "EndocrineGeriatricRisks Medication #117", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-118", new BeersRiskEntry("BEERS-ENDO-118", "EndocrineGeriatricRisks Medication #118", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-119", new BeersRiskEntry("BEERS-ENDO-119", "EndocrineGeriatricRisks Medication #119", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-120", new BeersRiskEntry("BEERS-ENDO-120", "EndocrineGeriatricRisks Medication #120", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-121", new BeersRiskEntry("BEERS-ENDO-121", "EndocrineGeriatricRisks Medication #121", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-122", new BeersRiskEntry("BEERS-ENDO-122", "EndocrineGeriatricRisks Medication #122", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-123", new BeersRiskEntry("BEERS-ENDO-123", "EndocrineGeriatricRisks Medication #123", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-124", new BeersRiskEntry("BEERS-ENDO-124", "EndocrineGeriatricRisks Medication #124", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-125", new BeersRiskEntry("BEERS-ENDO-125", "EndocrineGeriatricRisks Medication #125", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-126", new BeersRiskEntry("BEERS-ENDO-126", "EndocrineGeriatricRisks Medication #126", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-127", new BeersRiskEntry("BEERS-ENDO-127", "EndocrineGeriatricRisks Medication #127", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-128", new BeersRiskEntry("BEERS-ENDO-128", "EndocrineGeriatricRisks Medication #128", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-129", new BeersRiskEntry("BEERS-ENDO-129", "EndocrineGeriatricRisks Medication #129", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-130", new BeersRiskEntry("BEERS-ENDO-130", "EndocrineGeriatricRisks Medication #130", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-131", new BeersRiskEntry("BEERS-ENDO-131", "EndocrineGeriatricRisks Medication #131", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-132", new BeersRiskEntry("BEERS-ENDO-132", "EndocrineGeriatricRisks Medication #132", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-133", new BeersRiskEntry("BEERS-ENDO-133", "EndocrineGeriatricRisks Medication #133", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-134", new BeersRiskEntry("BEERS-ENDO-134", "EndocrineGeriatricRisks Medication #134", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-135", new BeersRiskEntry("BEERS-ENDO-135", "EndocrineGeriatricRisks Medication #135", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-136", new BeersRiskEntry("BEERS-ENDO-136", "EndocrineGeriatricRisks Medication #136", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-137", new BeersRiskEntry("BEERS-ENDO-137", "EndocrineGeriatricRisks Medication #137", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-138", new BeersRiskEntry("BEERS-ENDO-138", "EndocrineGeriatricRisks Medication #138", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-139", new BeersRiskEntry("BEERS-ENDO-139", "EndocrineGeriatricRisks Medication #139", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-ENDO-140", new BeersRiskEntry("BEERS-ENDO-140", "EndocrineGeriatricRisks Medication #140", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
    }

    public Optional<BeersRiskEntry> getByCode(String code) {
        return Optional.ofNullable(risks.get(code));
    }

    public List<BeersRiskEntry> getAllRisks() {
        return new ArrayList<>(risks.values());
    }
}
