package com.hospital.ontology.beers;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.stereotype.Component;
import java.util.*;

@Component
public class PainAndNsaidGeriatricRisksDirectory {

    @Data
    @AllArgsConstructor
    public static class BeersRiskEntry {
        private String riskCode;
        private String medicationName;
        private String agsTier;
        private String rationale;
        private String recommendation;
    }

    private final Map<String, BeersRiskEntry> risks = new LinkedHashMap<>();

    public PainAndNsaidGeriatricRisksDirectory() {
        initializeRisks();
    }

    private void initializeRisks() {
        risks.put("BEERS-PAIN-001", new BeersRiskEntry("BEERS-PAIN-001", "PainAndNsaidGeriatricRisks Medication #1", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-002", new BeersRiskEntry("BEERS-PAIN-002", "PainAndNsaidGeriatricRisks Medication #2", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-003", new BeersRiskEntry("BEERS-PAIN-003", "PainAndNsaidGeriatricRisks Medication #3", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-004", new BeersRiskEntry("BEERS-PAIN-004", "PainAndNsaidGeriatricRisks Medication #4", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-005", new BeersRiskEntry("BEERS-PAIN-005", "PainAndNsaidGeriatricRisks Medication #5", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-006", new BeersRiskEntry("BEERS-PAIN-006", "PainAndNsaidGeriatricRisks Medication #6", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-007", new BeersRiskEntry("BEERS-PAIN-007", "PainAndNsaidGeriatricRisks Medication #7", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-008", new BeersRiskEntry("BEERS-PAIN-008", "PainAndNsaidGeriatricRisks Medication #8", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-009", new BeersRiskEntry("BEERS-PAIN-009", "PainAndNsaidGeriatricRisks Medication #9", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-010", new BeersRiskEntry("BEERS-PAIN-010", "PainAndNsaidGeriatricRisks Medication #10", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-011", new BeersRiskEntry("BEERS-PAIN-011", "PainAndNsaidGeriatricRisks Medication #11", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-012", new BeersRiskEntry("BEERS-PAIN-012", "PainAndNsaidGeriatricRisks Medication #12", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-013", new BeersRiskEntry("BEERS-PAIN-013", "PainAndNsaidGeriatricRisks Medication #13", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-014", new BeersRiskEntry("BEERS-PAIN-014", "PainAndNsaidGeriatricRisks Medication #14", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-015", new BeersRiskEntry("BEERS-PAIN-015", "PainAndNsaidGeriatricRisks Medication #15", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-016", new BeersRiskEntry("BEERS-PAIN-016", "PainAndNsaidGeriatricRisks Medication #16", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-017", new BeersRiskEntry("BEERS-PAIN-017", "PainAndNsaidGeriatricRisks Medication #17", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-018", new BeersRiskEntry("BEERS-PAIN-018", "PainAndNsaidGeriatricRisks Medication #18", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-019", new BeersRiskEntry("BEERS-PAIN-019", "PainAndNsaidGeriatricRisks Medication #19", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-020", new BeersRiskEntry("BEERS-PAIN-020", "PainAndNsaidGeriatricRisks Medication #20", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-021", new BeersRiskEntry("BEERS-PAIN-021", "PainAndNsaidGeriatricRisks Medication #21", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-022", new BeersRiskEntry("BEERS-PAIN-022", "PainAndNsaidGeriatricRisks Medication #22", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-023", new BeersRiskEntry("BEERS-PAIN-023", "PainAndNsaidGeriatricRisks Medication #23", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-024", new BeersRiskEntry("BEERS-PAIN-024", "PainAndNsaidGeriatricRisks Medication #24", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-025", new BeersRiskEntry("BEERS-PAIN-025", "PainAndNsaidGeriatricRisks Medication #25", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-026", new BeersRiskEntry("BEERS-PAIN-026", "PainAndNsaidGeriatricRisks Medication #26", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-027", new BeersRiskEntry("BEERS-PAIN-027", "PainAndNsaidGeriatricRisks Medication #27", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-028", new BeersRiskEntry("BEERS-PAIN-028", "PainAndNsaidGeriatricRisks Medication #28", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-029", new BeersRiskEntry("BEERS-PAIN-029", "PainAndNsaidGeriatricRisks Medication #29", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-030", new BeersRiskEntry("BEERS-PAIN-030", "PainAndNsaidGeriatricRisks Medication #30", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-031", new BeersRiskEntry("BEERS-PAIN-031", "PainAndNsaidGeriatricRisks Medication #31", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-032", new BeersRiskEntry("BEERS-PAIN-032", "PainAndNsaidGeriatricRisks Medication #32", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-033", new BeersRiskEntry("BEERS-PAIN-033", "PainAndNsaidGeriatricRisks Medication #33", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-034", new BeersRiskEntry("BEERS-PAIN-034", "PainAndNsaidGeriatricRisks Medication #34", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-035", new BeersRiskEntry("BEERS-PAIN-035", "PainAndNsaidGeriatricRisks Medication #35", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-036", new BeersRiskEntry("BEERS-PAIN-036", "PainAndNsaidGeriatricRisks Medication #36", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-037", new BeersRiskEntry("BEERS-PAIN-037", "PainAndNsaidGeriatricRisks Medication #37", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-038", new BeersRiskEntry("BEERS-PAIN-038", "PainAndNsaidGeriatricRisks Medication #38", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-039", new BeersRiskEntry("BEERS-PAIN-039", "PainAndNsaidGeriatricRisks Medication #39", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-040", new BeersRiskEntry("BEERS-PAIN-040", "PainAndNsaidGeriatricRisks Medication #40", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-041", new BeersRiskEntry("BEERS-PAIN-041", "PainAndNsaidGeriatricRisks Medication #41", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-042", new BeersRiskEntry("BEERS-PAIN-042", "PainAndNsaidGeriatricRisks Medication #42", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-043", new BeersRiskEntry("BEERS-PAIN-043", "PainAndNsaidGeriatricRisks Medication #43", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-044", new BeersRiskEntry("BEERS-PAIN-044", "PainAndNsaidGeriatricRisks Medication #44", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-045", new BeersRiskEntry("BEERS-PAIN-045", "PainAndNsaidGeriatricRisks Medication #45", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-046", new BeersRiskEntry("BEERS-PAIN-046", "PainAndNsaidGeriatricRisks Medication #46", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-047", new BeersRiskEntry("BEERS-PAIN-047", "PainAndNsaidGeriatricRisks Medication #47", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-048", new BeersRiskEntry("BEERS-PAIN-048", "PainAndNsaidGeriatricRisks Medication #48", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-049", new BeersRiskEntry("BEERS-PAIN-049", "PainAndNsaidGeriatricRisks Medication #49", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-050", new BeersRiskEntry("BEERS-PAIN-050", "PainAndNsaidGeriatricRisks Medication #50", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-051", new BeersRiskEntry("BEERS-PAIN-051", "PainAndNsaidGeriatricRisks Medication #51", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-052", new BeersRiskEntry("BEERS-PAIN-052", "PainAndNsaidGeriatricRisks Medication #52", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-053", new BeersRiskEntry("BEERS-PAIN-053", "PainAndNsaidGeriatricRisks Medication #53", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-054", new BeersRiskEntry("BEERS-PAIN-054", "PainAndNsaidGeriatricRisks Medication #54", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-055", new BeersRiskEntry("BEERS-PAIN-055", "PainAndNsaidGeriatricRisks Medication #55", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-056", new BeersRiskEntry("BEERS-PAIN-056", "PainAndNsaidGeriatricRisks Medication #56", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-057", new BeersRiskEntry("BEERS-PAIN-057", "PainAndNsaidGeriatricRisks Medication #57", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-058", new BeersRiskEntry("BEERS-PAIN-058", "PainAndNsaidGeriatricRisks Medication #58", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-059", new BeersRiskEntry("BEERS-PAIN-059", "PainAndNsaidGeriatricRisks Medication #59", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-060", new BeersRiskEntry("BEERS-PAIN-060", "PainAndNsaidGeriatricRisks Medication #60", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-061", new BeersRiskEntry("BEERS-PAIN-061", "PainAndNsaidGeriatricRisks Medication #61", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-062", new BeersRiskEntry("BEERS-PAIN-062", "PainAndNsaidGeriatricRisks Medication #62", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-063", new BeersRiskEntry("BEERS-PAIN-063", "PainAndNsaidGeriatricRisks Medication #63", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-064", new BeersRiskEntry("BEERS-PAIN-064", "PainAndNsaidGeriatricRisks Medication #64", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-065", new BeersRiskEntry("BEERS-PAIN-065", "PainAndNsaidGeriatricRisks Medication #65", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-066", new BeersRiskEntry("BEERS-PAIN-066", "PainAndNsaidGeriatricRisks Medication #66", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-067", new BeersRiskEntry("BEERS-PAIN-067", "PainAndNsaidGeriatricRisks Medication #67", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-068", new BeersRiskEntry("BEERS-PAIN-068", "PainAndNsaidGeriatricRisks Medication #68", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-069", new BeersRiskEntry("BEERS-PAIN-069", "PainAndNsaidGeriatricRisks Medication #69", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-070", new BeersRiskEntry("BEERS-PAIN-070", "PainAndNsaidGeriatricRisks Medication #70", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-071", new BeersRiskEntry("BEERS-PAIN-071", "PainAndNsaidGeriatricRisks Medication #71", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-072", new BeersRiskEntry("BEERS-PAIN-072", "PainAndNsaidGeriatricRisks Medication #72", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-073", new BeersRiskEntry("BEERS-PAIN-073", "PainAndNsaidGeriatricRisks Medication #73", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-074", new BeersRiskEntry("BEERS-PAIN-074", "PainAndNsaidGeriatricRisks Medication #74", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-075", new BeersRiskEntry("BEERS-PAIN-075", "PainAndNsaidGeriatricRisks Medication #75", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-076", new BeersRiskEntry("BEERS-PAIN-076", "PainAndNsaidGeriatricRisks Medication #76", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-077", new BeersRiskEntry("BEERS-PAIN-077", "PainAndNsaidGeriatricRisks Medication #77", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-078", new BeersRiskEntry("BEERS-PAIN-078", "PainAndNsaidGeriatricRisks Medication #78", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-079", new BeersRiskEntry("BEERS-PAIN-079", "PainAndNsaidGeriatricRisks Medication #79", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-080", new BeersRiskEntry("BEERS-PAIN-080", "PainAndNsaidGeriatricRisks Medication #80", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-081", new BeersRiskEntry("BEERS-PAIN-081", "PainAndNsaidGeriatricRisks Medication #81", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-082", new BeersRiskEntry("BEERS-PAIN-082", "PainAndNsaidGeriatricRisks Medication #82", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-083", new BeersRiskEntry("BEERS-PAIN-083", "PainAndNsaidGeriatricRisks Medication #83", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-084", new BeersRiskEntry("BEERS-PAIN-084", "PainAndNsaidGeriatricRisks Medication #84", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-085", new BeersRiskEntry("BEERS-PAIN-085", "PainAndNsaidGeriatricRisks Medication #85", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-086", new BeersRiskEntry("BEERS-PAIN-086", "PainAndNsaidGeriatricRisks Medication #86", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-087", new BeersRiskEntry("BEERS-PAIN-087", "PainAndNsaidGeriatricRisks Medication #87", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-088", new BeersRiskEntry("BEERS-PAIN-088", "PainAndNsaidGeriatricRisks Medication #88", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-089", new BeersRiskEntry("BEERS-PAIN-089", "PainAndNsaidGeriatricRisks Medication #89", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-090", new BeersRiskEntry("BEERS-PAIN-090", "PainAndNsaidGeriatricRisks Medication #90", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-091", new BeersRiskEntry("BEERS-PAIN-091", "PainAndNsaidGeriatricRisks Medication #91", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-092", new BeersRiskEntry("BEERS-PAIN-092", "PainAndNsaidGeriatricRisks Medication #92", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-093", new BeersRiskEntry("BEERS-PAIN-093", "PainAndNsaidGeriatricRisks Medication #93", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-094", new BeersRiskEntry("BEERS-PAIN-094", "PainAndNsaidGeriatricRisks Medication #94", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-095", new BeersRiskEntry("BEERS-PAIN-095", "PainAndNsaidGeriatricRisks Medication #95", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-096", new BeersRiskEntry("BEERS-PAIN-096", "PainAndNsaidGeriatricRisks Medication #96", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-097", new BeersRiskEntry("BEERS-PAIN-097", "PainAndNsaidGeriatricRisks Medication #97", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-098", new BeersRiskEntry("BEERS-PAIN-098", "PainAndNsaidGeriatricRisks Medication #98", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-099", new BeersRiskEntry("BEERS-PAIN-099", "PainAndNsaidGeriatricRisks Medication #99", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-100", new BeersRiskEntry("BEERS-PAIN-100", "PainAndNsaidGeriatricRisks Medication #100", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-101", new BeersRiskEntry("BEERS-PAIN-101", "PainAndNsaidGeriatricRisks Medication #101", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-102", new BeersRiskEntry("BEERS-PAIN-102", "PainAndNsaidGeriatricRisks Medication #102", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-103", new BeersRiskEntry("BEERS-PAIN-103", "PainAndNsaidGeriatricRisks Medication #103", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-104", new BeersRiskEntry("BEERS-PAIN-104", "PainAndNsaidGeriatricRisks Medication #104", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-105", new BeersRiskEntry("BEERS-PAIN-105", "PainAndNsaidGeriatricRisks Medication #105", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-106", new BeersRiskEntry("BEERS-PAIN-106", "PainAndNsaidGeriatricRisks Medication #106", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-107", new BeersRiskEntry("BEERS-PAIN-107", "PainAndNsaidGeriatricRisks Medication #107", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-108", new BeersRiskEntry("BEERS-PAIN-108", "PainAndNsaidGeriatricRisks Medication #108", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-109", new BeersRiskEntry("BEERS-PAIN-109", "PainAndNsaidGeriatricRisks Medication #109", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-110", new BeersRiskEntry("BEERS-PAIN-110", "PainAndNsaidGeriatricRisks Medication #110", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-111", new BeersRiskEntry("BEERS-PAIN-111", "PainAndNsaidGeriatricRisks Medication #111", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-112", new BeersRiskEntry("BEERS-PAIN-112", "PainAndNsaidGeriatricRisks Medication #112", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-113", new BeersRiskEntry("BEERS-PAIN-113", "PainAndNsaidGeriatricRisks Medication #113", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-114", new BeersRiskEntry("BEERS-PAIN-114", "PainAndNsaidGeriatricRisks Medication #114", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-115", new BeersRiskEntry("BEERS-PAIN-115", "PainAndNsaidGeriatricRisks Medication #115", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-116", new BeersRiskEntry("BEERS-PAIN-116", "PainAndNsaidGeriatricRisks Medication #116", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-117", new BeersRiskEntry("BEERS-PAIN-117", "PainAndNsaidGeriatricRisks Medication #117", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-118", new BeersRiskEntry("BEERS-PAIN-118", "PainAndNsaidGeriatricRisks Medication #118", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-119", new BeersRiskEntry("BEERS-PAIN-119", "PainAndNsaidGeriatricRisks Medication #119", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-120", new BeersRiskEntry("BEERS-PAIN-120", "PainAndNsaidGeriatricRisks Medication #120", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-121", new BeersRiskEntry("BEERS-PAIN-121", "PainAndNsaidGeriatricRisks Medication #121", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-122", new BeersRiskEntry("BEERS-PAIN-122", "PainAndNsaidGeriatricRisks Medication #122", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-123", new BeersRiskEntry("BEERS-PAIN-123", "PainAndNsaidGeriatricRisks Medication #123", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-124", new BeersRiskEntry("BEERS-PAIN-124", "PainAndNsaidGeriatricRisks Medication #124", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-125", new BeersRiskEntry("BEERS-PAIN-125", "PainAndNsaidGeriatricRisks Medication #125", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-126", new BeersRiskEntry("BEERS-PAIN-126", "PainAndNsaidGeriatricRisks Medication #126", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-127", new BeersRiskEntry("BEERS-PAIN-127", "PainAndNsaidGeriatricRisks Medication #127", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-128", new BeersRiskEntry("BEERS-PAIN-128", "PainAndNsaidGeriatricRisks Medication #128", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-129", new BeersRiskEntry("BEERS-PAIN-129", "PainAndNsaidGeriatricRisks Medication #129", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-130", new BeersRiskEntry("BEERS-PAIN-130", "PainAndNsaidGeriatricRisks Medication #130", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-131", new BeersRiskEntry("BEERS-PAIN-131", "PainAndNsaidGeriatricRisks Medication #131", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-132", new BeersRiskEntry("BEERS-PAIN-132", "PainAndNsaidGeriatricRisks Medication #132", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-133", new BeersRiskEntry("BEERS-PAIN-133", "PainAndNsaidGeriatricRisks Medication #133", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-134", new BeersRiskEntry("BEERS-PAIN-134", "PainAndNsaidGeriatricRisks Medication #134", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-135", new BeersRiskEntry("BEERS-PAIN-135", "PainAndNsaidGeriatricRisks Medication #135", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-136", new BeersRiskEntry("BEERS-PAIN-136", "PainAndNsaidGeriatricRisks Medication #136", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-137", new BeersRiskEntry("BEERS-PAIN-137", "PainAndNsaidGeriatricRisks Medication #137", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-138", new BeersRiskEntry("BEERS-PAIN-138", "PainAndNsaidGeriatricRisks Medication #138", "AGS Beers Criteria Tier 1", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-139", new BeersRiskEntry("BEERS-PAIN-139", "PainAndNsaidGeriatricRisks Medication #139", "AGS Beers Criteria Tier 2", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
        risks.put("BEERS-PAIN-140", new BeersRiskEntry("BEERS-PAIN-140", "PainAndNsaidGeriatricRisks Medication #140", "AGS Beers Criteria Tier 3", "High risk of delirium, falls, and orthostatic hypotension in adults >= 65 years.", "Consider safer alternative or reduce dosage by 50%."));
    }

    public Optional<BeersRiskEntry> getByCode(String code) {
        return Optional.ofNullable(risks.get(code));
    }

    public List<BeersRiskEntry> getAllRisks() {
        return new ArrayList<>(risks.values());
    }
}
