package com.hospital.clinical.encyclopedia;

import lombok.Builder;
import lombok.Data;
import org.springframework.stereotype.Component;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Enterprise ICD-10-CM Respiratory & Pulmonology Clinical Encyclopedia (Chapter X: J00-J99).
 * Complete pathophysiological monographs, GOLD/GINA guidelines, ARDS Berlin criteria,
 * arterial blood gas interpretations, mechanical ventilation protocols, and targeted therapeutics.
 */
@Component
public class Icd10RespiratoryEncyclopedia {

    @Data
    @Builder
    public static class RespiratoryDiseaseEntry {
        private String icd10Code;
        private String diseaseName;
        private String category;
        private String pathophysiology;
        private List<String> clinicalFeatures;
        private List<String> diagnosticCriteria;
        private List<String> pulmonaryFunctionTests;
        private List<String> imagingFindings; // CXR, HRCT
        private List<String> arterialBloodGasProfile;
        private List<String> differentialDiagnoses;
        private List<String> evidenceBasedPharmacotherapy;
        private List<String> ventilatoryAndSurgicalSupport;
        private String stagingAndPrognosis;
    }

    private static final List<RespiratoryDiseaseEntry> ENTRIES = new ArrayList<>();

    static {
        // =========================================================================
        // SECTION 1: CHRONIC LOWER RESPIRATORY DISEASES (J40 - J47)
        // =========================================================================
        add("J44.1", "Chronic Obstructive Pulmonary Disease with (Acute) Exacerbation", "Chronic Lower Respiratory Diseases",
                "Acute worsening of respiratory symptoms (dyspnea, cough, sputum volume, and sputum purulence - Anthonisen criteria) beyond normal day-to-day variations that leads to a change in medication. Underlying COPD is characterized by persistent, progressive airflow limitation associated with enhanced chronic inflammatory response in the airways and the lung parenchyma to noxious particles or gases (primarily cigarette smoke and biomass fuel exposure). Pathophysiology involves small airway disease (obstructive bronchiolitis with goblet cell hyperplasia and peribronchiolar fibrosis) and parenchymal destruction (centrilobular or panlobular emphysema with loss of alveolar attachments and elastic recoil, causing dynamic hyperinflation and gas trapping). Exacerbations are triggered in 70-80% of cases by respiratory viral infections (Rhinovirus, Influenza, RSV) or bacterial infections (Streptococcus pneumoniae, Haemophilus influenzae, Moraxella catarrhalis, Pseudomonas aeruginosa in severe airflow limitation).",
                Arrays.asList("Acute worsening of baseline exertional dyspnea progressing to rest dyspnea", "Increased sputum volume and development of frank purulent (green/yellow) sputum", "Increased frequency and severity of cough", "Chest tightness and audible expiratory wheezing", "Accessory muscle use (scalene, sternocleidomastoid), pursed-lip breathing, and paradoxical abdominal motion (Hoover's sign)", "Tachypnea (RR > 25-30 breaths/min), tachycardia, and central cyanosis", "Confusion, lethargy, asterixis (flapping tremor), and morning headaches indicating severe hypercapnia (CO2 narcosis)"),
                Arrays.asList("Post-bronchodilator Spirometry confirming persistent airflow limitation: FEV1/FVC ratio < 0.70 (Fixed ratio defining COPD according to GOLD 2024 guidelines)", "Anthonisen Type 1 (Severe: all 3 cardinal symptoms present - increased dyspnea, increased sputum volume, increased sputum purulence) indicating clear benefit from systemic antibiotics", "Rome Proposal for COPD Exacerbation Severity: Mild (Dyspnea VAS < 5, RR < 24, HR < 95), Moderate (Dyspnea VAS >= 5, RR >= 24, HR >= 95, SpO2 < 92%, CRP >= 10 mg/L), Severe (Arterial Blood Gas with PaCO2 > 45 mmHg and pH < 7.35 indicating acute respiratory acidosis)"),
                Arrays.asList("Post-bronchodilator FEV1/FVC < 0.70", "GOLD Staging of Airflow Limitation based on Post-BD FEV1: GOLD 1 Mild (FEV1 >= 80% predicted), GOLD 2 Moderate (50% <= FEV1 < 80%), GOLD 3 Severe (30% <= FEV1 < 50%), GOLD 4 Very Severe (FEV1 < 30% predicted)", "Plethysmography: Increased Total Lung Capacity (TLC > 120% predicted) and Residual Volume (RV > 140% predicted) indicating air trapping", "Diffusing Capacity of the Lung for Carbon Monoxide (DLCO < 60% predicted in emphysema)"),
                Arrays.asList("Chest X-Ray: Bilateral lung hyperinflation (flattened diaphragmatic domes, increased retrosternal clear space > 2.5 cm on lateral, visualization of > 10 posterior ribs on PA), vascular attenuation in periphery, narrow cardiac silhouette ('tear-drop heart')", "High-Resolution Computed Tomography (HRCT Thorax): Centrilobular emphysematous lucencies with imperceptible walls, paraseptal emphysema, bullous lung disease, and bronchial wall thickening"),
                Arrays.asList("Acute or Acute-on-Chronic Type 2 Hypercapnic Respiratory Failure:", "pH < 7.35 with PaCO2 > 45-60+ mmHg (Acute uncompensated respiratory acidosis)", "PaO2 < 60 mmHg (Hypoxemia on room air)", "Serum Bicarbonate (HCO3- elevated > 28-34 mEq/L indicates chronic metabolic compensation for baseline hypercapnia)", "Alveolar-arterial (A-a) Oxygen Gradient elevated (> 20-30 mmHg) due to severe ventilation-perfusion V/Q mismatch"),
                Arrays.asList("Acute Decompensated Congestive Heart Failure / Cardiogenic Pulmonary Edema", "Severe Acute Asthma Exacerbation", "Acute Massive or Submassive Pulmonary Embolism", "Community-Acquired Pneumonia (focal consolidation on CXR, marked leukocytosis)", "Spontaneous Pneumothorax (sudden pleuritic pain, absent breath sounds, tracheal deviation)", "Upper Airway Obstruction / Foreign Body Aspiration", "Bronchiectasis exacerbation"),
                Arrays.asList("Controlled Oxygen Therapy: Target SpO2 88-92% using Venturi mask (24-28% FiO2) or low-flow nasal cannula (1-2 L/min) to prevent worsening hypercapnia caused by loss of hypoxic vasoconstriction (Haldane effect and dead space increase)", "Inhaled Short-Acting Bronchodilators (SABD): Nebulized Short-Acting Beta-2 Agonist (Salbutamol 2.5-5.0 mg) + Short-Acting Muscarinic Antagonist (Ipratropium Bromide 0.5 mg) q4-6h during acute phase", "Systemic Corticosteroids: Oral Prednisolone 40 mg daily (or IV Methylprednisolone 40-80 mg daily if unable to take oral) for exactly 5 days (REDUCE trial demonstrated 5-day course is non-inferior to 14 days and accelerates FEV1 recovery)", "Evidence-Based Antibiotic Therapy (indicated for Anthonisen Type 1 or any patient requiring mechanical ventilation): Amoxicillin-Clavulanate (875/125 mg PO bid or 1.2g IV tid) OR Macrolide (Azithromycin 500 mg daily x 3-5 days) OR Fluoroquinolone (Levofloxacin 500 mg daily or Moxifloxacin 400 mg daily for risk factors of Pseudomonas: FEV1 < 30%, frequent exacerbations, chronic oral steroid use)", "Maintenance Inhaled Therapy post-discharge (GOLD Group E): Triple Inhaled Therapy (LABA + LAMA + Inhaled Corticosteroid ICS e.g. Fluticasone Furoate / Umeclidinium / Vilanterol OR Budesonide / Glycopyrrolate / Formoterol if blood eosinophils >= 300 cells/uL or >= 100 with >= 2 exacerbations/year)"),
                Arrays.asList("Non-Invasive Positive Pressure Ventilation (NIPPV: BiPAP is the standard of care for acute hypercapnic respiratory failure with pH < 7.35 and PaCO2 > 45 mmHg): Initial settings IPAP 10-14 cmH2O, EPAP 4-5 cmH2O, titrated to achieve tidal volume 6-8 mL/kg and pH > 7.35; reduces intubation rate by 65% and in-hospital mortality by 50%", "Invasive Mechanical Ventilation: Indicated for NIPPV failure (worsening acidosis, coma, hemodynamic instability, severe aspiration risk); lung-protective settings with low respiratory rate (10-14/min) and high inspiratory flow (70-100 L/min) to prolong expiratory time (I:E ratio 1:3 to 1:4) and minimize dynamic intrinsic PEEP (Auto-PEEP)", "Bronchoscopic Lung Volume Reduction (BLVR with one-way endobronchial valves e.g. Zephyr valves in severe heterogeneous emphysema without collateral ventilation)", "Lung Volume Reduction Surgery (LVRS) or Bilateral Lung Transplantation for end-stage GOLD 4 COPD in selected candidates"),
                "Prognosis is stratified by the BODE Index (Body Mass Index, airflow Obstruction FEV1, Dyspnea mMRC scale, Exercise 6-minute walk distance). Severe exacerbations requiring hospitalization carry an in-hospital mortality of 4-8% and 1-year mortality of 20-30%. Long-term oxygen therapy (LTOT for >= 15 hours/day in resting PaO2 <= 55 mmHg or SpO2 <= 88%) improves survival. Comprehensive pulmonary rehabilitation reduces future hospitalizations by 40%.");

        add("J45.52", "Severe Persistent Asthma with Status Asthmaticus", "Chronic Lower Respiratory Diseases",
                "Acute, severe, life-threatening, progressive asthma exacerbation that fails to respond promptly to standard intensive bronchodilator and corticosteroid therapy. Pathophysiology is driven by intense Type 2 inflammatory cascade (IL-4, IL-5, IL-13, IgE-mediated mast cell and eosinophil degranulation) causing profound airway smooth muscle bronchospasm, extensive mucosal edema, extensive epithelial desquamation, and dense intraluminal inspissated mucocellular plugging throughout the tracheobronchial tree. Results in severe airflow resistance, air trapping, massive increase in work of breathing, ventilation-perfusion mismatch, respiratory muscle fatigue, and impending fatal asphyxia.",
                Arrays.asList("Extreme breathlessness with inability to speak in phrases or single words (speech fragmented into monosyllables)", "Upright 'tripod' orthopneic positioning (leaning forward with hands on knees to engage accessory muscles)", "Profound tachypnea (Respiratory Rate > 30-40 breaths/min)", "Pulsus Paradoxus (fall in systolic blood pressure > 10-20 mmHg during quiet inspiration, indicating massive negative intrathoracic pressure swings)", "Tachycardia (Heart Rate > 120 bpm; bradycardia is an ominous pre-terminal sign of respiratory arrest)", "Audible polyphonic high-pitched expiratory and inspiratory wheezes; or OMINOUS 'SILENT CHEST' (complete absence of breath sounds due to critical airflow reduction and lack of air movement)"),
                Arrays.asList("GINA 2024 Criteria for Life-Threatening Asthma Exacerbation: Presence of any: Silent chest, Cyanosis, Bradycardia, Hypotension, Exhaustion, Confusion, PaCO2 normal or elevated (> 40-45 mmHg) in a breathless patient", "Peak Expiratory Flow (PEF) < 30-50% of patient's personal best or predicted value", "Failure of PEF or FEV1 to improve by > 15-20% after 1 hour of continuous nebulized bronchodilators and IV steroids"),
                Arrays.asList("Severe obstructive pattern with FEV1 < 30-40% predicted", "Marked Bronchodilator Reversibility (increase in FEV1 by >= 12% and >= 200 mL following bronchodilator in stable phase)", "Elevated Fractional Exhaled Nitric Oxide (FeNO > 50 ppb indicating active eosinophilic airway inflammation)", "Blood Eosinophils >= 300 cells/uL"),
                Arrays.asList("Chest X-Ray: Symmetrical lung hyperinflation with low, flat diaphragms and increased bronchovascular markings; MANDATORY to exclude complications: Pneumothorax, Pneumomediastinum, Subcutaneous Emphysema, and Lobar Atelectasis from mucus plugging"),
                Arrays.asList("INITIAL STAGE: Type 1 Hypoxemia with respiratory alkalosis (pH > 7.45, PaCO2 < 30-35 mmHg, PaO2 60-75 mmHg due to hyperventilation)", "TRANSITIONAL / DANGER STAGE: 'Normal' PaCO2 (38-42 mmHg) and normal pH in a severely tachypneic patient indicates respiratory muscle exhaustion and impending arrest", "LATE CRITICAL STAGE: Severe combined Respiratory and Metabolic Acidosis (pH < 7.20, PaCO2 > 50-80 mmHg, PaO2 < 50 mmHg, Lactic Acid > 4.0 mmol/L due to immense work of breathing)"),
                Arrays.asList("Acute Foreign Body Aspiration (especially with unilateral absent breath sounds)", "Anaphylaxis with Laryngeal Edema and Upper Airway Stridor", "Acute Heart Failure / Cardiogenic Pulmonary Edema ('Cardiac Asthma')", "Vocal Cord Dysfunction (VCD / Inducible Laryngeal Obstruction - paradoxical vocal cord adduction during inspiration)", "Acute Pulmonary Embolism", "Spontaneous Pneumothorax", "Tracheobronchomalacia"),
                Arrays.asList("Continuous Inhaled Short-Acting Beta-2 Agonist: Continuous nebulization of Salbutamol (10-15 mg/hr) OR intermittent nebulization (5 mg q20min x 3 doses in the first hour)", "Inhaled Anticholinergic: Ipratropium Bromide (0.5 mg nebulized with Salbutamol q20min x 3 doses, then q4h - block cholinergic bronchoconstriction and reduce mucus secretion)", "Early High-Dose Systemic Corticosteroids: Intravenous Hydrocortisone (100-200 mg IV q6h) OR IV Methylprednisolone (60-80 mg IV q6-8h) - genomic anti-inflammatory effects take 4-6 hours to onset; continue for 5-7 days", "Intravenous Magnesium Sulfate: Single infusion of Magnesium Sulfate 2.0 grams IV in 100 mL Normal Saline over 20 minutes (inhibits smooth muscle calcium influx, producing direct bronchial relaxation; proven to reduce hospitalization in severe acute asthma)", "Intravenous Beta-2 Agonist (for patients unable to inhale effectively): IV Terbutaline or IV Salbutamol (bolus 250 mcg IV over 10 min, then 1-5 mcg/min infusion under continuous ECG monitoring)", "Biologic Therapy for Severe Uncontrolled Eosinophilic/Allergic Asthma (Outpatient Maintenance): Anti-IgE (Omalizumab SC q2-4w), Anti-IL-5 (Mepolizumab 100 mg SC q4w, Reslizumab IV, Benralizumab 30 mg SC q8w), Anti-IL-4R-alpha (Dupilumab 200/300 mg SC q2w), or Anti-TSLP (Tezepelumab 210 mg SC q4w)"),
                Arrays.asList("Non-Invasive Positive Pressure Ventilation (BiPAP: IPAP 10-12, EPAP 4-5 cmH2O) with close monitoring for exhaustion", "Invasive Mechanical Ventilation: Reserved for cardiac arrest, severe coma, or profound refractory exhaustion/acidosis (pH < 7.15). Lung-protective strategy with 'Permissive Hypercapnia': Low tidal volume (4-6 mL/kg PBW), low respiratory rate (8-12 breaths/min), high inspiratory peak flow (80-100 L/min) to maximize expiratory time (I:E >= 1:4) and minimize plateau pressure (< 30 cmH2O) and dynamic hyperinflation (Auto-PEEP < 10-15 cmH2O) to prevent tension pneumothorax and circulatory collapse", "General Inhalation Anesthetics (Sevoflurane or Isoflurane via dedicated scavenger circuit in ICU) for refractory status asthmaticus due to potent intrinsic bronchodilator properties", "Veno-Venous Extracorporeal Membrane Oxygenation (VV-ECMO) for refractory life-threatening status asthmaticus when mechanical ventilation cannot safely clear CO2 without dangerous barotrauma"),
                "With rapid, aggressive multimodal medical intervention in an intensive care setting, mortality in status asthmaticus is < 1-2%. However, patients who experience near-fatal asthma exacerbations require permanent classification as GINA Step 5 Severe Asthma, mandatory prescription of an Inhaled Corticosteroid-Formoterol reliever/maintenance regimen (SMART / MART protocol), daily peak flow monitoring, a written personalized Asthma Action Plan, and formal evaluation for biologic monoclonal antibody therapy.");

        add("J80", "Acute Respiratory Distress Syndrome (ARDS)", "Other Respiratory Diseases Affecting Interstitium",
                "Catastrophic, diffuse, inflammatory lung injury syndrome characterized by increased pulmonary vascular permeability, diffuse alveolar epithelial and endothelial cell necrosis, loss of aerated lung tissue ('baby lung'), flooding of the alveoli with protein-rich exudative fluid, surfactant dysfunction, alveolar collapse (atelectasis), and profound refractory hypoxemia. Pathophysiology unfolds across three overlapping histological phases: (1) Exudative Phase (Days 1-7: capillary endothelial damage, alveolar macrophage activation, neutrophil recruitment, formation of dense eosinophilic hyaline membranes along denuded basement membranes); (2) Proliferative Phase (Days 7-21: Type II pneumocyte proliferation, myofibroblast migration, provisional matrix deposition); (3) Fibrotic Phase (Day > 21: extensive interstitial and alveolar fibrosis, structural remodeling, obliteration of pulmonary microvasculature, chronic pulmonary hypertension). Common direct etiologies: Pneumonia (bacterial, viral Influenza/SARS-CoV-2), Aspiration of gastric contents, Pulmonary contusion, Inhalation injury; Indirect etiologies: Non-pulmonary Sepsis, Severe Polytrauma, Acute Pancreatitis, Massive Transfusion (TRALI), Cardiopulmonary bypass, Burn shock.",
                Arrays.asList("Acute onset of profound, refractory dyspnea and air hunger developing within 6-72 hours of an identified clinical insult", "Severe tachypnea (Respiratory Rate > 35-45 breaths/min)", "Profound central and peripheral cyanosis unresponsive to high-flow non-rebreather mask oxygen", "Diffuse bilateral coarse inspiratory crackles and bronchial breath sounds on auscultation", "Diaphoresis, intercostal and supraclavicular retractions, and acute encephalopathy due to severe cerebral hypoxemia", "Hemodynamic instability or septic shock with vasopressor requirements"),
                Arrays.asList("BERLIN DEFINITION OF ARDS (2012 / Updated 2023 Global Definition):", "(1) TIMING: Acute onset within 1 week of a known clinical insult or new/worsening respiratory symptoms;", "(2) CHEST IMAGING: Bilateral opacities on chest radiograph or CT scan not fully explained by pleural effusions, lobar/lung collapse, or nodules;", "(3) ORIGIN OF EDEMA: Respiratory failure not fully explained by cardiac failure or fluid overload (objective echocardiography required to exclude hydrostatic cardiogenic edema if no clear risk factor is present);", "(4) OXYGENATION IMPAIRMENT (on PEEP >= 5 cmH2O):", "- MILD ARDS: 200 mmHg < PaO2/FiO2 ratio <= 300 mmHg", "- MODERATE ARDS: 100 mmHg < PaO2/FiO2 ratio <= 200 mmHg", "- SEVERE ARDS: PaO2/FiO2 ratio <= 100 mmHg"),
                Arrays.asList("Marked reduction in Static Respiratory System Compliance (Cstat = Vt / [Pplat - PEEP] < 20-30 mL/cmH2O; normal is 50-80 mL/cmH2O), reflecting severe lung stiffness ('stiff lung')", "Massive increase in physiological dead space fraction (Vd/Vt > 0.60)", "Severely reduced Functional Residual Capacity (FRC)"),
                Arrays.asList("Chest Radiograph: Diffuse, bilateral, fluffy, confluent alveolar-interstitial infiltrates sparing the costophrenic angles (non-cardiogenic 'white-out' lung)", "High-Resolution CT (HRCT Thorax): Heterogeneous distribution of dependent dense alveolar consolidation with patent air bronchograms, extensive non-dependent ground-glass opacities, and spared anterior aerated lung tissue ('baby lung' concept)"),
                Arrays.asList("Severe Refractory Hypoxemia (PaO2/FiO2 ratio < 100-150 mmHg on 100% FiO2)", "Massive Alveolar-arterial (A-a) Oxygen Gradient (> 300-500 mmHg) caused by extensive right-to-left intrapulmonary shunt (blood perfusing non-aerated consolidated/collapsed alveoli)", "Mixed Respiratory and Lactic Acidosis (pH < 7.25, PaCO2 variable, Lactate > 2.0-4.0 mmol/L)"),
                Arrays.asList("Cardiogenic Pulmonary Edema / Acute Left Ventricular Systolic/Diastolic Failure (elevated PCWP > 18 mmHg, elevated BNP/NT-proBNP, responds rapidly to loop diuretics)", "Transfusion-Related Acute Lung Injury (TRALI - occurs within 6 hours of blood product transfusion)", "Diffuse Alveolar Hemorrhage (DAH - Goodpasture syndrome, ANCA-associated vasculitis, Systemic Lupus Erythematosus)", "Acute Interstitial Pneumonia (Hamman-Rich syndrome)", "Disseminated Miliary Tuberculosis / Fungal Pneumonia (Pneumocystis jirovecii)", "Drug-induced acute interstitial lung disease (Amiodarone, Bleomycin, Methotrexate)"),
                Arrays.asList("Treatment of Underlying Etiology: Immediate broad-spectrum intravenous antimicrobials for sepsis/pneumonia, source control for intra-abdominal infections, surgical debridement", "Conservative Fluid Management Strategy (FACTT Trial): Fluid restriction and targeted diuresis (Furosemide) once shock has resolved to achieve net negative fluid balance, significantly shortening duration of mechanical ventilation without increasing renal failure", "Neuromuscular Blockade (NMBA): Continuous infusion of Cisatracurium (37.5 mg/hr for <= 48 hours in severe ARDS with PaO2/FiO2 < 150) to abolish patient-ventilator dyssynchrony, reduce transpulmonary pressure swings, and decrease oxygen consumption (ACURASYS trial)", "Systemic Corticosteroids: Intravenous Dexamethasone (20 mg daily on Days 1-5, then 10 mg daily on Days 6-10 - DEXA-ARDS trial demonstrated significantly increased ventilator-free days and reduced 60-day mortality) OR Methylprednisolone (1-2 mg/kg/day)", "Inhaled Pulmonary Vasodilators: Inhaled Epoprostenol (PGI2 10-50 ng/kg/min) or Inhaled Nitric Oxide (iNO 10-20 ppm) as rescue therapy to selectively vasodilate ventilated alveoli, improving V/Q matching without systemic hypotension"),
                Arrays.asList("LUNG-PROTECTIVE MECHANICAL VENTILATION (ARDSNet Protocol - landmark standard of care):", "(1) Low Tidal Volume Ventilation: Vt strictly targeted to 6 mL/kg of Predicted Body Weight (PBW; based on height and biological sex, NOT actual weight), reducing to 4 mL/kg if necessary to maintain Plateau Pressure (Pplat) <= 30 cmH2O and Driving Pressure (Pplat - PEEP) <= 14-15 cmH2O to prevent ventilator-induced lung injury (VILI: barotrauma, volutrauma, atelectrauma, and biotrauma);", "(2) High PEEP Titration (PEEP 10-20 cmH2O based on PEEP-FiO2 titration tables) to recruit collapsed non-aerated alveoli and prevent cyclical end-expiratory alveolar collapse;", "(3) Permissive Hypercapnia: Allowing PaCO2 to rise (50-70 mmHg) while maintaining arterial pH >= 7.20-7.25;", "(4) PRONE POSITIONING (PROSEVA Trial): Mandatory for moderate-to-severe ARDS with PaO2/FiO2 < 150 mmHg for AT LEAST 16 to 24 consecutive hours per day; promotes uniform transpulmonary pressure distribution, relieves dorsal lung compression from the heart and abdomen, dramatically improves V/Q matching, and reduces 28-day mortality by 50%;", "(5) VENO-VENOUS EXTRACORPOREAL MEMBRANE OXYGENATION (VV-ECMO - EOLIA Trial criteria): Indicated for refractory severe ARDS with PaO2/FiO2 < 50 for > 3 hours or PaO2/FiO2 < 80 for > 6 hours or pH < 7.15 despite lung-protective ventilation and prone positioning"),
                "High overall in-hospital mortality: Mild ARDS ~27%, Moderate ARDS ~32%, Severe ARDS ~45-50%. Major causes of death are multi-organ dysfunction syndrome (MODS), refractory septic shock, and ventilator-associated complications (tension pneumothorax, ventilator-associated pneumonia). Survivors of ARDS experience Post-Intensive Care Syndrome (PICS), including long-term neurocognitive impairment, post-traumatic stress disorder (PTSD), severe muscle weakness (ICU-acquired myopathy), and residual pulmonary fibrosis with reduced DLCO, requiring prolonged multidisciplinary pulmonary rehabilitation.");
    }

    private static void add(String code, String name, String cat, String patho,
                            List<String> clin, List<String> diag, List<String> pft,
                            List<String> img, List<String> abg, List<String> diff,
                            List<String> rx, List<String> vent, String stag) {
        ENTRIES.add(RespiratoryDiseaseEntry.builder()
                .icd10Code(code)
                .diseaseName(name)
                .category(cat)
                .pathophysiology(patho)
                .clinicalFeatures(clin)
                .diagnosticCriteria(diag)
                .pulmonaryFunctionTests(pft)
                .imagingFindings(img)
                .arterialBloodGasProfile(abg)
                .differentialDiagnoses(diff)
                .evidenceBasedPharmacotherapy(rx)
                .ventilatoryAndSurgicalSupport(vent)
                .stagingAndPrognosis(stag)
                .build());
    }

    public List<RespiratoryDiseaseEntry> search(String query) {
        if (query == null || query.isBlank()) {
            return ENTRIES;
        }
        String q = query.toLowerCase().trim();
        return ENTRIES.stream()
                .filter(e -> e.getIcd10Code().toLowerCase().contains(q) ||
                             e.getDiseaseName().toLowerCase().contains(q) ||
                             e.getCategory().toLowerCase().contains(q) ||
                             e.getPathophysiology().toLowerCase().contains(q))
                .collect(Collectors.toList());
    }

    public Optional<RespiratoryDiseaseEntry> findByCode(String code) {
        return ENTRIES.stream()
                .filter(e -> e.getIcd10Code().equalsIgnoreCase(code))
                .findFirst();
    }
}
