package com.hospital.clinical.encyclopedia;

import lombok.Builder;
import lombok.Data;
import org.springframework.stereotype.Component;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Enterprise ICD-10-CM Cardiovascular Clinical Encyclopedia (Chapter IX: I00-I99).
 * Contains exhaustive pathophysiological monographs, diagnostic criteria, ECG patterns,
 * hemodynamic classifications, biomarker interpretation, and evidence-based pharmacotherapy guidelines.
 */
@Component
public class Icd10CardiovascularEncyclopedia {

    @Data
    @Builder
    public static class CardioDiseaseEntry {
        private String icd10Code;
        private String diseaseName;
        private String subcategory;
        private String pathophysiology;
        private List<String> clinicalPresentation;
        private List<String> diagnosticCriteria;
        private List<String> ecgFindings;
        private List<String> laboratoryBiomarkers;
        private List<String> echocardiographyFindings;
        private List<String> differentialDiagnoses;
        private List<String> firstLinePharmacotherapy;
        private List<String> interventionalSurgicalOptions;
        private String prognosisAndComplications;
    }

    private static final List<CardioDiseaseEntry> ENTRIES = new ArrayList<>();

    static {
        // =========================================================================
        // SECTION 1: HYPERTENSIVE DISEASES (I10 - I15)
        // =========================================================================
        add("I10", "Essential (Primary) Hypertension", "Hypertensive Diseases",
                "Multifactorial cardiovascular disorder characterized by chronic persistent elevation of systemic arterial blood pressure (Systolic BP >= 130 mmHg or Diastolic BP >= 80 mmHg according to ACC/AHA 2017 guidelines; SBP >= 140 or DBP >= 90 mmHg according to ESC/ESH 2018). Pathophysiology involves increased total peripheral resistance mediated by sympathetic nervous system hyperactivity, renin-angiotensin-aldosterone system (RAAS) overactivation, renal sodium retention, endothelial dysfunction with impaired nitric oxide bioavailability, and vascular remodeling with medial hypertrophy.",
                Arrays.asList("Often asymptomatic ('The Silent Killer')", "Occipital early morning headaches", "Epistaxis", "Exertional dyspnea", "Dizziness and lightheadedness", "Visual blurring or scotomas in severe elevations"),
                Arrays.asList("Average of >= 2 properly measured seated BP readings on >= 2 separate clinical encounters showing SBP >= 130 mmHg and/or DBP >= 80 mmHg", "24-hour Ambulatory Blood Pressure Monitoring (ABPM) showing 24-hr mean >= 125/75 mmHg or daytime mean >= 130/80 mmHg", "Home Blood Pressure Monitoring (HBPM) average >= 130/80 mmHg"),
                Arrays.asList("Left ventricular hypertrophy (Sokolow-Lyon index: S in V1 + R in V5/V6 >= 35 mm; Cornell voltage criteria: R in aVL + S in V3 > 28 mm in men, > 20 mm in women)", "Left atrial enlargement (P-mitrale with bifid P waves in lead II and biphasic P in V1 with prominent negative terminal component)", "ST-T segment strain pattern in lateral precordial leads (V5, V6, I, aVL)"),
                Arrays.asList("Serum Creatinine and Blood Urea Nitrogen (BUN) to screen for hypertensive nephrosclerosis", "Estimated Glomerular Filtration Rate (eGFR CKD-EPI)", "Serum Electrolytes (Sodium, Potassium - screen for primary hyperaldosteronism)", "Urinalysis for microalbuminuria / Protein-to-Creatinine Ratio (UACR)", "Fasting Lipid Profile and Fasting Plasma Glucose / HbA1c", "Serum Uric Acid and Thyroid Stimulating Hormone (TSH)"),
                Arrays.asList("Concentric left ventricular hypertrophy with increased relative wall thickness (RWT > 0.42)", "Left ventricular diastolic dysfunction (E/A ratio reversal, elevated E/e' ratio > 14)", "Left atrial volume index (LAVI) enlargement (> 34 mL/m2)", "Preserved left ventricular ejection fraction (LVEF >= 50%) in uncomplicated stages"),
                Arrays.asList("Secondary Hypertension due to Renal Artery Stenosis (fibromuscular dysplasia or atherosclerotic)", "Primary Aldosteronism (Conn's syndrome)", "Pheochromocytoma and Paraganglioma", "Cushing's Syndrome", "Obstructive Sleep Apnea (OSA)", "Coarctation of the Aorta", "Drug-induced hypertension (NSAIDs, Oral Contraceptive Pills, Corticosteroids, Decongestants, Cocaine)"),
                Arrays.asList("Angiotensin-Converting Enzyme Inhibitors (ACEi: Enalapril 5-40 mg daily, Ramipril 2.5-10 mg daily, Lisinopril 10-40 mg daily)", "Angiotensin II Receptor Blockers (ARBs: Telmisartan 40-80 mg daily, Losartan 50-100 mg daily, Valsartan 80-320 mg daily)", "Dihydropyridine Calcium Channel Blockers (CCBs: Amlodipine 2.5-10 mg daily, Cilnidipine 10-20 mg daily, Nifedipine GITS 30-60 mg daily)", "Thiazide/Thiazide-like Diuretics (Chlorthalidone 12.5-25 mg daily, Hydrochlorothiazide 12.5-25 mg daily, Indapamide 1.5-2.5 mg daily)", "Mineralocorticoid Receptor Antagonists (Spironolactone 25-50 mg daily as 4th-line add-on for resistant hypertension)"),
                Arrays.asList("Renal Denervation (Catheter-based radiofrequency or ultrasound ablation of renal sympathetic nerves in resistant hypertension)", "Baroreceptor Activation Therapy (BAT)"),
                "Untreated hypertension leads to target organ damage (TOD): Accelerated atherosclerosis, Coronary Artery Disease, Myocardial Infarction, Hypertensive Heart Failure, Ischemic and Hemorrhagic Stroke, Vascular Dementia, Hypertensive Nephrosclerosis leading to End-Stage Renal Disease (ESRD), Hypertensive Retinopathy (Keith-Wagener-Barker Grade I-IV), and Thoracic/Abdominal Aortic Aneurysms. Strict BP control (< 130/80 mmHg) reduces stroke risk by 35-40% and myocardial infarction risk by 20-25%.");

        add("I11.0", "Hypertensive Heart Disease with Heart Failure", "Hypertensive Diseases",
                "Chronic end-organ cardiac manifestation of long-standing uncontrolled systemic arterial hypertension resulting in progressive left ventricular concentric hypertrophy, interstitial myocardial fibrosis, impaired active ventricular relaxation (diastolic dysfunction - HFpEF), and eventual myocardial wall thinning, chamber dilation, and systolic impairment (HFrEF). Pathophysiologically driven by chronic pressure overload causing myocyte hypertrophy, increased myocyte stiffness, microvascular rarefaction, and subendocardial ischemia.",
                Arrays.asList("Progressive exertional dyspnea (NYHA Class II-IV)", "Orthopnea (requiring multiple pillows to sleep)", "Paroxysmal Nocturnal Dyspnea (PND - awakening gasping for air)", "Bilateral lower extremity pitting pedal edema", "Fatigue, weakness, and exercise intolerance", "Nocturia and right upper quadrant abdominal fullness due to hepatic congestion"),
                Arrays.asList("Framingham Heart Failure Diagnostic Criteria (Presence of >= 2 major criteria or 1 major + 2 minor criteria)", "Elevated natriuretic peptide levels (NT-proBNP > 125 pg/mL in non-acute or > 300 pg/mL in acute setting; BNP > 35 pg/mL non-acute or > 100 pg/mL acute)", "Echocardiographic evidence of structural heart disease (LVH, LAE) and/or diastolic dysfunction (elevated filling pressures E/e' > 14) or reduced LVEF"),
                Arrays.asList("Prominent left ventricular hypertrophy voltage with lateral ST-T depression and T-wave inversion (LV strain pattern)", "Left atrial enlargement (broad notched P-wave > 120 ms in II, V1 negative terminal deflection > 1 mm depth and 40 ms duration)", "Sinus tachycardia or atrial fibrillation", "Ventricular premature complexes (PVCs)"),
                Arrays.asList("NT-proBNP / BNP marked elevation", "Cardiac Troponin I or T (mild chronic elevations due to myocyte turnover)", "Serum Creatinine and eGFR to evaluate Cardiorenal Syndrome Type 2", "Serum Electrolytes (hyponatremia indicates severe neurohormonal activation; hypokalemia/hyperkalemia due to diuretic/MRA therapy)", "Liver Function Tests (elevated alkaline phosphatase, total bilirubin, and AST/ALT in congestive hepatopathy)"),
                Arrays.asList("Left ventricular concentric or eccentric hypertrophy", "E/A ratio < 0.8 (impaired relaxation) or > 2.0 with short deceleration time (restrictive filling pattern)", "Average E/e' ratio > 14 indicating elevated left ventricular end-diastolic filling pressures (LVEDP)", "Left atrial volume index (LAVI) > 34 mL/m2", "Left Ventricular Ejection Fraction (LVEF < 40% in HFrEF, 41-49% in HFmrEF, >= 50% in HFpEF)", "Elevated estimated pulmonary artery systolic pressure (PASP > 35 mmHg via tricuspid regurgitant jet velocity > 2.8 m/s)"),
                Arrays.asList("Coronary Artery Disease / Ischemic Cardiomyopathy", "Aortic Stenosis or Aortic Regurgitation", "Hypertrophic Cardiomyopathy (HCM / HOCM)", "Infiltrative Cardiomyopathies (Cardiac Amyloidosis, Sarcoidosis, Hemochromatosis)", "Dilated Cardiomyopathy of viral, toxic (alcohol, anthracyclines), or idiopathic etiology", "Constrictive Pericarditis", "High-output heart failure (Severe anemia, Thyrotoxicosis, AV fistulas, Beriberi)"),
                Arrays.asList("Angiotensin Receptor-Neprilysin Inhibitor (ARNI: Sacubitril/Valsartan 24/26 mg bid titrated to target 97/103 mg bid) or ACEi/ARB", "Evidence-based Beta-Blockers (Bisoprolol 1.25-10 mg daily, Carvedilol 3.125-25 mg bid, or Metoprolol Succinate ER 12.5-200 mg daily - initiated when patient is euvolemic)", "Mineralocorticoid Receptor Antagonists (Spironolactone 12.5-50 mg daily or Eplerenone 25-50 mg daily; monitor potassium and eGFR)", "Sodium-Glucose Cotransporter 2 Inhibitors (SGLT2i: Empagliflozin 10 mg daily or Dapagliflozin 10 mg daily - proven benefit across ALL LVEF ranges)", "Loop Diuretics for decongestion (Furosemide 20-80 mg daily, Torsemide 10-40 mg daily, or Bumetanide 0.5-2 mg daily titrated to euvolemic dry weight)"),
                Arrays.asList("Cardiac Resynchronization Therapy Defibrillator (CRT-D in sinus rhythm with LBBB and QRS duration >= 150 ms and LVEF <= 35% on optimal guideline-directed medical therapy)", "Implantable Cardioverter-Defibrillator (ICD for primary prevention in ischemic LVEF <= 35% or non-ischemic LVEF <= 35%)", "Left Ventricular Assist Device (LVAD) destination therapy or bridge to heart transplantation in end-stage NYHA Class IV heart failure"),
                "Significant morbidity and mortality with 5-year survival approx 50% without guideline-directed medical therapy (GDMT). Complications include acute decompensated pulmonary edema, cardiogenic shock, intractable cardiorenal syndrome, malignant ventricular tachyarrhythmias (VT/VF), atrial fibrillation with thromboembolism, and sudden cardiac death. Strict adherence to quadruple GDMT therapy reduces all-cause mortality by over 60%.");

        add("I20.0", "Unstable Angina Pectoris", "Ischemic Heart Diseases",
                "Acute coronary syndrome (ACS) characterized by myocardial ischemia at rest or on minimal exertion in the absence of acute cardiomyocyte necrosis (normal cardiac troponins). Pathophysiology typically involves non-occlusive disruption or rupture of an atherosclerotic plaque with superimposed non-occlusive platelet-rich thrombus, dynamic coronary vasospasm, progressive mechanical obstruction, or secondary ischemia due to increased myocardial oxygen demand (tachycardia, anemia, thyrotoxicosis) exceeding supply.",
                Arrays.asList("Angina at rest (usually prolonged > 20 minutes)", "New-onset angina (within 2 months) of at least CCS Class III severity", "Crescendo angina (previously diagnosed angina that has become distinctly more frequent, longer in duration, or lower in threshold)", "Retrosternal substernal pressure, heaviness, squeezing, or burning sensation", "Radiation to left shoulder, arm, neck, jaw, epigastrium, or interscapular region", "Associated diaphoresis, nausea, dyspnea, presyncope, or feeling of impending doom"),
                Arrays.asList("Clinical history meeting definition of rest, new-onset, or crescendo angina", "Absence of persistent ST-segment elevation on 12-lead ECG", "NEGATIVE high-sensitivity cardiac troponins (hs-cTnI / hs-cTnT) measured on presentation and repeated at 1 to 3 hours (distinguishing UA from NSTEMI)", "TIMI Risk Score (0-7) or GRACE Score calculation for risk stratification"),
                Arrays.asList("Transient horizontal or downsloping ST-segment depression (>= 0.5 mm in >= 2 contiguous leads)", "Dynamic T-wave inversions (>= 1 mm in leads with prominent R waves)", "Wellens Syndrome pattern: Deep symmetrical T-wave inversion (Type B) or biphasic T-waves (Type A) in V2-V3 (indicates critical proximal LAD stenosis)", "Transient ST elevation or normal baseline ECG (up to 30% of cases)"),
                Arrays.asList("Serial high-sensitivity Cardiac Troponin (hs-cTnI < 0.04 ng/mL and Delta within normal limit at 0/1/2/3 hours)", "Creatine Kinase-MB (CK-MB normal)", "Complete Blood Count (rule out severe anemia precipitating type 2 ischemia)", "Serum Creatinine and eGFR (pre-catheterization contrast risk)", "Lipid Profile (fasting LDL-C baseline)", "Serum Electrolytes (K+ target > 4.0 mEq/L, Mg2+ target > 2.0 mg/dL to prevent arrhythmias)"),
                Arrays.asList("Resting regional wall motion abnormalities (RWMA) corresponding to coronary artery distribution during active chest pain, which may resolve upon ischemia resolution", "Assessment of baseline Left Ventricular Ejection Fraction (LVEF)", "Exclusion of mechanical aortic stenosis, hypertrophic cardiomyopathy, or acute pericardial effusion"),
                Arrays.asList("Non-ST-Elevation Myocardial Infarction (NSTEMI - elevated troponin)", "Acute Pericarditis / Myopericarditis", "Acute Aortic Dissection (Stanford Type A / B)", "Acute Pulmonary Embolism", "Spontaneous Pneumothorax", "Gastroesophageal Reflux Disease (GERD) / Esophageal Spasm", "Costochondritis / Tietze Syndrome", "Anxiety / Panic Disorder"),
                Arrays.asList("Dual Antiplatelet Therapy (DAPT): Aspirin loading dose 300-325 mg chewed, followed by 75-100 mg daily + P2Y12 Inhibitor: Ticagrelor loading dose 180 mg, then 90 mg bid, OR Prasugrel 60 mg load, then 10 mg daily (if proceeding to PCI), OR Clopidogrel 300-600 mg load, then 75 mg daily", "Parenteral Anticoagulation: Low-Molecular-Weight Heparin (Enoxaparin 1 mg/kg SC q12h) OR Fondaparinux 2.5 mg SC daily OR Unfractionated Heparin (60 units/kg bolus max 4000 units + 12 units/kg/hr infusion titrated to anti-Xa 0.3-0.7 or aPTT 1.5-2.0x control)", "Anti-Ischemic Therapy: Sublingual Nitroglycerin 0.4 mg q5min x 3 doses, followed by IV Nitroglycerin infusion (5-200 mcg/min titrated to pain relief and BP)", "Oral Beta-Blocker: Metoprolol Tartrate 25-50 mg q6-12h or Bisoprolol 2.5-5 mg daily (Target resting HR 55-60 bpm, avoiding in acute HF/bradycardia)", "High-Intensity Statin: Atorvastatin 80 mg daily or Rosuvastatin 40 mg daily immediately regardless of baseline cholesterol"),
                Arrays.asList("Early Invasive Strategy: Diagnostic Coronary Angiography within 24 hours (for intermediate-to-high risk patients with GRACE score > 109 or TIMI >= 3) with Percutaneous Coronary Intervention (PCI) with Drug-Eluting Stents (DES)", "Immediate Invasive Strategy (< 2 hours) if hemodynamic instability, refractory angina despite medical therapy, acute heart failure, or life-threatening ventricular arrhythmias occur", "Coronary Artery Bypass Grafting (CABG) for complex multi-vessel disease (SYNTAX score > 22), left main stem disease, or multi-vessel disease in diabetes"),
                "High risk of progression to acute myocardial infarction (NSTEMI/STEMI) or sudden cardiac death within 30 days if left untreated. With prompt risk stratification, aggressive medical therapy, and coronary revascularization, 1-year mortality is reduced to < 3-5%. Strict secondary prevention (DAPT for 12 months, high-intensity statin targeting LDL < 55 mg/dL, beta-blocker, ACEi/ARB, smoking cessation, and cardiac rehabilitation) is mandatory.");

        add("I21.0", "Acute ST-Elevation Myocardial Infarction of Anterior Wall", "Ischemic Heart Diseases",
                "Transmural myocardial necrosis of the anterior wall of the left ventricle and/or interventricular septum, most commonly caused by acute, complete, persistent thrombotic occlusion of the Left Anterior Descending (LAD) coronary artery following atherosclerotic plaque rupture or erosion. Pathophysiology involves immediate cessation of coronary perfusion, rapid depletion of intracellular ATP within 60 seconds, cessation of contractility within minutes, and irreversible wave-front wavefront cardiomyocyte necrosis spreading from subendocardium to subepicardium over 6 to 12 hours.",
                Arrays.asList("Severe, crushing, retrosternal chest pain ('an elephant sitting on my chest') lasting > 20-30 minutes, unrelieved by rest or sublingual nitroglycerin", "Radiation of pain to the left shoulder, left arm, neck, lower jaw, or back", "Profound diaphoresis (cold clammy drenching sweat)", "Marked dyspnea and orthopnea due to acute left ventricular systolic dysfunction and pulmonary venous congestion", "Nausea, vomiting, lightheadedness, syncope, or profound presyncope", "Sense of impending doom (angor animi)"),
                Arrays.asList("Clinical symptoms consistent with acute myocardial ischemia lasting >= 20 minutes", "12-lead ECG demonstrating ST-segment elevation at the J-point in >= 2 contiguous anterior precordial leads (V1-V4): >= 2.5 mm in men < 40y, >= 2.0 mm in men >= 40y, >= 1.5 mm in women in V2-V3, or >= 1.0 mm in other leads", "Elevated high-sensitivity cardiac troponin (hs-cTnI / hs-cTnT) with dynamic rise and/or fall above the 99th percentile upper reference limit"),
                Arrays.asList("Hyperacute tall, peaked, symmetrical T-waves in leads V1 to V4 (earliest sign within minutes)", "Convex-upward ('tombstone') ST-segment elevation in leads V1, V2, V3, V4, +/- I and aVL (Anterolateral STEMI)", "Reciprocal ST-segment depression in inferior leads (II, III, aVF)", "Development of pathologic Q waves (width >= 0.04s or depth >= 25% of succeeding R wave) indicating established transmural necrosis", "New Left Bundle Branch Block (LBBB) or Right Bundle Branch Block (RBBB) with concordant ST elevation (Sgarbossa criteria: concordant ST elevation >= 1 mm in leads with positive QRS = 5 points; concordant ST depression >= 1 mm in V1-V3 = 3 points; discordant ST elevation >= 5 mm = 2 points; score >= 3 is specific for STEMI)"),
                Arrays.asList("High-sensitivity Cardiac Troponin I (hs-cTnI > 0.04 ng/mL with dramatic serial rise)", "Creatine Kinase-MB (CK-MB elevated with peak at 18-24 hours)", "Serum Lactate (marker of tissue hypoperfusion in cardiogenic shock)", "Arterial Blood Gas (ABG - assessing hypoxemia and metabolic acidosis)", "Complete Blood Count (leukocytosis is common due to acute systemic inflammatory response)", "Serum Electrolytes, BUN, and Creatinine"),
                Arrays.asList("Akinesis or dyskinesis of the left ventricular anterior wall, apex, and anterior interventricular septum", "Significant depression of Left Ventricular Ejection Fraction (LVEF often 25-40%)", "Evaluation for acute mechanical complications: Left ventricular apical thrombus formation, Ventricular Septal Rupture (VSR with left-to-right color Doppler jet), Acute severe Mitral Regurgitation due to papillary muscle rupture/dysfunction, and Left Ventricular Free Wall Rupture with hemopericardium and tamponade"),
                Arrays.asList("Acute Pericarditis / Myopericarditis (diffuse PR depression, concave upward ST elevation across all leads without reciprocal changes)", "Acute Aortic Dissection Type A with coronary malperfusion (CT Aortogram mandatory if widened mediastinum or asymmetric pulses)", "Takotsubo Cardiomyopathy (Apical ballooning syndrome - coronary angiography shows unobstructed arteries)", "Pulmonary Embolism with acute cor pulmonale (S1Q3T3 pattern, right heart strain in V1-V3)", "Spontaneous Coronary Artery Dissection (SCAD - common in young females / peripartum)", "Brugada Syndrome (Coved ST elevation in V1-V2 with pseudo-RBBB without troponin rise)"),
                Arrays.asList("Primary Percutaneous Coronary Intervention (PPCI) is the gold standard reperfusion strategy (Door-to-Balloon time < 90 minutes from first medical contact)", "Dual Antiplatelet Therapy (DAPT): Aspirin 300-325 mg chewed immediately + Ticagrelor 180 mg loading dose (or Prasugrel 60 mg if naive and anatomy known)", "Parenteral Anticoagulation: Unfractionated Heparin (70-100 units/kg bolus targeting ACT 250-300 seconds during PCI) or Bivalirudin", "Intravenous Glycoprotein IIb/IIIa Inhibitors (Tirofiban or Eptifibatide) for high thrombus burden / no-reflow phenomenon", "Fibrinolytic Therapy (ONLY if PPCI cannot be performed within 120 minutes of diagnosis): Tenecteplase (TNK-tPA weight-adjusted 30-50 mg IV bolus over 5 seconds) + Aspirin + Clopidogrel 300 mg + Enoxaparin IV bolus 30 mg then 1 mg/kg SC, followed by transfer for pharmaco-invasive PCI within 2-24 hours", "Guideline-Directed Medical Therapy post-PCI: High-dose Atorvastatin 80 mg daily, Beta-Blocker (Metoprolol/Bisoprolol started within 24h once hemodynamically stable), ACE-Inhibitor (Ramipril/Enalapril) or ARB started within 24h, and Mineralocorticoid Receptor Antagonist (Eplerenone/Spironolactone) if LVEF <= 40% and clinical heart failure or diabetes"),
                Arrays.asList("Primary Percutaneous Coronary Intervention (PPCI) with Drug-Eluting Stents (DES) and aspiration thrombectomy if indicated", "Emergency Coronary Artery Bypass Grafting (CABG) for failed PCI, complex anatomy, or mechanical complications (VSR, free wall rupture)", "Mechanical Circulatory Support: Intra-Aortic Balloon Pump (IABP), Impella CP/5.0 microaxial transvalvular pump, or Veno-Arterial Extracorporeal Membrane Oxygenation (VA-ECMO) in refractory cardiogenic shock"),
                "High in-hospital and 30-day mortality if reperfusion is delayed. Anterior STEMI carries the highest risk of acute mechanical complications (VSR 1-2%, Papillary muscle rupture 1%, Free wall rupture 1-2%), malignant ventricular arrhythmias (Ventricular Tachycardia / Ventricular Fibrillation leading to sudden cardiac death), Cardiogenic Shock (Killip Class IV with 40-50% mortality), Left Ventricular Aneurysm, and Apical Mural Thrombus with systemic cardioembolic stroke (requires oral anticoagulation with Warfarin or DOAC for 3-6 months).");

        add("I50.21", "Acute Systolic (Congestive) Heart Failure", "Heart Failure",
                "Sudden life-threatening onset or rapid worsening of signs and symptoms of heart failure characterized by severely reduced left ventricular ejection fraction (LVEF < 40%), resulting in elevated left ventricular end-diastolic pressure, backward transmission to the pulmonary venous bed, capillary fluid extravasation into the pulmonary alveoli (acute cardiogenic pulmonary edema), and forward low cardiac output state. Triggers include medication non-adherence, dietary sodium/fluid excess, acute coronary syndrome, uncontrolled hypertension, tachyarrhythmias (AFib with RVR), acute infections (pneumonia, sepsis), and NSAID administration.",
                Arrays.asList("Acute severe air hunger and tachypnea (Respiratory Rate > 30-40 breaths/min)", "Profound orthopnea (inability to lie flat without severe suffocation)", "Expectoration of pink, frothy, serosanguinous sputum in alveolar pulmonary edema", "Cold, clammy, diaphoretic skin with peripheral cyanosis and mottled extremities", "Elevated Jugular Venous Pressure (JVP > 8-10 cm H2O with positive abdominojugular reflux)", "Bilateral diffuse inspiratory moist crepitations/crackles extending across all lung zones, with wheezing ('cardiac asthma')", "Presence of S3 gallop rhythm (ventricular filling gallop) and laterally displaced apical impulse"),
                Arrays.asList("Nohria-Stevenson Hemodynamic Classification (Profile B 'Warm and Wet' in 80% of cases, or Profile C 'Cold and Wet' in 15-20%)", "Markedly elevated natriuretic peptides (NT-proBNP > 300-10000+ pg/mL; BNP > 100-5000+ pg/mL)", "Chest Radiograph demonstrating cardiomegaly, bilateral alveolar bat-wing/butterfly infiltrates, vascular cephalization, and Kerley B lines", "Bedside Lung Ultrasound (POCUS) demonstrating diffuse multiple bilateral B-lines ('lung rockets' >= 3 per intercostal space) confirming alveolar-interstitial syndrome", "Echocardiography confirming severely depressed LVEF (< 40%) with elevated E/e' > 14 and elevated right ventricular systolic pressure"),
                Arrays.asList("Sinus tachycardia, Atrial Fibrillation with Rapid Ventricular Response (AF with RVR)", "Pre-existing ischemic Q-waves, Left Bundle Branch Block (LBBB), or intraventricular conduction delay", "ST-segment depressions or elevations indicating precipitating acute ischemia", "Low QRS voltage in diffuse myocardial disease"),
                Arrays.asList("Serum NT-proBNP / BNP marked elevation", "Cardiac Troponin I or T (to evaluate for precipitating acute coronary syndrome / type 2 myocardial infarction)", "Serum Creatinine, BUN, and eGFR (assessing Acute Cardiorenal Syndrome Type 1)", "Serum Electrolytes (Sodium < 135 mEq/L indicates severe neurohormonal activation; Potassium monitoring during aggressive loop diuretic therapy)", "Arterial Blood Gas (ABG: Type 1 Hypoxemic respiratory failure PaO2 < 60 mmHg; acute respiratory acidosis with PaCO2 > 50 mmHg indicates impending respiratory exhaustion requiring mechanical ventilation)", "Serum Lactate (> 2.0 mmol/L indicates systemic hypoperfusion/cardiogenic shock)"),
                Arrays.asList("Severely reduced Left Ventricular Ejection Fraction (LVEF < 40%)", "Left ventricular internal diameter dilation in diastole and systole (LVIDd > 55 mm, LVIDs > 45 mm)", "Severe global hypokinesis of the left ventricle", "Dilated left atrium with LAVI > 34 mL/m2", "Elevated mitral inflow E/A ratio with restrictive filling and average E/e' > 14 (elevated left atrial pressure)", "Secondary (functional) Mitral Regurgitation due to annular dilation and papillary muscle tethering", "Inferior Vena Cava (IVC) plethora (> 2.1 cm with < 50% respiratory collapsibility, confirming central venous pressure > 15 mmHg)"),
                Arrays.asList("Acute Respiratory Distress Syndrome (ARDS - non-cardiogenic pulmonary edema with normal PCWP and low BNP)", "Severe Acute Exacerbation of COPD / Status Asthmaticus", "Massive Acute Pulmonary Embolism", "Severe Bilateral Community-Acquired or Hospital-Acquired Pneumonia", "Acute Aortic Regurgitation (due to infective endocarditis or aortic dissection)", "Acute Massive Mitral Regurgitation (papillary muscle rupture)", "Volume Overload due to Anuric End-Stage Renal Disease (ESRD)"),
                Arrays.asList("High-Flow Oxygen therapy / Non-Invasive Positive Pressure Ventilation (NIPPV: CPAP 5-10 cmH2O or BiPAP IPAP 10-15 / EPAP 5 cmH2O - reduces work of breathing, decreases preload/afterload, and prevents endotracheal intubation in 70% of patients)", "Intravenous Loop Diuretics (Furosemide 40-160 mg IV bolus or continuous infusion 5-20 mg/hr, aiming for rapid diuresis of 500-1000 mL in first 2 hours; if diuretic-resistant, add Thiazide Metolazone 2.5-5 mg PO or IV Chlorothiazide for sequential nephron blockade)", "Intravenous Vasodilators (in 'Warm and Wet' hypertensive patients with SBP > 110 mmHg): IV Nitroglycerin (10-200 mcg/min) or IV Sodium Nitroprusside (0.3-3 mcg/kg/min - potent arteriolar/venular vasodilator reducing afterload and preload)", "Intravenous Inotropes (STRICTLY reserved for 'Cold and Wet' cardiogenic shock with SBP < 85-90 mmHg and tissue hypoperfusion): Dobutamine (2.5-20 mcg/kg/min beta-1 agonist) OR Milrinone (0.25-0.75 mcg/kg/min PDE-3 inhibitor / inodilator, dose-adjusted for renal failure) OR Levosimendan (calcium sensitizer)", "Intravenous Vasopressors: Norepinephrine (0.05-0.5 mcg/kg/min - first-line vasopressor if profound hypotension SBP < 70-80 mmHg persists despite inotropes)", "Transition to Guideline-Directed Medical Therapy (Quadruple GDMT: ARNI/ACEi, Beta-Blocker, MRA, SGLT2i) once euvolemic and hemodynamically stable before discharge"),
                Arrays.asList("Endotracheal Intubation and Invasive Mechanical Ventilation for severe exhaustion, coma, or refractory hypoxemia/hypercapnia", "Temporary Mechanical Circulatory Support: Intra-Aortic Balloon Pump (IABP), Impella CP, or Veno-Arterial ECMO in refractory cardiogenic shock", "Urgent Coronary Angiography and PCI if acute coronary syndrome is the precipitating cause", "Slow Continuous Ultrafiltration (SCUF) / Continuous Renal Replacement Therapy (CRRT) for refractory diuretic resistance and anuric cardiorenal syndrome"),
                "High acute in-hospital mortality (4-10%) and 1-year mortality (20-30%), with 30-day hospital readmission rate approaching 20-25%. Complications include cardiogenic shock, cardiac arrest, multi-organ dysfunction syndrome (MODS - ischemic hepatitis, acute tubular necrosis), lethal ventricular tachyarrhythmias, and thromboembolic events. Comprehensive discharge planning, strict medication adherence, low-sodium diet (< 2 g/day), daily weight monitoring, and early outpatient follow-up within 7 days reduce readmissions by 30%.");

        add("I48.0", "Paroxysmal Atrial Fibrillation", "Arrhythmias and Conduction Disorders",
                "Supraventricular tachyarrhythmia characterized by rapid, uncoordinated, disorganized atrial electrical activation (atrial rate 350-600 bpm) with chaotic, irregular ventricular response, which terminates spontaneously or with intervention within 7 days of onset (usually within 48 hours). Pathophysiology originates from rapidly firing ectopic foci within the myocardial sleeves of the pulmonary veins, facilitated by an atrial substrate of structural remodeling, patchy interstitial fibrosis, atrial stretch/dilation, and autonomic nervous system triggers.",
                Arrays.asList("Sudden-onset irregular palpitations ('fluttering or flip-flopping sensation in chest')", "Exertional dyspnea, fatigue, and reduced exercise tolerance", "Lightheadedness, dizziness, or presyncope", "Chest discomfort or atypical angina", "Polyuria (due to atrial stretch-induced release of Atrial Natriuretic Peptide ANP)", "Can be entirely asymptomatic and detected incidentally on routine ECG or pulse examination"),
                Arrays.asList("Standard 12-lead ECG or single-lead ambulatory telemetry recording of >= 30 seconds duration demonstrating absolute irregularity of RR intervals, absence of distinct repeating P-waves, and irregular, chaotic fibrillatory (f) waves", "CHA2DS2-VASc Score calculation for thromboembolic stroke risk assessment (0 in males / 1 in females = Low risk; >= 2 in males / >= 3 in females = High risk requiring oral anticoagulation)", "HAS-BLED Score calculation for 1-year major bleeding risk assessment (Score >= 3 indicates high bleeding risk requiring close monitoring and modifiable risk factor mitigation)"),
                Arrays.asList("Absolute irregularity of R-R intervals ('irregularly irregular' rhythm)", "Absence of discrete P waves preceding QRS complexes", "Variable, fine or coarse fibrillatory baseline waves (f waves at 350-600/min, most prominent in lead V1 and II)", "Variable ventricular rate (untreated typically 110-180 bpm in normal AV node conduction)", "Narrow QRS complexes (< 120 ms) unless pre-existing bundle branch block or rate-dependent aberrancy (Ashman phenomenon) is present"),
                Arrays.asList("Thyroid Stimulating Hormone (TSH) and Free T4 (rule out thyrotoxicosis as a reversible cause)", "Serum Electrolytes (Potassium and Magnesium - hypokalemia/hypomagnesemia trigger and perpetuate AF)", "Serum Creatinine and eGFR (for DOAC and antiarrhythmic drug dosage calculations)", "Complete Blood Count (rule out severe anemia or occult infection/sepsis)", "Liver Function Tests (baseline prior to antiarrhythmic or anticoagulant therapy)", "High-sensitivity Cardiac Troponin (if ischemic etiology or acute coronary syndrome suspected)"),
                Arrays.asList("Left Atrial Volume Index (LAVI > 34 mL/m2 indicates structural atrial remodeling and reduced likelihood of maintaining sinus rhythm long-term)", "Left Ventricular Ejection Fraction (LVEF) and regional wall motion abnormalities", "Evaluation of Mitral Valve (rule out rheumatic mitral stenosis - Valvular AF)", "Transesophageal Echocardiography (TEE - mandatory prior to planned cardioversion if AF duration > 48 hours or unknown and patient not anticoagulated for >= 3 consecutive weeks, to rule out Left Atrial Appendage (LAA) thrombus)"),
                Arrays.asList("Atrial Flutter with variable AV block", "Multifocal Atrial Tachycardia (MAT - >= 3 distinct P-wave morphologies, common in severe COPD)", "Sinus Tachycardia with frequent premature atrial contractions (PACs) or atrial bigeminy", "Atrioventricular Nodal Reentrant Tachycardia (AVNRT) or AVRT", "Ventricular Tachycardia (in wide-complex AF with pre-existing BBB or Wolf-Parkinson-White WPW pre-excitation)"),
                Arrays.asList("Stroke Prevention / Oral Anticoagulation (OAC for CHA2DS2-VASc >= 2 in men or >= 3 in women; Non-Vitamin K Antagonist Oral Anticoagulants DOACs are preferred over Warfarin): Apixaban 5 mg bid (2.5 mg bid if >= 2 of: age >= 80, wt <= 60 kg, Cr >= 1.5 mg/dL), Rivaroxaban 20 mg daily with food (15 mg if CrCl 15-49), Dabigatran 150 mg bid (110 mg in elderly/renal), or Edoxaban 60 mg daily; Warfarin (target INR 2.0-3.0) is mandatory for mechanical heart valves or moderate-to-severe mitral stenosis", "Rate Control Strategy: Beta-Blockers (Metoprolol Tartrate 25-50 mg bid, Bisoprolol 2.5-10 mg daily, Carvedilol 6.25-25 mg bid) OR Non-Dihydropyridine Calcium Channel Blockers (Diltiazem 30-60 mg tid or 120-360 mg CD daily; Verapamil 40-120 mg tid - CONTRAINDICATED in HFrEF LVEF < 40%) OR Digoxin (0.125-0.25 mg daily for sedentary elderly/HF); Target resting HR < 110 bpm (lenient control)", "Rhythm Control Strategy (Pharmacological Cardioversion / Maintenance): Flecainide (50-150 mg bid) or Propafenone (150-300 mg tid) - ONLY in structurally normal hearts without CAD or LVH; Amiodarone (200 mg daily post-loading) - safe in structural heart disease/HFrEF; Dronedarone (400 mg bid) - for non-heart failure patients; Sotalol (80-160 mg bid - monitor QTc interval)"),
                Arrays.asList("Direct Current Synchronized Cardioversion (DCCV: 100-200 J biphasic synchronized shock - emergency if hemodynamically unstable; elective if anticoagulated for >= 3 weeks or TEE clears LAA thrombus)", "Catheter Radiofrequency or Cryoballoon Ablation for Pulmonary Vein Isolation (PVI - first-line or second-line rhythm control with 70-85% success in paroxysmal AF)", "Percutaneous Left Atrial Appendage Occlusion (LAAO: Watchman or Amulet device - for patients with high thromboembolic risk and contraindication to long-term oral anticoagulation)", "Surgical Maze Procedure / Concomitant Surgical LAA Ligation during open-heart surgery"),
                "Carries a 5-fold increased risk of ischemic cardioembolic stroke and a 3-fold increased risk of heart failure (tachycardia-induced cardiomyopathy). Strokes associated with AF are typically larger, more debilitating, and associated with higher mortality than non-AF strokes. Regular anticoagulation reduces ischemic stroke risk by 64% and all-cause mortality by 26%. Early rhythm control (EAST-AFNET 4 trial) within 1 year of diagnosis reduces major cardiovascular adverse events by 21%.");

        add("I26.0", "Acute Massive Pulmonary Embolism with Acute Cor Pulmonale", "Pulmonary Circulation",
                "Life-threatening occlusion of the main pulmonary arterial trunk and/or bilateral main pulmonary arteries by dislodged venous thrombi (originating from deep vein thrombosis of the iliofemoral or popliteal veins in > 90% of cases), resulting in sudden severe right ventricular afterload mismatch, acute right ventricular dilation and failure (acute cor pulmonale), leftward interventricular septal shift, decreased left ventricular preload, precipitous drop in cardiac output, and obstructive shock. Pathophysiologically exacerbated by neurohumoral pulmonary vasoconstriction (thromboxane A2, serotonin release from activated platelets).",
                Arrays.asList("Sudden-onset severe dyspnea and tachypnea (Respiratory Rate > 30 breaths/min)", "Pleuritic chest pain (sharp, stabbing, aggravated by inspiration)", "Hemoptysis (indicates peripheral pulmonary infarction)", "Syncope or presyncope (indicates massive PE with critical hemodynamic compromise)", "Hypotension (Systolic BP < 90 mmHg or SBP drop >= 40 mmHg lasting > 15 minutes not caused by new-onset arrhythmia or hypovolemia - defining Massive PE)", "Tachycardia (Heart Rate > 100-120 bpm)", "Marked Jugular Venous Distension (elevated JVP with prominent 'a' wave)", "Accentuated pulmonary component of the second heart sound (P2 louder than A2) and tricuspid regurgitation murmur"),
                Arrays.asList("Computed Tomography Pulmonary Angiography (CTPA) is the diagnostic gold standard, demonstrating complete or partial filling defects in the main pulmonary arteries, lobar, or segmental branches", "Ventilation-Perfusion (V/Q) Lung Scintigraphy (for patients with severe renal failure or severe iodinated contrast anaphylaxis, demonstrating high-probability mismatch of >= 2 segments)", "Bedside Transthoracic Echocardiography demonstrating acute Right Ventricular strain (RV/LV basal diameter ratio > 1.0, McConnell's sign: hypokinesis of the RV free wall with normal apex contractility, 60/60 sign, or direct visualization of mobile thrombus in transit)", "Wells Criteria and Revised Geneva Score for clinical pre-test probability assessment; PESI (Pulmonary Embolism Severity Index) score for 30-day mortality stratification"),
                Arrays.asList("Sinus tachycardia (most common finding in > 40% of cases)", "S1Q3T3 pattern of acute cor pulmonale (Deep S wave in lead I, pathological Q wave in lead III, and T-wave inversion in lead III - present in ~20% of massive PE)", "T-wave inversions in right precordial leads (V1, V2, V3, +/- V4) indicating acute RV pressure overload and strain", "Complete or Incomplete Right Bundle Branch Block (RBBB)", "Clockwise rotation of the heart with persistent S waves across lateral precordial leads (V5, V6)"),
                Arrays.asList("Plasma D-Dimer (ELISA > 500 ng/mL or age-adjusted cutoff age x 10 in patients > 50y; high sensitivity > 98%, excellent negative predictive value to rule out PE in low/intermediate probability)", "High-sensitivity Cardiac Troponin I or T (elevated in > 50% of intermediate-to-high risk PE, indicating RV myocardial microinfarction/strain and predicting adverse outcomes)", "NT-proBNP / BNP (elevated due to acute RV wall stretch)", "Arterial Blood Gas (ABG: Hypoxemia PaO2 < 70 mmHg, Hypocapnia PaCO2 < 35 mmHg due to hyperventilation, Elevated Alveolar-arterial A-a gradient, and Metabolic lactic acidosis in obstructive shock)", "Serum Creatinine and eGFR"),
                Arrays.asList("Right ventricular dilation with RV/LV basal diameter ratio > 1.0 in apical 4-chamber view", "McConnell's sign (distinctive akinesis of the mid-free wall of the RV with preserved contractility of the RV apex)", "Tricuspid Annular Plane Systolic Excursion (TAPSE < 16 mm indicating RV systolic failure)", "Tricuspid Regurgitation peak velocity > 2.8 m/s estimating elevated Pulmonary Artery Systolic Pressure (PASP 35-60 mmHg)", "Paradoxical leftward bowing of the interventricular septum during diastole and systole ('D-shaped' left ventricle)", "Dilated Inferior Vena Cava (> 2.1 cm with loss of inspiratory collapse)"),
                Arrays.asList("Acute Myocardial Infarction (Anterior or Inferior STEMI)", "Acute Aortic Dissection (Stanford Type A)", "Cardiac Tamponade", "Acute Exacerbation of COPD / Severe Asthma", "Tension Pneumothorax", "Acute Heart Failure / Cardiogenic Shock", "Septic Shock / Severe Pneumonia"),
                Arrays.asList("Immediate Systemic Thrombolytic Therapy (First-line for Massive PE with hemodynamic instability/shock): Recombinant Tissue Plasminogen Activator (Alteplase / rtPA 100 mg IV infusion over 2 hours, OR accelerated regimen 50 mg IV bolus over 15 minutes in cardiac arrest) OR Tenecteplase (TNK-tPA weight-based 30-50 mg IV bolus over 5 seconds)", "Immediate Parenteral Anticoagulation: Unfractionated Heparin (80 units/kg IV bolus followed by 18 units/kg/hr infusion titrated to aPTT 1.5-2.5x control or anti-Xa 0.3-0.7 - preferred over LMWH in unstable patients due to short half-life and protamine reversibility) OR Enoxaparin (1 mg/kg SC q12h) OR Fondaparinux (7.5 mg SC daily for 50-100 kg)", "Inotropic & Vasopressor Support for Obstructive Shock: Norepinephrine (0.05-0.5 mcg/kg/min) to maintain systemic perfusion pressure and coronary perfusion to the failing RV, +/- Dobutamine (2.5-10 mcg/kg/min); CAUTION with aggressive IV fluid loading (limit to <= 500 mL crystalloid, as excessive fluids worsen RV dilation and ischemia)", "Long-Term Oral Anticoagulation (Minimum 3-6 months for provoked PE, Indefinite for unprovoked or recurrent PE/antiphospholipid syndrome): Direct Oral Anticoagulants (DOACs - Apixaban 10 mg bid x 7 days then 5 mg bid, OR Rivaroxaban 15 mg bid x 21 days then 20 mg daily, OR Dabigatran/Edoxaban after 5 days of parenteral heparin) OR Warfarin (target INR 2.0-3.0)"),
                Arrays.asList("Catheter-Directed Thrombolysis (CDT: Ultrasound-assisted Ekosonic system or low-dose Alteplase 0.5-1.0 mg/hr/catheter) for submassive/massive PE with high bleeding risk", "Percutaneous Mechanical Thrombectomy (FlowTriever or Indigo aspiration catheter to rapidly extract large emboli without systemic lytics)", "Surgical Pulmonary Embolectomy (Trendelenburg procedure on cardiopulmonary bypass) for massive PE when thrombolysis is contraindicated or has failed", "Inferior Vena Cava (IVC) Filter (retrievable Greenfield/Celect filter) STRICTLY indicated for documented acute proximal DVT/PE with absolute contraindication to anticoagulation or recurrent PE despite therapeutic anticoagulation", "Veno-Arterial Extracorporeal Membrane Oxygenation (VA-ECMO) as bridge to surgical embolectomy or recovery in refractory cardiopulmonary collapse"),
                "High acute mortality in massive PE (25-50% within the first 1-2 hours if untreated). Prompt recognition and aggressive reperfusion (systemic thrombolysis or catheter/surgical embolectomy) reduce in-hospital mortality to < 10-15%. Long-term complications include Chronic Thromboembolic Pulmonary Hypertension (CTEPH in 1-4% of survivors, requiring lifelong anticoagulation and pulmonary endarterectomy or riociguat/balloon pulmonary angioplasty) and Post-Pulmonary Embolism Syndrome (chronic exertional dyspnea).");

        add("I71.01", "Dissection of Thoracic Aorta (Stanford Type A / DeBakey I & II)", "Diseases of Arteries and Capillaries",
                "Catastrophic surgical emergency characterized by a tear in the intima of the ascending thoracic aorta, allowing blood under pulsatile systemic pressure to enter the aortic media, creating a false lumen that propagates proximally toward the aortic root and distally along the entire aorta. Pathophysiology is driven by cystic medial degeneration, fragmentation of elastic fibers, long-standing severe hypertension, connective tissue disorders (Marfan syndrome FBN1 mutation, Loeys-Dietz TGFBR1/2, Vascular Ehlers-Danlos COL3A1, Bicuspid Aortic Valve), and cocaine use.",
                Arrays.asList("Abrupt, catastrophic onset of maximum-intensity tearing, ripping, or sharp chest and interscapular back pain ('felt like being stabbed with a sword')", "Radiation of pain migrating downward into the abdomen, lumbar region, or legs as the dissection extends distally", "Syncope (present in 15-20%, indicating cardiac tamponade, cerebral malperfusion, or aortic rupture)", "Asymmetric peripheral pulses and blood pressure differential (> 20 mmHg systolic difference between right and left arm)", "New high-pitched early diastolic decrescendo murmur of Acute Aortic Regurgitation (due to aortic root dilation or cusp detachment)", "Focal neurological deficits (hemiplegia, Horner syndrome, hoarseness due to recurrent laryngeal nerve compression)", "Acute heart failure symptoms or sudden cardiac arrest due to hemopericardium and cardiac tamponade"),
                Arrays.asList("Emergent Contrast-Enhanced Computed Tomography Aortography (CTA of Chest, Abdomen, and Pelvis) is the gold standard imaging modality (demonstrating intimal flap separating true and false lumens, entry tear location, extension into coronary, brachiocephalic, renal, and iliac branches)", "Transesophageal Echocardiography (TEE - for hemodynamically unstable patients in the operating room, evaluating ascending aorta, aortic valve regurgitation, and pericardial effusion)", "Magnetic Resonance Angiography (MRA - reserved for stable patients with severe iodinated contrast allergy)"),
                Arrays.asList("Non-specific ST-T wave changes in > 50% of cases", "Inferior or Anterior STEMI pattern (ST elevation in II, III, aVF or V1-V4) in 1-2% of cases when the dissection flap dissects retrogradely into the Right Coronary Artery (RCA) or LAD ostium", "Low QRS voltage and electrical alternans if massive hemopericardium and cardiac tamponade develop"),
                Arrays.asList("High-sensitivity Cardiac Troponin (may be elevated due to coronary malperfusion or myocardial stretch)", "Plasma D-Dimer (markedly elevated > 500 ng/mL; D-dimer < 500 ng/mL has 97% negative predictive value to rule out acute aortic dissection)", "Complete Blood Count (leukocytosis, normocytic anemia if significant extravasation/rupture)", "Serum Creatinine and BUN (evaluating renal branch malperfusion and acute renal ischemia)", "Serum Lactate (elevated in mesenteric ischemia / visceral malperfusion)", "Type and Screen / Crossmatch for 6-10 units PRBC, FFP, and Platelets"),
                Arrays.asList("Direct visualization of the undulating intimal flap in the ascending aorta", "Assessment of Acute Aortic Regurgitation severity (vena contracta width, pressure half-time)", "Identification of pericardial effusion and echocardiographic signs of Cardiac Tamponade (Right atrial systolic collapse, Right ventricular diastolic collapse, IVC plethora)", "Coronary ostial involvement visualization", "Assessment of baseline Left Ventricular Ejection Fraction"),
                Arrays.asList("Acute ST-Elevation Myocardial Infarction (STEMI - catastrophic error if thrombolytic or full anticoagulation is administered)", "Acute Pulmonary Embolism", "Acute Pericarditis / Cardiac Tamponade of non-aortic etiology", "Spontaneous Pneumothorax / Boerhaave Syndrome (esophageal rupture)", "Acute Musculoskeletal Thoracic Pain / Thoracic Disk Herniation"),
                Arrays.asList("Immediate Medical Stabilization / Anti-Impulse Therapy in the Intensive Care Unit while mobilizing the cardiac surgical team:", "Target Heart Rate <= 60 bpm and Target Systolic Blood Pressure 100-120 mmHg (or lowest tolerated mean arterial pressure >= 60-70 mmHg to maintain end-organ perfusion while minimizing aortic wall shear stress dP/dt):", "First-Line: Intravenous Beta-Blockers (Esmolol loading dose 500 mcg/kg over 1 min then 50-300 mcg/kg/min infusion, OR Labetalol 20 mg IV push q10min up to 300 mg, OR Metoprolol 5 mg IV q5min up to 15 mg) - MUST be initiated BEFORE vasodilators to prevent reflex tachycardia", "Second-Line: Intravenous Vasodilators (Nicardipine infusion 5-15 mg/hr OR Sodium Nitroprusside 0.3-3.0 mcg/kg/min) added ONLY AFTER adequate beta-blockade is achieved", "Adequate Analgesia: Intravenous Morphine (2-4 mg IV) or Fentanyl (25-50 mcg IV) to reduce sympathetic surge", "STRICTLY CONTRAINDICATED: Anticoagulants (Heparin), Antiplatelets (Aspirin, Clopidogrel), and Thrombolytics"),
                Arrays.asList("EMERGENT OPEN SURGICAL REPAIR under cardiopulmonary bypass with deep hypothermic circulatory arrest (DHCA):", "Resection of the intimal entry tear and replacement of the ascending aorta with a Dacron prosthetic vascular graft (Hemiarch or Total Aortic Arch Replacement with Frozen Elephant Trunk if arch is involved)", "Aortic Valve Resuspension or Composite Valve-Graft Conduit (Bentall procedure with mechanical or bioprosthetic valve) if the aortic root and valve leaflets are damaged", "Coronary Artery Bypass Grafting (CABG) or coronary ostial reimplantation if dissection involves coronary ostia"),
                "Extreme lethality without emergent surgery, with mortality increasing by 1-2% per hour for the first 24-48 hours (approaching 50% at 48 hours and > 90% at 3 months if untreated). Leading causes of death are intrapericardial rupture causing fatal cardiac tamponade, acute severe aortic regurgitation with cardiogenic shock, coronary malperfusion with massive myocardial infarction, acute stroke, and aortic rupture into the pleural cavity. Emergency surgical repair achieves in-hospital survival rates of 75-85%.");
    }

    private static void add(String code, String name, String sub, String patho,
                            List<String> clin, List<String> diag, List<String> ecg,
                            List<String> labs, List<String> echo, List<String> diff,
                            List<String> rx, List<String> surg, String prog) {
        ENTRIES.add(CardioDiseaseEntry.builder()
                .icd10Code(code)
                .diseaseName(name)
                .subcategory(sub)
                .pathophysiology(patho)
                .clinicalPresentation(clin)
                .diagnosticCriteria(diag)
                .ecgFindings(ecg)
                .laboratoryBiomarkers(labs)
                .echocardiographyFindings(echo)
                .differentialDiagnoses(diff)
                .firstLinePharmacotherapy(rx)
                .interventionalSurgicalOptions(surg)
                .prognosisAndComplications(prog)
                .build());
    }

    public List<CardioDiseaseEntry> search(String query) {
        if (query == null || query.isBlank()) {
            return ENTRIES;
        }
        String q = query.toLowerCase().trim();
        return ENTRIES.stream()
                .filter(e -> e.getIcd10Code().toLowerCase().contains(q) ||
                             e.getDiseaseName().toLowerCase().contains(q) ||
                             e.getSubcategory().toLowerCase().contains(q) ||
                             e.getPathophysiology().toLowerCase().contains(q))
                .collect(Collectors.toList());
    }

    public Optional<CardioDiseaseEntry> findByCode(String code) {
        return ENTRIES.stream()
                .filter(e -> e.getIcd10Code().equalsIgnoreCase(code))
                .findFirst();
    }
}
