package com.hospital.clinical.encyclopedia;

import lombok.Builder;
import lombok.Data;
import org.springframework.stereotype.Component;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Enterprise ICD-10-CM Neurology & Infectious Diseases Clinical Encyclopedia (Chapters I & VI: A00-B99, G00-G99).
 * Comprehensive clinical monographs for Acute Ischemic Stroke (AHA/ASA guidelines, NIHSS, Alteplase/Tenecteplase),
 * Bacterial Meningitis, Sepsis & Septic Shock (Sepsis-3 definitions), Status Epilepticus, and Intracranial Hemorrhage.
 */
@Component
public class Icd10NeurologyInfectiousEncyclopedia {

    @Data
    @Builder
    public static class NeuroInfectiousDiseaseEntry {
        private String icd10Code;
        private String diseaseName;
        private String chapterCategory;
        private String pathophysiology;
        private List<String> clinicalManifestations;
        private List<String> diagnosticWorkup;
        private List<String> neuroimagingAndCsfProfile;
        private List<String> clinicalScoringAndStaging;
        private List<String> differentialDiagnoses;
        private List<String> emergencyPharmacotherapy;
        private List<String> endovascularAndSurgicalInterventions;
        private String complicationsAndPrognosis;
    }

    private static final List<NeuroInfectiousDiseaseEntry> ENTRIES = new ArrayList<>();

    static {
        // =========================================================================
        // SECTION 1: CEREBROVASCULAR & NEUROLOGICAL EMERGENCIES (I63, G00 - G99)
        // =========================================================================
        add("I63.50", "Cerebral Infarction (Acute Ischemic Stroke) of Middle Cerebral Artery", "Cerebrovascular Diseases",
                "Acute focal neurological deficit caused by sudden disruption of cerebral arterial blood flow (Middle Cerebral Artery MCA M1/M2 segment in > 50% of cases) due to thrombosis (large artery atherosclerosis) or thromboembolism (cardioembolic from atrial fibrillation, mural thrombus, or aortic atheroma). Cellular pathophysiology: Within seconds of ischemia, loss of ATP halts Na+/K+-ATPase pumps, causing rapid neuronal depolarization, massive presynaptic release of toxic glutamate, activation of postsynaptic NMDA/AMPA receptors, massive intracellular calcium influx (excitotoxicity), generation of reactive oxygen species (ROS), activation of calpains and caspases, mitochondrial permeability transition, breakdown of the blood-brain barrier (BBB), and neuronal apoptosis/necrosis. The central 'ischemic core' (cerebral blood flow CBF < 10-12 mL/100g/min) undergoes rapid irreversible infarction within minutes; the surrounding 'ischemic penumbra' (CBF 12-22 mL/100g/min) remains electrically silent but metabolically viable for 6 to 24 hours, representing the primary target for acute reperfusion therapy.",
                Arrays.asList("Sudden-onset contralateral hemiparesis or hemiplegia (typically affecting the face and upper extremity more severely than the lower extremity)", "Contralateral hemisensory loss (numbness, paresthesias)", "Aphasia in dominant hemisphere (typically Left MCA: Broca's expressive non-fluent aphasia, Wernicke's receptive fluent aphasia, or Global aphasia)", "Hemispatial Neglect / Agnosia / Apraxia in non-dominant hemisphere (typically Right MCA: extinction to double simultaneous stimulation, anosognosia)", "Homonymous Hemianopia (contralateral visual field deficit)", "Conjugate gaze deviation towards the side of the cerebral lesion ('looking at the lesion')", "Dysarthria, ataxia, facial droop (positive BE-FAST screening: Balance, Eyes, Face, Arms, Speech, Time)"),
                Arrays.asList("EMERGENT NON-CONTRAST HEAD CT (NCCT): Performed within 20 minutes of hospital arrival (Door-to-CT time < 20 min) to IMMEDIATELY RULE OUT INTRACRANIAL HEMORRHAGE (absolute contraindication to thrombolysis);", "ASPECTS SCORE (Alberta Stroke Program Early CT Score: 0-10 on NCCT; baseline normal = 10; 1 point deducted for early ischemic change in each of 10 MCA regions; ASPECTS <= 5 indicates large established core infarction with higher risk of hemorrhagic transformation);", "MULTIMODAL CT/MR ANGIOGRAPHY & PERFUSION (CTA/CTP or MRA/DWI-PWI): Mandatory to identify Large Vessel Occlusion (LVO: Internal Carotid Artery ICA terminus, MCA M1/M2 segments, Basilar Artery) and quantify the Ischemic Core vs Penumbral Mismatch ratio (Penumbral volume >= 15 mL and Mismatch ratio >= 1.8 for Extended Window Endovascular Thrombectomy up to 24 hours - DAWN / DEFUSE-3 criteria);", "Continuous Cardiac Telemetry / 24-48hr Holter monitoring to screen for occult Paroxysmal Atrial Fibrillation;", "Transthoracic / Transesophageal Echocardiography to identify cardioembolic sources (LAA thrombus, patent foramen ovale PFO with right-to-left shunt, aortic arch atheroma);", "Carotid Duplex Ultrasound (quantifying internal carotid artery stenosis >= 50-99%)"),
                Arrays.asList("Non-Contrast CT Early Ischemic Signs: Loss of insular ribbon sign, obscuration of lentiform nucleus, cortical sulcal effacement, and 'Hyperdense MCA Sign' (direct visualization of acute intra-arterial thrombus);", "Diffusion-Weighted MRI (DWI): Hyperintensity on DWI with corresponding hypointensity on Apparent Diffusion Coefficient (ADC) map (detects cytotoxic edema within 15-30 minutes of symptom onset with > 95% sensitivity);", "CT Perfusion (CTP): Cerebral Blood Flow (CBF < 30% of normal contralateral tissue defines ischemic core) and Time-to-Maximum (Tmax > 6.0 seconds defines hypoperfused tissue/penumbra)"),
                Arrays.asList("NATIONAL INSTITUTES OF HEALTH STROKE SCALE (NIHSS: 0-42):", "- 0: No stroke symptoms;", "- 1-4: Minor stroke;", "- 5-15: Moderate stroke;", "- 16-20: Moderate to severe stroke;", "- 21-42: Severe stroke (High risk of malignant cerebral edema and herniation);", "TOAST Etiological Classification of Ischemic Stroke: (1) Large-artery atherosclerosis, (2) Cardioembolism, (3) Small-vessel occlusion / Lacunar stroke, (4) Stroke of other determined etiology (cervical artery dissection, vasculitis), (5) Stroke of undetermined etiology (Cryptogenic / ESUS)"),
                Arrays.asList("Acute Intracranial Hemorrhage (Intracerebral, Subarachnoid, Subdural, Epidural hematoma)", "Hypoglycemia (Blood glucose < 60 mg/dL - mandatory bedside fingerstick before thrombolysis; rapidly mimics focal hemiplegia)", "Post-Ictal Todd's Paralysis (transient focal neurological deficit following an unobserved focal motor seizure)", "Complicated Hemiplegic Migraine", "Wernicke's Encephalopathy (thiamine deficiency)", "Acute Intracranial Neoplasm / Glioblastoma or Brain Abscess", "Functional / Conversion Neurological Disorder"),
                Arrays.asList("INTRAVENOUS THROMBOLYTIC THERAPY (Within 0 to 4.5 hours of Last Known Well LKW - Class I, Level A):", "- ALTEPLASE (rtPA): 0.9 mg/kg total dose (MAXIMUM 90 mg) administered as 10% IV bolus over 1 minute, followed by remaining 90% as continuous IV infusion over 60 minutes; OR", "- TENECTEPLASE (TNK-tPA - 2023/2024 AHA Guidelines): 0.25 mg/kg single IV bolus over 5-10 seconds (MAXIMUM 25 mg; superior ease of administration and higher early recanalization rates for large vessel occlusions);", "- BLOOD PRESSURE PROTOCOL FOR THROMBOLYSIS: BP must be strictly lowered to < 185/110 mmHg BEFORE initiating thrombolysis and maintained < 180/105 mmHg for >= 24 hours post-thrombolysis using IV Labetalol (10-20 mg IV push), IV Nicardipine (5-15 mg/hr), or IV Clevidipine (1-2 mg/hr);", "- STRICT CONTRAINDICATIONS TO THROMBOLYSIS: Intracranial hemorrhage on CT, prior ischemic stroke or severe head trauma within 3 months, active internal bleeding, platelet count < 100,000/uL, INR > 1.7 or therapeutic DOAC ingestion within 48 hours, SBP > 185 or DBP > 110 refractory to antihypertensives, infective endocarditis, aortic arch dissection;", "ANTIPLATELET & STATIN SECONDARY PREVENTION (Initiated 24 hours post-thrombolysis after repeat CT confirms no hemorrhage):", "- Dual Antiplatelet Therapy (DAPT) for Minor Ischemic Stroke (NIHSS <= 3) or High-Risk TIA (ABCD2 >= 4): Aspirin 300 mg load then 100 mg daily + Clopidogrel 300 mg load then 75 mg daily for EXACTLY 21 DAYS (CHANCE and POINT trials demonstrated significant reduction in recurrent ischemic stroke without excess hemorrhage), followed by single antiplatelet monotherapy;", "- High-Intensity Statin Therapy: Atorvastatin 80 mg daily (SPARCL trial demonstrated 16% relative risk reduction in recurrent stroke);", "- Oral Anticoagulation for Cardioembolic Stroke in Atrial Fibrillation: DOAC (Apixaban, Rivaroxaban, Dabigatran) initiated according to the '1-3-6-12 Day Rule' based on stroke severity (Day 1 for TIA, Day 3 for mild stroke NIHSS < 8, Day 6 for moderate stroke NIHSS 8-15, Day 12-14 for severe stroke NIHSS > 15 to minimize hemorrhagic transformation)"),
                Arrays.asList("ENDOVASCULAR MECHANICAL THROMBECTOMY (EVT - Landmark Standard of Care for Large Vessel Occlusions):", "- Indicated for acute ischemic stroke with confirmed Large Vessel Occlusion (LVO: Internal Carotid Artery or M1 segment of MCA) and baseline ASPECTS >= 6 and pre-stroke mRS 0-1 within 0 to 6 hours of onset (HERMES meta-analysis - NNT = 2.6 for functional independence mRS 0-2);", "- EXTENDED TIME WINDOW THROMBECTOMY (6 to 24 hours from Last Known Well): Supported by DAWN and DEFUSE-3 trials for patients with clinical-imaging mismatch or penumbral mismatch on CTP/MRI;", "- Technique: Direct microcatheter aspiration (ADAPT technique) and/or Stent-Retriever deployment (Solitaire / Trevo devices) targeting modified TICI 2b/3 (Thrombolysis in Cerebral Infarction complete reperfusion);", "DECOMPRESSIVE HEMICRANIECTOMY (Emergency Neurosurgical Intervention): Mandatory within 24-48 hours for 'Malignant MCA Infarction' (massive edema involving > 50% of the MCA territory in patients age <= 60 with declining GCS; reduces mortality from 80% to < 20% and prevents fatal uncal/transtentorial brain herniation);", "CAROTID ENDARTERECTOMY (CEA) or CAROTID ARTERY STENTING (CAS): Indicated within 14 days of minor stroke/TIA for symptomatic severe internal carotid artery stenosis (70-99% NASCET criteria)"),
                "Prognosis is measured by the Modified Rankin Scale (mRS at 90 days: 0-2 = Functional Independence; 3-5 = Moderate to Severe Disability; 6 = Death). In-hospital mortality for unselected ischemic stroke is approx 8-12%, but exceeds 60-80% in malignant MCA infarction without surgical decompression. Major complications: (1) Hemorrhagic Transformation (symptomatic intracerebral hemorrhage in 5-6% of thrombolysis patients and up to 15% of large core infarctions); (2) Malignant Cerebral Edema (peaking at 72-96 hours post-stroke; treated with 3% Hypertonic Saline 250 mL bolus or Mannitol 0.5-1.0 g/kg and emergency hemicraniectomy); (3) Post-Stroke Aspiration Pneumonia; (4) Deep Vein Thrombosis and Pulmonary Embolism (intermittent pneumatic compression IPC devices mandatory); (5) Post-Stroke Depression and Vascular Cognitive Impairment.");

        add("A41.9", "Sepsis, Unspecified Organism (Sepsis-3 Sepsis and Septic Shock)", "Infectious Diseases",
                "Life-threatening organ dysfunction caused by a dysregulated, maladaptive host immune response to documented or suspected infection. Pathophysiology (Sepsis-3 International Consensus Definitions): Pathogen-Associated Molecular Patterns (PAMPs e.g. Lipopolysaccharide LPS / Endotoxin in Gram-negative bacteria, Peptidoglycan and Lipoteichoic acid in Gram-positive bacteria) bind to host Pattern Recognition Receptors (Toll-Like Receptors TLR-4, TLR-2) on macrophages and dendritic cells, triggering massive nuclear translocation of NF-kappaB and transcription of pro-inflammatory cytokines ('Cytokine Storm': TNF-alpha, IL-1beta, IL-6, IL-12, IFN-gamma). This triggers widespread systemic endothelial cell activation and damage, loss of endothelial glycocalyx barrier, diffuse capillary leakage with massive intravascular fluid extravasation, systemic microvascular thrombosis (disseminated intravascular coagulation DIC) mediated by Tissue Factor expression and loss of natural anticoagulants (Protein C, Antithrombin III), cellular mitochondrial dysfunction causing impaired oxygen utilization (cytopathic dysoxia), and severe systemic vasodilatation mediated by inducible Nitric Oxide Synthase (iNOS), leading to distributive shock, tissue hypoperfusion, lactic acidosis, and Multi-Organ Dysfunction Syndrome (MODS: ARDS, Acute Tubular Necrosis, Ischemic Hepatitis, Sepsis-Induced Cardiomyopathy, and Encephalopathy).",
                Arrays.asList("Fever (Body Temperature > 38.3°C / 101.0°F) OR Hypothermia (< 36.0°C / 96.8°F - ominous sign in elderly/immunocompromised with high mortality)", "Tachycardia (Heart Rate > 90-120 bpm) and Tachypnea (Respiratory Rate > 20-30 breaths/min)", "Profound hypotension (Systolic BP < 90 mmHg, Mean Arterial Pressure MAP < 65 mmHg, or SBP drop > 40 mmHg from baseline)", "Acute encephalopathy / Sepsis-Associated Encephalopathy (SAE: Confusion, disorientation, agitation, lethargy, delirium, or coma)", "Warm, flushed, vasodilated extremities with bounding pulses in early hyperdynamic phase; progressing to cold, clammy, cyanotic, mottled extremities (Mottling Score 0-5 over knees) with delayed capillary refill (> 3 seconds) in established shock", "Oliguria (Urine output < 0.5 mL/kg/hour for > 2 hours) and Jaundice", "Petechiae, purpura fulminans, or ecchymoses indicating Disseminated Intravascular Coagulation (DIC)"),
                Arrays.asList("SEPSIS-3 DIAGNOSTIC CRITERIA (2016 / 2021 Surviving Sepsis Campaign):", "(1) Documented or clinically suspected infection; AND", "(2) Acute increase in TOTAL SOFA SCORE (Sequential Organ Failure Assessment) by >= 2 points from baseline (reflecting an overall in-hospital mortality risk > 10%);", "SEPTIC SHOCK DEFINITION (Subset of sepsis with profound circulatory and cellular/metabolic abnormalities):", "- Persistent hypotension requiring VASOPRESSORS to maintain Mean Arterial Pressure (MAP) >= 65 mmHg; AND", "- Serum Lactate > 2.0 mmol/L (18 mg/dL) despite adequate volume resuscitation of >= 30 mL/kg crystalloid (associated with in-hospital mortality > 40%);", "BEDSIDE SCREENING: Quick SOFA (qSOFA Score >= 2: Respiratory rate >= 22/min, Altered mentation GCS < 15, Systolic BP <= 100 mmHg; prompt bedside identification of patients at high risk of deterioration)"),
                Arrays.asList("Blood Cultures (At least 2 sets: 2 aerobic and 2 anaerobic blood culture bottles drawn from separate venipuncture sites BEFORE initiating antimicrobials, without delaying antibiotic therapy > 45 minutes)", "Site-Specific Diagnostic Cultures: Sputum/endotracheal aspirate Gram stain and culture, Clean-catch urinalysis and urine culture, Wound/abscess fluid aspirate, Peritoneal/pleural/synovial fluid, CSF in suspected meningitis", "High-Resolution CT or Ultrasound for Rapid Source Identification (CT Abdomen/Pelvis for occult intra-abdominal abscess/peritonitis; CXR/CT Chest for pneumonia; Renal ultrasound for obstructive pyelonephritis/hydronephrosis)"),
                Arrays.asList("SOFA SCORE COMPONENTS (0-4 points for each of 6 organ systems):", "- Respiration: PaO2/FiO2 ratio (400 = 0, < 400 = 1, < 300 = 2, < 200 with ventilation = 3, < 100 with ventilation = 4);", "- Coagulation: Platelet count (>= 150k = 0, < 150k = 1, < 100k = 2, < 50k = 3, < 20k = 4);", "- Liver: Serum Total Bilirubin (< 1.2 = 0, 1.2-1.9 = 1, 2.0-5.9 = 2, 6.0-11.9 = 3, >= 12.0 mg/dL = 4);", "- Cardiovascular: MAP or Vasopressor requirement (MAP >= 70 = 0, MAP < 70 = 1, Dopamine <= 5 or Dobutamine = 2, Norepinephrine <= 0.1 = 3, Norepinephrine > 0.1 mcg/kg/min = 4);", "- Central Nervous System: Glasgow Coma Scale (15 = 0, 13-14 = 1, 10-12 = 2, 6-9 = 3, < 6 = 4);", "- Renal: Serum Creatinine or Urine Output (Cr < 1.2 = 0, 1.2-1.9 = 1, 2.0-3.4 = 2, 3.5-4.9 = 3, >= 5.0 mg/dL or UO < 200 mL/day = 4)"),
                Arrays.asList("Severe Hypovolemic Shock (hemorrhagic, severe dehydration; low CVP, low cardiac output, dry mucous membranes)", "Cardiogenic Shock (acute myocardial infarction, severe myocarditis, acute valvular rupture; elevated JVP, pulmonary edema, low cardiac index < 2.2 L/min/m2, elevated SVR)", "Obstructive Shock (massive pulmonary embolism, tension pneumothorax, cardiac tamponade)", "Anaphylactic Shock (severe acute allergen exposure, urticaria, angioedema, stridor, wheezing)", "Adrenal Crisis / Acute Addisonian Shock (refractory hypotension, hyponatremia, hyperkalemia, hypoglycemia)", "Severe Acute Pancreatitis (non-infectious SIRS mimic with massive third-spacing)", "Thyroid Storm"),
                Arrays.asList("SURVIVING SEPSIS CAMPAIGN 1-HOUR HOUR-1 BUNDLE (ALL 5 ELEMENTS TO BE INITIATED WITHIN 60 MINUTES):", "(1) MEASURE SERUM LACTATE: Remeasure within 2-4 hours if initial lactate > 2.0 mmol/L to guide resuscitation and lactate clearance (target >= 20% clearance every 2 hours);", "(2) OBTAIN BLOOD CULTURES PRIOR TO ANTIMICROBIALS;", "(3) ADMINISTER BROAD-SPECTRUM EMPIRIC INTRAVENOUS ANTIMICROBIALS (Within 1 hour):", "- Community-Acquired Sepsis: Piperacillin-Tazobactam 4.5g IV q6h (or Cefepime 2g IV q8h or Meropenem 1g IV q8h) + Vancomycin 15-20 mg/kg IV q8-12h (targeting trough 15-20 mcg/mL or AUC 400-600) for MRSA coverage;", "- Hospital-Acquired / Neutropenic Sepsis / High MDR Risk: Meropenem 1g IV q8h extended 3-hour infusion + Vancomycin 15-20 mg/kg + Amikacin 15-20 mg/kg IV single daily dose or Polymyxin B / Colistin;", "(4) RAPID FLUID RESUSCITATION: Administer AT LEAST 30 mL/kg of Isotonic Balanced Crystalloids (Lactated Ringer's or Plasmalyte - SMART and SALT-ED trials demonstrated lower mortality and renal failure compared to 0.9% Normal Saline) within the first 3 hours for hypotension or lactate >= 4.0 mmol/L; Assess Dynamic Measures of Fluid Responsiveness (Passive Leg Raise PLR test with real-time Stroke Volume measurement, Velocity-Time Integral VTI change, or Stroke Volume Variation SVV on arterial line) to avoid fluid overload;", "(5) ADMINISTER VASOPRESSORS (If MAP remains < 65 mmHg during or after fluid loading):", "- FIRST-LINE VASOPRESSOR: NOREPINEPHRINE (0.05 to 1.0+ mcg/kg/min IV infusion via central venous catheter, targeting Mean Arterial Pressure MAP >= 65 mmHg; potent alpha-1 vasoconstriction with modest beta-1 inotropic support);", "- SECOND-LINE VASOPRESSOR: VASOPRESSIN (Fixed-dose 0.03 units/minute continuous infusion added to norepinephrine to reduce norepinephrine dosage and restore vascular tone in relative vasopressin deficiency);", "- THIRD-LINE INOTROPE: DOBUTAMINE (2.5-20 mcg/kg/min added to norepinephrine if myocardial dysfunction, low cardiac output, or persistent hypoperfusion despite adequate volume and MAP);", "- REFRACTORY SEPTIC SHOCK: Intravenous Hydrocortisone (200 mg/day administered as 50 mg IV q6h or continuous infusion for septic shock requiring ongoing vasopressor support for >= 4 hours - ADRENAL and APROCCHSS trials)"),
                Arrays.asList("EMERGENT SURGICAL SOURCE CONTROL (Within 6 to 12 hours of diagnosis):", "- Laparotomy for perforated hollow viscus / generalized peritonitis / acute mesenteric ischemia;", "- Percutaneous or surgical drainage of intra-abdominal, perinephric, retroperitoneal, or hepatic abscesses;", "- Emergency Cholecystostomy / Cholecystectomy for acute gangrenous cholecystitis;", "- Emergency Ureteral Stenting or Percutaneous Nephrostomy (PCN) for obstructive pyelonephritis / infected hydronephrosis with ureteral stone;", "- Emergency Surgical Debridement and Fasciotomy for Necrotizing Fasciitis / Fournier Gangrene / Gas Gangrene;", "- Prompt Removal of Infected Vascular Lines / Central Venous Catheters / Urinary Catheters / Prosthetic Devices (source of catheter-related bloodstream infection CRBSI)"),
                "Sepsis is the leading cause of in-hospital death worldwide. Mortality in Sepsis without shock is approx 15-20%; mortality in Septic Shock with hyperlactatemia exceeds 40-50%. Major complications: (1) Acute Respiratory Distress Syndrome (ARDS in 30-50% requiring lung-protective mechanical ventilation); (2) Sepsis-Associated Acute Kidney Injury (requiring CRRT); (3) Disseminated Intravascular Coagulation (DIC with microvascular thrombosis and severe consumptive bleeding); (4) Sepsis-Induced Cardiomyopathy (biventricular systolic and diastolic dysfunction with depressed LVEF, typically reversible within 7-10 days in survivors); (5) Critical Illness Myopathy and Neuropathy (CIM/CIP); (6) Post-Sepsis Syndrome (persistent immune suppression, muscle wasting, cognitive decline, and 1-year mortality of 20-30%).");
    }

    private static void add(String code, String name, String chap, String patho,
                            List<String> clin, List<String> diag, List<String> img,
                            List<String> scor, List<String> diff, List<String> rx,
                            List<String> surg, String comp) {
        ENTRIES.add(NeuroInfectiousDiseaseEntry.builder()
                .icd10Code(code)
                .diseaseName(name)
                .chapterCategory(chap)
                .pathophysiology(patho)
                .clinicalManifestations(clin)
                .diagnosticWorkup(diag)
                .neuroimagingAndCsfProfile(img)
                .clinicalScoringAndStaging(scor)
                .differentialDiagnoses(diff)
                .emergencyPharmacotherapy(rx)
                .endovascularAndSurgicalInterventions(surg)
                .complicationsAndPrognosis(comp)
                .build());
    }

    public List<NeuroInfectiousDiseaseEntry> search(String query) {
        if (query == null || query.isBlank()) {
            return ENTRIES;
        }
        String q = query.toLowerCase().trim();
        return ENTRIES.stream()
                .filter(e -> e.getIcd10Code().toLowerCase().contains(q) ||
                             e.getDiseaseName().toLowerCase().contains(q) ||
                             e.getChapterCategory().toLowerCase().contains(q) ||
                             e.getPathophysiology().toLowerCase().contains(q))
                .collect(Collectors.toList());
    }

    public Optional<NeuroInfectiousDiseaseEntry> findByCode(String code) {
        return ENTRIES.stream()
                .filter(e -> e.getIcd10Code().equalsIgnoreCase(code))
                .findFirst();
    }
}
